### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ttmx** [florisboard/florisboard#1053]
I had just closed the keyboard, I would not even have noticed the crash if not for the notification.

#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Xiaomi POCO F1
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1625068709912.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:150)
	at dev.patrickgold.florisboard.ime.clip.provider.PinnedItemsDatabase$Companion.getInstance(FlorisDatabase.kt:198)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.initialize$lambda-3(FlorisClipboardManager.kt:276)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.lambda$Krs37l3asP-mgyTHLA2S-BiM2XA(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.clip.-$$Lambda$FlorisClipboardManager$Krs37l3asP-mgyTHLA2S-BiM2XA.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>

<details>
<summary>1625499657850.stacktrace</summary>

```
java.lang.ArrayIndexOutOfBoundsException: length=300; index=-1
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Gesture.getLastX(StatisticalGlideTypingClassifier.kt:549)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.pruneByExtremities(StatisticalGlideTypingClassifier.kt:283)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.unCachedGetSuggestions(StatisticalGlideTypingClassifier.kt:173)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.getSuggestions(StatisticalGlideTypingClassifier.kt:157)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$updateSuggestionsAsync$1.invokeSuspend(GlideTypingManager.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by GoRaN909** [comment]
You must Disable (Next-word suggestion) and all below the Suggestions also (Glide-typing) must be  Disabled. If you disable them at Settings you see the keyboard works like charm and no more crashes!

**Comment by Glitchy-Tozier** [comment]
1. Thank you for reporting this issue.  :)
2. For now it's best to just disable word-suggestions. In version v0.3.15, those crashes should be gone, even with activated word-suggestions.
3. I'll be closing this because many many issues are reporting the same OOM-crash.
