### ISSUE TITLE
Florisboard suddenly crash auto switch to my default keyboard

### ISSUE THREAD

**Issue by NSTAdventure** [florisboard/florisboard#1054]
#### Short description
I are currently not use keyobard yet and suddenly i got notifications that florisboard crash
Checking on keyboard and yes android are auto switching back to gboard as default and i had to relaunch that florisboard to work again

#### Steps to reproduce
1. (I also didn't know how to reproduce because accidentally happend while i not use florisboard yet)

#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Realme RMX2030
- Android: 10 (cn=Q sdk=29)

#### Features enabled
kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true

#### Attached stacktrace files
<details>
<summary>1625483936694.stacktrace</summary>

java.lang.IllegalArgumentException: View=DecorView@6baad9[InputMethod] not attached to window manager
 at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:550)
 at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:444)
 at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
 at android.app.Dialog.onWindowAttributesChanged(Dialog.java:800)
 at android.view.Window.dispatchWindowAttributesChanged(Window.java:1202)
 at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:3031)
 at android.view.Window.setLayout(Window.java:1005)
 at android.inputmethodservice.InputMethodService.onConfigureWindow(InputMethodService.java:1398)
 at android.inputmethodservice.InputMethodService.updateFullscreenMode(InputMethodService.java:1367)
 at dev.patrickgold.florisboard.ime.core.FlorisBoard.updateFullscreenMode(FlorisBoard.kt:303)
 at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2064)
 at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2046)
 at android.inputmethodservice.InputMethodService.access$500(InputMethodService.java:255)
 at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:626)
 at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:223)
 at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:238)
 at android.app.ActivityThread.main(ActivityThread.java:7853)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

</details>

**Comment by NSTAdventure** [comment]
I already set florisboard as default but I didn't use that to type yet before crash happend
