### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by manofmarvelous** [florisboard/florisboard#1055]
~~~ 1622603630007.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1622603630020.stacktrace ~~~

kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.Main, Continuation at kotlinx.coroutines.DeferredCoroutine.await$suspendImpl(Builders.common.kt:101)@f17f9ae]){CompletedContinuation(result=ComputedLayout(mode=NUMERIC_ADVANCED, name=computed, direction=ltr, arrangement=[[KeyData { type=CHARACTER code=43 label="+" }, KeyData { type=NUMERIC code=49 label="1" }, KeyData { type=NUMERIC code=50 label="2" }, KeyData { type=NUMERIC code=51 label="3" }, KeyData { type=CHARACTER code=37 label="%" }], [KeyData { type=CHARACTER code=40 label="(" }, KeyData { type=NUMERIC code=52 label="4" }, KeyData { type=NUMERIC code=53 label="5" }, KeyData { type=NUMERIC code=54 label="6" }, KeyData { type=CHARACTER code=32 label="space" }], [KeyData { type=CHARACTER code=41 label=")" }, KeyData { type=NUMERIC code=55 label="7" }, KeyData { type=NUMERIC code=56 label="8" }, KeyData { type=NUMERIC code=57 label="9" }, KeyData { type=ENTER_EDITING code=-5 label="delete" }], [KeyData { type=SYSTEM_GUI code=-201 label="view_characters" }, KeyData { type=CHARACTER code=44 label="," }, KeyData { type=SYSTEM_GUI code=-202 label="view_symbols" }, KeyData { type=NUMERIC code=48 label="0" }, KeyData { type=CHARACTER code=61 label="=" }, KeyData { type=CHARACTER code=46 label="." }, KeyData { type=ENTER_EDITING code=10 label="enter" }]]), cancelHandler=DisposeOnCancel[ResumeAwaitOnCompletion@84977e5[job@9ee02ba]], onCancellation=null, idempotentResume=null, cancelCause=null)}@508056b. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 120 byte allocation with 72 free bytes and 72B until OOM, target footprint 268435456, growth limit 268435456
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 7 more
~~~ 1624415847952.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1624895029911.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 144056 free bytes and 140KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1625626142610.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 199032 free bytes and 194KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug report!

Could you share what version of Florisboard you are using?  :)

**Comment by patrickgold** [comment]
As far as I can tell from the stacktrace the part which caused the OOM issue has been fixed by <span>@</span>X-yl already, so I will close this issue.
