### ISSUE TITLE
java no such element exception

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#1065]
#### Short description
I was trying to type with latest beta 0.3.13 beta 05 and randomly got crash twice. I was only able to get one crash log.

#### Steps to reproduce
Just when typing?😅

#### Environment information
- FlorisBoard Version: 0.3.13-beta05 (48)
- Device: Xiaomi POCO M2 Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1626163845353.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 28
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.leftAppendWordToSelection(EditorInstance.kt:418)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.handleDeleteSwipe(TextKeyboardView.kt:647)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onSwipe(TextKeyboardView.kt:581)
	at dev.patrickgold.florisboard.ime.text.gestures.SwipeGesture$Detector.onTouchMove(SwipeGesture.kt:136)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:326)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:83)
	at android.view.View.dispatchTouchEvent(View.java:13483)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2767)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:863)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:161)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
	at android.view.View.dispatchPointerEvent(View.java:13744)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5616)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5416)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4944)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4944)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7669)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7638)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7799)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:213)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7745)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7823)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:782)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>

Edit another crash again
#### Environment information
- FlorisBoard Version: 0.3.13-beta05 (48)
- Device: Xiaomi POCO M2 Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1626164023494.stacktrace</summary>

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:416)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.leftAppendWordToSelection(EditorInstance.kt:419)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.handleDeleteSwipe(TextKeyboardView.kt:647)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onSwipe(TextKeyboardView.kt:581)
	at dev.patrickgold.florisboard.ime.text.gestures.SwipeGesture$Detector.onTouchMove(SwipeGesture.kt:136)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:326)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:83)
	at android.view.View.dispatchTouchEvent(View.java:13483)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2767)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:863)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:161)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
	at android.view.View.dispatchPointerEvent(View.java:13744)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5616)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5416)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4944)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4944)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7669)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7638)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7799)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:213)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7745)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7823)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:782)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>

**Comment by Glitchy-Tozier** [comment]
Hi, do you happen to use word-deletion as your delete-swipe-action?

**Comment by pokegamer5547** [comment]
> Hi, do you happen to use word-deletion as your delete-swipe-action?
> 
> (the second log reminds me of #1076)

i'm really sorry for late response. yes i use "delete words precisely" mode
