### ISSUE TITLE
Florisboard crashed after rebooting when clipboard manager has some pinned items

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#1097]
If i pin some copied text in clipboard manager,
And reboot my device then after unlocking device, i got florisboard crash notification

BTW the copied text which is pinned in clipboard manager survives the reboot

Steps to reproduce
1. Enable clipboard manager 
2. Copy some text
3. Pin the copied text in clipboard manager
4. Reboot the device
5. After reboot is complete ,you will get a notification that florisboard is crashed on unlocking device

Log captured by florisboard: 
[Reboot crash.txt](https://github.com/florisboard/florisboard/files/6871769/Reboot.crash.txt)

Environment information
- FlorisBoard Version: 0.3.13beta06
- Install Source: github
- Device: Poco M2 pro
- Android: 11 Arrow os

**Comment by GithbUser** [comment]
Now i noticed it only crashes if i pin a copied item in clipboard manager 
But florisboard keep the pinned item safe after a reboot which is good

Maybe this is help

**Comment by patrickgold** [comment]
Thanks for your bug report! Will place this one on my todo list. Btw, you don't have to include the generated crash log as a txt file, you can just paste it into GitHub, the crash log is already formatted so it looks nice within a GH issue :)

**Comment by patrickgold** [comment]
Your above txt would look like this:

------

#### Environment information
- FlorisBoard Version: 0.3.13-beta06 (49)
- Device: Xiaomi POCO M2 Pro
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1627091528537.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$Companion.getInstance(FlorisContentProvider.kt:36)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:307)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by GithbUser** [comment]
Ok i will keep in mind to paste log directly 
Not in a text file

**Comment by patrickgold** [comment]
Above commit should fix the crash, will be available in the next beta.
