### ISSUE TITLE
Crash (cause unknown)

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1107]
#### Environment information
- FlorisBoard Version: 0.3.13-beta07 (50)
- Device: Xiaomi Mi 9T Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1627301863678.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:613)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateSelection(InputMethodService.java:725)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:103)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug-report.

 This issue has already been reported in #1018. (And will probably be fixed soon, seeing as how it has a priority-1-tag)

**Comment by patrickgold** [comment]
Thanks for your bug report! This crash is indeed the same as in #1018 and #1110 may be a fix for it. To keep the list of issues a bit more clean, I will close this issue as a duplicate and will use the PR and the original issue for discussion.
