### ISSUE TITLE
View is invalided from incorrect thread in TextKeyboardView.kt

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#1118]
#### Short description
Got this crash report via email, is caused because View is invalidated in incorrect thread.

#### Steps to reproduce
-- none --

#### Environment information
- FlorisBoard Version: 0.3.13-beta07 (50)
- Device: Motorola Moto E (4)
- Android: 7.1.1 (cn=N_MR1 sdk=25)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1627599561078.stacktrace</summary>

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6962)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1101)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:5209)
at android.view.View.invalidateInternal(View.java:13659)
at android.view.View.invalidate(View.java:13623)
at android.view.View.invalidate(View.java:13607)
at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$onGlideAddPoint$1.invokeSuspend(TextKeyboardView.kt:1283)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Fixed in above commit.
