### ISSUE TITLE
Whole-word swipe-deletion crashes app when swiping text with only numbers and symbols

### ISSUE THREAD

**Issue by KLaurence** [florisboard/florisboard#1130]
Edit by @patrickgold : This issue is the main discussion area for fixing word deletion related stuff all at once, which have piled up. Below you can still see the original issue comment.

---

#### Description
When swipe-deleting in a text box that exclusively contains numbers and symbols, the keyboard crashes. If the text box contains any single letter, the keyboard doesn't immediately crash. The error doesn't occur on per-character swipe-deletion.

Somehow related to #547. This issue is also somehow related to #1076, which is likely sufficiently different to this issue that this issue being a separate one is justified.

#### Steps to reproduce
1. Go to a text box where typing text is possible.
2. Type `123456789@#$%&-+()/*"':;!?`.
3. Focus the cursor on the very end of the text box.
4. Swipe the delete button to the left.

#### Environment information
- FlorisBoard Version: 0.3.13-beta08 (51)
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = false
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1628111146794.stacktrace</summary>

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:416)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.leftAppendWordToSelection(EditorInstance.kt:419)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.handleDeleteSwipe(TextKeyboardView.kt:651)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onSwipe(TextKeyboardView.kt:585)
	at dev.patrickgold.florisboard.ime.text.gestures.SwipeGesture$Detector.onTouchMove(SwipeGesture.kt:136)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:330)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:83)
	at android.view.View.dispatchTouchEvent(View.java:13620)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2774)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:506)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1857)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:873)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:152)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
	at android.view.View.dispatchPointerEvent(View.java:13884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6202)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5940)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5393)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5453)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5412)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5577)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5420)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5634)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5393)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5453)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5412)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5420)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5393)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8343)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8312)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8263)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8482)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8429)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8506)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

Sorry for not getting back to you sooner for all your word deletion issues, at the time I had a lot of stuff to do and whole-word deletion was not exactly a priority. Now I plan to finally tackle in and provide a fix in the beta10 release (so I start to work on it directly after tomorrow's beta09 release).

Currently I am preparing to collect all issues which are related to this and I will use this issue as the main discussion area for the bug. The following list is I think all issues regarding whole-word deletion:

- #1130
- #1076 
- #548 
- #547 
- #546 
- #1072
- #1065 

@Glitchy-Tozier do you know any other issues regarding current word/precise word deletion which are not on above list? I tried my best at searching all but I may have missed some.

So for fixing the bug I will probably do the following tasks:
- [ ] Rewrite word splitter logic
- [ ] Rework word selection logic
- [ ] Make sure that all array/selection access methods are crash-safe

The regex splitters is also a preparation step to properly split up words for the word suggestion feature (because currently for languages that don't follow basic Latin rules the word splitter can cause some issues with a potential suggestion algorithm).

**Comment by Glitchy-Tozier** [comment]
>@Glitchy-Tozier do you know any other issues regarding current word/precise word deletion which are not on above list? I tried my best at searching all but I may have missed some.

I checked but couldn't find any additional ones.

**Comment by KLaurence** [comment]
> Sorry for not getting back to you sooner for all your word deletion issues, at the time I had a lot of stuff to do and whole-word deletion was not exactly a priority.
>
> Currently I am preparing to collect all issues which are related to this and I will use this issue as the main discussion area for the bug.

It's completely understandable. With a repository of this size, keeping up with every single thing isn't really easy to do. I'm also perfectly fine with using this issue as the main one for this bug.

**Comment by tsiflimagas** [comment]
#1014

**Comment by patrickgold** [comment]
Thanks for noticing, will add it to the list!

**Comment by patrickgold** [comment]
Above PR is the first preview for the reworked cached input logic, which should also address the various issues with the delete swipe. @KLaurence or everyone interested: feel free to try out the debug APK and give feedback if the new logic breaks normal input, as well as the new delete swipe works. Note, that this PR is currently draft and I am working on polishing and fixing some minor issues still.

A question I came up with is, what should FlorisBoard even consider as a word? For now terms which look like the ones below are recognized as a word, everything else is considered a symbol or non-relevant character:

https://github.com/florisboard/florisboard/blob/abb460fba08c4009a8c42393d8543e7500f0b395/app/src/test/java/dev/patrickgold/florisboard/ime/core/TextProcessorTest.kt#L12-L29

Are these type of words enough or are there more words which can contain a special char and should still be considered one word?

**Comment by patrickgold** [comment]
I've now fixed some state bugs and the selection of only symbols at the beginning of the text boxes. The only issue that is now actively open in the PR is #548. How exactly should this partial selection work? I've tried the whole-word selection also on Gboard and you are correct, Gboard sometimes elects only some parts of the symbols, however I cannot figure out the logic behind that segmentation nor where it is useful.

**Comment by KLaurence** [comment]
> Feel free to try out the debug APK and give feedback if the new logic breaks normal input, as well as the new delete swipe works.

#1076 and #1130's crashes don't occur in my phone in the debug APK artifact. #547 is also fixed for me. The new consistent word-deletion swipe also works properly, behaving like Gboard's deletion selection.

I currently haven't found any bugs about them, but If I encounter one later, I'll report it here.

> Are these type of words enough or are there more words which can contain a special char and should still be considered one word?

I sadly don't know if the listed words are enough. I also currently don't know other words that can be added to the list.

> The only issue that is now actively open in the PR is #548. How exactly should this partial selection work?

The 'partial selection' should work, in my opinion, so that in a block of symbols, whole-word deletion should work like per-character swipe-deletion instead. An example using the text `/// Example sentence ///` would be like this.

#### Partial selection of symbols for deletion selection

| Steps swiped | Text selected to delete |
| :-- | --: |
| 1 | `/` |
| 2 | `//` |
| 3 | `///` |
| 4 | `sentence ///` |
| 5 | `Example sentence ///` |
| 6 | `/ Example sentence ///` |
| 7 | `// Example sentence ///` |
| 8 | `/// Example sentence ///` |
</details>

#### Debug APK and Gboard's current swipe-deletion selection

| Steps swiped | Text selected to delete |
| :-- | --: |
| 1 | `sentence ///` |
| 2 | `Example sentence ///` |
| 3 | `/// Example sentence ///` |

I think that this allows users to precisely choose the symbols they want to be deleted in texts with blocks of symbols. A disadvantage of this, though, is that users would need more swipes to delete the same text.

**Comment by patrickgold** [comment]
> #1076 and #1130's crashes don't occur in my phone in the debug APK artifact. #547 is also fixed for me. The new consistent word-deletion swipe also works properly, behaving like Gboard's deletion selection.

Thanks for testing it out, great to hear that it is fixed for you!

> The 'partial selection' should work, in my opinion, such that in parts of texts where block of symbols are, whole-word deletion should work like per-character swipe-deletion instead. An example using the text /// Example sentence /// would be like this.

I am still not sure if this is the best way to go, because it requires significantly more steps to do the swipe than Gboard's/Debug APK's behavior. What I can do is to leave #548 open for now and discuss this particular issue at a later stage. This issue is generally nice to fix but the important ones, like fixing the crashes and the general word detection logic, will definitely be in 0.3.13.

**Comment by KLaurence** [comment]
> I am still not sure if this is the best way to go, because it requires significantly more steps to do the swipe than Gboard's/Debug APK's behavior. What I can do is to leave #548 open for now and discuss this particular issue at a later stage.

It's understandable. 

I've also now just realized that <span>#</span>548's title makes it sound like a b2ug when it sounds more like a

**Comment by KLaurence** [comment]
Sorry, I accidentally pressed the close issue button.

**Comment by KLaurence** [comment]
> I am still not sure if this is the best way to go, because it requires significantly more steps to do the swipe than Gboard's/Debug APK's behavior. What I can do is to leave #548 open for now and discuss this particular issue at a later stage.

That's completely reasonable. It can make deletion more tedious than the current behavior.

Other than that, I've changed <span>#</span>548's title, as I've now just realized that its title makes it sound like a bug when the issue itself sounds more like a proposal instead (and an opinionated one at that) for partial/precise symbol selection.

**Comment by patrickgold** [comment]
> Other than that, I've changed #548's title, as I've now just realized that its title makes it sound like a bug when the issue itself sounds more like a proposal (and an opinionated one at that) for partial/precise symbol selection.

Perfect, we will work on #548 on a later stage then. As for the word deletion, I will merge the changes now in so I can work on fixing some other things for 0.3.13 stable next week, thanks for testing the debug build out!

**Comment by KLaurence** [comment]
Thank you, too, for fixing bugs such as these!
