### ISSUE TITLE
Mark a text in Firefox Adressbar

### ISSUE THREAD

**Issue by SomeGuy02** [florisboard/florisboard#1140]
(Sorry my English is not good. I'm from Germany.)

Short description
I have mark a Text for copy it.

#### Steps to reproduce
1. Go to 'Firefox'
2. Click on 'Adressbar'
3. Mark the 'URL'
4. Mark with the arrows
5. See crash

#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Xiaomi Mi Note 10
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1628334496271.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 18
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.Region.getText(EditorInstance.kt:914)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$2$1.invokeSuspend(TextInputManager.kt:459)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! As a lot has changed since 0.3.12, could you please try out the latest beta release 0.3.13-beta09 and see if this issue is still there? You can get the beta either from Google Play like the stable, from Izzy's F-Droid repo or from the GitHub releases. Thanks in advance!
