### ISSUE TITLE
Spacebar gesture crash

### ISSUE THREAD

**Issue by igor725** [florisboard/florisboard#1157]
#### Short description
Keyboard randomly crashes when I move the text cursor with a spacebar swipe gesture. Not the first time the application crashes like this, but I don't know how truly reproduce this crash due to its rarity.

#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Xiaomi M2102J20SG (POCO X3 PRO)
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1628961486817.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 104
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.Region.getText(EditorInstance.kt:914)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$2$1.invokeSuspend(TextInputManager.kt:459)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! I tried reproducing it but wasn't able to in the latest beta release. Could you try out the latest beta and check if the bug randomly occurs like in 0.3.12 or if it has gone away? This would be very helpful, thanks in advance!

**Comment by igor725** [comment]
Sure, I can try beta channel. I'll let you know if this issue happens again.

**Comment by igor725** [comment]
Looks like in the latest beta gestures are ok, but the backspace button sometimes gets stuck in pressed state. Omg, I'm lucky with strange bugs.

**Comment by patrickgold** [comment]
What is the latest beta for you? beta08 or beta09?

**Comment by igor725** [comment]
> 
> 
> What is the latest beta for you? beta08 or beta09?

Beta08 from f-droid, just checked for updates, now beta09. I see in the changelog, this issue is fixed by beta09. Thanks for everything.
