### ISSUE TITLE
'Delete key swipe left' bug

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1164]
#### Short description

If 'delete key swipe left' is set to 'delete words precisely', then if the first character of the line is a space, swiping on delete key till the start of the line crashes the keyboard.

#### Steps to reproduce
1. Set 'delete key swipe left' option to 'delete words precisely'
2. Enter at least one space, then optionally some text
3. Swipe on delete key till the start of the line

 #### Environment information
- FlorisBoard Version: 0.3.13-beta09 (52)
- Device: Xiaomi Redmi Note 8
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1629204731431.stacktrace</summary>

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:416)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.leftAppendWordToSelection(EditorInstance.kt:419)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.handleDeleteSwipe(TextKeyboardView.kt:646)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onSwipe(TextKeyboardView.kt:580)
	at dev.patrickgold.florisboard.ime.text.gestures.SwipeGesture$Detector.onTouchMove(SwipeGesture.kt:136)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:330)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:83)
	at android.view.View.dispatchTouchEvent(View.java:14309)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1874)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:160)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8099)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8050)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8011)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8222)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:201)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8179)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8261)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1046)
	at android.view.Choreographer.doCallbacks(Choreographer.java:869)
	at android.view.Choreographer.doFrame(Choreographer.java:796)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1031)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! This issue is already known and planned to be fixed in the next beta release, see #1130. Closing this issue as a duplicate.
