### ISSUE TITLE
FlorisBoard quits

### ISSUE THREAD

**Issue by tekreativ** [florisboard/florisboard#1165]
The device was asleep and there was a notification when I awakened it. This is a regular occurance and the app restarts and functions (I'm using it now) although at times I have to  reenable it in the Input method settings. Platform is Lineage OS 17.1 (June 2021, so 2 mos out of date).

~~~ 1629050347945.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1627166231403.stacktrace ~~~

java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
~~~ 1627763632034.stacktrace ~~~

~~~ 1627763638630.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:992)
~~~ 1627166229213.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 320 byte allocation with 128 free bytes and 128B until OOM, target footprint 268435456, growth limit 268435456
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
~~~ 1629050344327.stacktrace ~~~

java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
~~~ 1627763637894.stacktrace ~~~

**Comment by patrickgold** [comment]
What version of FlorisBoard are you running?
