### ISSUE TITLE
Crash switching from FlorisBoard to beta

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1180]
#### Short description
After duplicating and editing key colors in FlorisBoard beta I switched to and fro FlorisBoard and FB beta in order to make screenshots and compare them. While I succeeded doing that with FB, after switching back to beta the keyboard froze and constantly covered the screen, even when switching between several apps, that were now quasi background apps. Remarkable is that I had the keyboard switcher icon constantly on screen, even while the keyboard's focus was not on editable text.

#### Steps to reproduce
Not reproducible, hence the tale of what happened before the crash took place.

#### Environment information
- FlorisBoard Version: 0.3.13-beta10 (53)
- Device: Motorola Moto G (4)
- Android: 6.0.1 (cn=M sdk=23)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1629811913388.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 18 byte allocation with 3976 free bytes and 3KB until OOM
	at java.lang.StringFactory.newStringFromChars(Native Method)
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:203)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:134)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1001)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your crash report. This is because beta10 added back the old suggestions (so stable track users don't loose access to word suggestions) and these are buggy. beta11 and beta12 add some safety restrictions to prevent crashes in the first place, though this may mean that the word suggestions do not work for you. As I am going to address this well-known issue in 0.3.15, I will close this issue to keep the list of issues clean!
