### ISSUE TITLE
Crash: ConcurrentModificationException

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1206]
#### Short description
I have absolutely no idea what caused this. I think I closed&reopened the keyboard twice, and this is the result.

#### Environment information
- FlorisBoard Version: 0.3.13-beta12 (55)
- Device: Samsung SM-G960F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1627474450324.stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.<init>(StatisticalGlideTypingClassifier.kt:395)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.initializePruner(StatisticalGlideTypingClassifier.kt:149)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.setLayout(StatisticalGlideTypingClassifier.kt:117)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:61)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-48(TextKeyboardView.kt:1273)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.lambda$U7OJ4sHYwGnSHXM36JYIb8DgTag(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.-$$Lambda$TextKeyboardView$U7OJ4sHYwGnSHXM36JYIb8DgTag.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1628016773061.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onStartInputView(FlorisBoard.kt:388)
	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:3101)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.restartInput(InputMethodService.java:806)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:823)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:206)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1628190795153.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:613)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateSelection(InputMethodService.java:1030)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:108)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1628018018165.stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.<init>(StatisticalGlideTypingClassifier.kt:395)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.initializePruner(StatisticalGlideTypingClassifier.kt:149)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.setLayout(StatisticalGlideTypingClassifier.kt:117)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:61)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-48(TextKeyboardView.kt:1273)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.lambda$U7OJ4sHYwGnSHXM36JYIb8DgTag(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.-$$Lambda$TextKeyboardView$U7OJ4sHYwGnSHXM36JYIb8DgTag.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1627626690238.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onStartInputView(FlorisBoard.kt:388)
	at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:2872)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2754)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:947)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1627569327379.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:613)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateSelection(InputMethodService.java:1030)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:108)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1628013871533.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:613)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateSelection(InputMethodService.java:1030)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:108)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1627720949099.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onStartInputView(FlorisBoard.kt:388)
	at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:2872)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2754)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:947)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1630265436034.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 233504 free bytes and 228KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 85458944 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:141)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1627649238523.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:613)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateSelection(InputMethodService.java:1030)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:108)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

<details>
<summary>1628160416831.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:122)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onUpdateKeyboardState(TextKeyboardView.kt:217)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.onUpdateKeyboardState(SmartbarView.kt:235)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:255)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardStateKt.updateKeyboardState(KeyboardState.kt:260)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.dispatchCurrentStateToInputUi(FlorisBoard.kt:480)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onStartInputView(FlorisBoard.kt:388)
	at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:2872)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2754)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:947)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

I see that your stacktrace list contains a lot of NaN crashes, does this mean the NaN crashes are still not resolved or are they just still saved in the crash log directory?

As for the exception you mentioned, I think this exact crash has already been reported in #887. Possibly when reopening the keyboard twice very quickly I suspect two threads try to work with the same array and that never works out well.

**Comment by Glitchy-Tozier** [comment]
Unfortunately, so far, I was not able to reproduce this crash.

>I see that your stacktrace list contains a lot of NaN crashes, does this mean the NaN crashes are still not resolved or are they just still saved in the crash log directory?

I'm not sure what to do to find the answer to that question.

>As for the exception you mentioned, I think this exact crash has already been reported in #887. Possibly when reopening the keyboard twice very quickly I suspect two threads try to work with the same array and that never works out well.

Should we close it as a duplicate, then?

**Comment by patrickgold** [comment]
> I'm not sure what to do to find the answer to that question.

Does the keyboard randomly crash and when it does is the newest one a NaN crash? I remember about having fixed this issue and since then haven't heard anything new about this crash I thought it is fixed, but seeing it again here made me unsure if it is still a thing.

> Should we close it as a duplicate, then?

I guess so yeah.

**Comment by Glitchy-Tozier** [comment]
>Does the keyboard randomly crash and when it does is the newest one a NaN crash? I remember about having fixed this issue and since then haven't heard anything new about this crash I thought it is fixed, but seeing it again here made me unsure if it is still a thing.

It hasn't crashed ever since.

**Comment by patrickgold** [comment]
> It hasn't crashed ever since.

Ok thanks for clarifying!
