### ISSUE TITLE
Crashed editing link in Firefox

### ISSUE THREAD

**Issue by Theo-user** [florisboard/florisboard#1220]
#### Short description
I was just editing a url in firefox attempting to backspace.

#### Steps to reproduce
Open Firefox
Edit URL

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-A705FN
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = false
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1630590606689.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 906128 free bytes and 884KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 247988224 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:309)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.listAllSameOrderWords-5_OMaVU(temp_suggestion_code.kt:310)
	at dev.patrickgold.florisboard.ime.dictionary.FlorisLanguageModel.matchAllNgrams(temp_suggestion_code.kt:400)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions-CIUF35U(Flictionary.kt:306)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1010)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1630590606691.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 514784 free bytes and 502KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 242483200 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for 0.3.15, where I will re-implement them so this specific crash does not occur again.
