### ISSUE TITLE
copying selected text (crash)

### ISSUE THREAD

**Issue by a-gyaanapan** [florisboard/florisboard#1232]
#### Short description
i was trying to copy text using app and i tapped hardly on selected text. if this reoccurs again, i will provide more detail steps.
browser: mull 91.2.0

#### Steps to reproduce
1. Go to https://www.wikidata.org/wiki/Q5496658
2. Click on label
3. select text
4. try to tap copy icon on keyboard
5. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-J701F
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1630942631938.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>

**Comment by a-gyaanapan** [comment]
@patrickgold another crash with same website and same steps:

 #### Attached stacktrace files
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-J701F
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1630944964979.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>
