### ISSUE TITLE
Florisboard has crashed due to an unexpected error

### ISSUE THREAD

**Issue by tusharkantsahu** [florisboard/florisboard#1234]
#### Short description
It is completely random I have no idea what caused the problem. I think it is due to clipboard but I am not sure.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Realme RMX1827
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

**Comment by Glitchy-Tozier** [comment]
The next time this happens, could you post the copied text again (in a comment under this issue)?

Why?
Unfortunately the crash-log is missing in the original post, and hopefully next time it'll be added.

**Comment by Glitchy-Tozier** [comment]
For you guys, did this crash happen to occur right after powering on the device?

#### Environment information
- FlorisBoard Version: 0.3.13-beta12 (55)
- Device: Samsung SM-G960F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1630944455288.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 716584 free bytes and 699KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 52428800 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1631199065453.stacktrace</summary>

```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```
</details>

<details>
<summary>1631199065252.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.text.TextInputManager$setActiveKeyboard$1.invokeSuspend(TextInputManager.kt:408)@4f92c0a]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 146336 free bytes and 142KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 120324096 bytes)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode.removed(LockFreeLinkedList.kt:67)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode.removeOrNext(LockFreeLinkedList.kt:250)
	at kotlinx.coroutines.internal.LockFreeLinkedListNode.remove(LockFreeLinkedList.kt:241)
	at kotlinx.coroutines.JobSupport.removeNode$kotlinx_coroutines_core(JobSupport.kt:596)
	at kotlinx.coroutines.JobNode.dispose(JobSupport.kt:1350)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:308)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more

```
</details>

<details>
<summary>1631199063459.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 48 free bytes and 48B until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 120324096 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1631199064430.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 16 free bytes and 16B until OOM, target footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by tasmo** [comment]
Mine also crashed after boot and randomly in between.

---

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: ONEPLUS A3003
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1631205148879.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 16 free bytes and 16B until OOM, target footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:188)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by opusforlife2** [comment]
> For you guys, did this crash happen to occur right after powering on the device?

It did happen after a reboot, but not immediately. I could use it to type in my password and unlock the device. But when I tried to use it with an app, it showed up for a fraction of a second and then disappeared. Then it kept spamming the Android log with `Waiting for a blocking GC Alloc'. There were over a hundred of these, I think.

Eventually, it crashed multiple times, which were caught by Scoop. Interestingly, it has a GcWatcher timeout, which I only found in #681. @patrickgold Maybe new unique stacktraces could be added to the OP in #677 for easy referencing?

Here's the multiple crash logs from the app's Error Activity, which are the same ones as caught by Scoop:

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi MI 5
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1631340701700.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 24 free bytes and 24B until OOM, target footprint 268435456, growth limit 268435456
	at com.android.internal.os.HandlerCaller.<init>(HandlerCaller.java:55)
	at android.inputmethodservice.IInputMethodSessionWrapper.<init>(IInputMethodSessionWrapper.java:65)
	at android.inputmethodservice.IInputMethodWrapper$InputMethodSessionCallbackWrapper.sessionCreated(IInputMethodWrapper.java:114)
	at android.inputmethodservice.AbstractInputMethodService$AbstractInputMethodImpl.createSession(AbstractInputMethodService.java:68)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:206)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

<details>
<summary>1631340708780.stacktrace</summary>

```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)

```
</details>

<details>
<summary>1631340716786.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:90)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.setIndexInArray(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryTerminateWorker(CoroutineScheduler.kt:825)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:800)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1631340716791.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at sun.misc.Cleaner.create(Cleaner.java:133)
	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:242)
	at android.os.BinderProxy.getInstance(BinderProxy.java:413)
	at android.os.Parcel.nativeReadStrongBinder(Native Method)
	at android.os.Parcel.readStrongBinder(Parcel.java:2162)
	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:209)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```
</details>

**Comment by opusforlife2** [comment]
Oh, yeah. It didn't even occur to me that if glide suggestions weren't working, I might as well disable them. xD

@patrickgold Is it okay to have Floris set as the default keyboard when rebooting the device yet, or is there a chance of getting stuck still? I got this crash shortly after rebooting, and though I've disabled suggestions now, I'm wary of other post-reboot lockscreen bugs.

**Comment by Glitchy-Tozier** [comment]
1. You've got a very nice issue number! :)
2. This problem will be handled in #1268. It is known and will be fixed after the settings-rework. **For now, the solution is to disable word-suggistions.**
I will close this issue as a duplicate.
