### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by schorschfunke** [florisboard/florisboard#1241]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
It seems to crash when i switch the keyboard from florisboard to hackers keyboard automatically from tasker

#### Environment information
- FlorisBoard Version: 0.3.13-beta12 (55)
- Device: ONEPLUS A6013
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1627746067388.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@707aa00]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more

```
</details>

<details>
<summary>1627746067378.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$Companion.getInstance(FlorisContentProvider.kt:36)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:307)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1627746067392.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1628442109269.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:188)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:61)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-49(TextKeyboardView.kt:1273)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$8XtYPEEFRElXO-r_WSFYRRtpePI(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1627700147123.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:188)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:61)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-48(TextKeyboardView.kt:1273)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.lambda$U7OJ4sHYwGnSHXM36JYIb8DgTag(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.-$$Lambda$TextKeyboardView$U7OJ4sHYwGnSHXM36JYIb8DgTag.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1629648527201.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:188)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getFlorisboard(TextInputManager.kt:84)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getActiveState(TextInputManager.kt:110)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$evaluator$1.evaluateEnabled(TextInputManager.kt:163)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$internalComputingEvaluator$1.evaluateEnabled(TextKeyboardView.kt:82)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKey.compute(TextKey.kt:108)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:845)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:201)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$2$1$1.invokeSuspend(SmartbarView.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1627746067393.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1631213559188.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:64)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-48(TextKeyboardView.kt:1301)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$U7OJ4sHYwGnSHXM36JYIb8DgTag(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1628255609973.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:188)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonKeyView.<init>(EmoticonKeyView.kt:37)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonKeyView.<init>(EmoticonKeyView.kt:46)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonKeyView.<init>(EmoticonKeyView.kt:45)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonKeyboardView$buildLayout$2.invokeSuspend(EmoticonKeyboardView.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1627746067389.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@707aa00]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
		at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
		... 5 more
	Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
		at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
		at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
		at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
		at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
		at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		... 4 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 7 more

```
</details>

<details>
<summary>1631194524521.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getFlorisboard(TextInputManager.kt:84)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getActiveState(TextInputManager.kt:110)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$evaluator$1.evaluateEnabled(TextInputManager.kt:169)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$internalComputingEvaluator$1.evaluateEnabled(TextKeyboardView.kt:97)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKey.compute(TextKey.kt:113)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:858)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:216)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$2$1$1.invokeSuspend(SmartbarView.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1631194044690.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:64)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-48(TextKeyboardView.kt:1301)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$U7OJ4sHYwGnSHXM36JYIb8DgTag(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1627746067381.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.NullPointerException
		at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$Companion.getInstance(FlorisContentProvider.kt:36)
		at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:307)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 13 more

```
</details>

**Comment by patrickgold** [comment]
Handled in #1295
