### ISSUE TITLE
File picker activity not found (act=android.intent.action.PICK typ=image/*)

### ISSUE THREAD

**Issue by Vinod8085** [florisboard/florisboard#1249]
~~~ 1631460714133.stacktrace ~~~

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=123, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.biz2.nowfloats/com.framework.imagepicker.ImageActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* (has extras) }
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5014)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5055)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
	at com.framework.imagepicker.ImageActivity.startActivityFromGallery(ImageActivity.kt:81)
	at com.framework.imagepicker.ImageActivity.pickImage(ImageActivity.kt:52)
	at com.framework.imagepicker.ImageActivity.onRequestPermissionsResult(ImageActivity.kt:273)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8460)
	at android.app.Activity.dispatchActivityResult(Activity.java:8308)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5007)
	... 11 more

**Comment by Glitchy-Tozier** [comment]
Hi, what version of FlorisBoard did you use when this issue occured?

**Comment by Vinod8085** [comment]
> Hi, what version of FlorisBoard did you use when this issue occured?

Newest

**Comment by Glitchy-Tozier** [comment]
Please give proper information when reporting a bug.

1. What did you do that resulted in the crash?
2. What's the version-**number** of your app.

The version can be found in the settings, here:
![Screenshot_20210912-184707_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/132995940-384e64c8-3435-414a-a74d-01182d6f3cf4.jpg)

![Screenshot_20210912-184649_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/132995943-b351926b-5665-40ca-893d-7e21148ed773.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report!

> Newest

That's not a good version specifier, based on the track and install source this can differ quite a bit. Please specify the exact version (Glitchy provides excellent screenshots)

As to the bug itself: For whatever reason the default file picker of your system is not found. Are you on a default ROM or custom and do you have any file explorers installed?
