### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by davidak** [florisboard/florisboard#1253]
#### Short description
The new version from F-Droid always crashes.

#### Steps to reproduce
1. Start program
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Redmi Note 4
- Android: 8.1.0 (cn=O_MR1 sdk=27)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = false
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1631630872568.stacktrace</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.patrickgold.florisboard/dev.patrickgold.florisboard.settings.SettingsMainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.SubtypeManager$Companion.default(SubtypeManager.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity.getSubtypeManager(SettingsMainActivity.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity$SettingsFragment.onCreate(SettingsMainActivity.kt:216)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:472)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
	at android.app.Activity.performStart(Activity.java:7029)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more

```
</details>

**Comment by patrickgold** [comment]
Could you please try to clear the cache of FlorisBoard and then restart the device? (make sure that another keyboard is the default keyboard if you have pw unlocking!!). Does this fix this issue?

**Comment by davidak** [comment]
how to clear the cache?

**Comment by patrickgold** [comment]
Long press the FlorisBoard app icon in your launcher, then app info and clear cache. If your launcher does not have that options go to system options > applications > FlorisBoard and then clear cache.

**Comment by davidak** [comment]
It does not fix the issue.

If not every F-Droid uses has this issue, it might be related to the old Android version?

LineageOS 15.1 from 2019

#### Attached stacktrace files
<details>
<summary>1631810578400.stacktrace</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.patrickgold.florisboard/dev.patrickgold.florisboard.settings.SettingsMainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.SubtypeManager$Companion.default(SubtypeManager.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity.getSubtypeManager(SettingsMainActivity.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity$SettingsFragment.onCreate(SettingsMainActivity.kt:216)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:472)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
	at android.app.Activity.performStart(Activity.java:7029)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more

```
</details>

**Comment by patrickgold** [comment]
Ok if this does not fix your issue then something only on your device goes completely wrong while initializing the FlorisBoard Application object, and the subtype manager either is not initialized at all or set to `null` somehow. This is very difficult to pin down to what exactly is causing this though, so atm I don't really know how I can fix this issue.

Does FlorisBoard only crash if you try to open the settings UI or also when you only activate the keyboard and tap into a text field?
