### ISSUE TITLE
Switched from preinstalled keyboard to florisboard

### ISSUE THREAD

**Issue by Aman9das** [florisboard/florisboard#1255]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
0. Change system font.
Oem switches to preinstalled keyboard automatically
1. Go to 'any text field (lawnchair search)'
2. Long press> input method
3. Click florisboard beta
4. Wait a bit
5. See error

#### Environment information
- FlorisBoard Version: 0.3.14-beta01 (57)
- Device: Vivo 1727
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1631686672734.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$loadLayoutAsync$1.invokeSuspend(LayoutManager.kt:85)@5647675]){Completed}@b5c460a. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:108)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 4 more

```
</details>

**Comment by patrickgold** [comment]
Could you please try to clear the cache of FlorisBoard and then restart your device? I've heard from some cases where the code cache didn't clean properly after an upgrade which caused bugs which aren't there when doing a fresh install. Thanks in advance!

**Comment by Aman9das** [comment]
Umm.. i did just that, and here is the error..
Clear cache
Reboot
There was a notification when the phone opened..

#### Environment information
- FlorisBoard Version: 0.3.14-beta01 (57)
- Device: Vivo 1727
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1631753623272.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$loadLayoutAsync$1.invokeSuspend(LayoutManager.kt:79)@7efec33]){Completed}@d914bf0. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:108)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:233)
	... 4 more

```
</details>

**Comment by Aman9das** [comment]
More info: this time i was at foxy droid trying to search something but the keyboard wouldn't open

#### Environment information
- FlorisBoard Version: 0.3.14-beta01 (57)
- Device: Vivo 1727
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = false
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1631791809948.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$loadLayoutAsync$1.invokeSuspend(LayoutManager.kt:79)@f0e899f]){Completed}@43a2eb5. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:108)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:233)
	... 4 more

```
</details>

<details>
<summary>1631840568034.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 16 free bytes and 16B until OOM, max allowed footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1019)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Hmm based on the first stacktrace this is a bug within the Kotlin coroutines, the second crash is the classic OOM crash which happens when suggestions are enabled. I am not 100% sure what to do for the Kotlin co-routine crash, for the OOM crash I suggest disabling word suggestions if the OOM crashes occur often.

**Comment by Aman9das** [comment]
Thanks, closing.. if and when telex is added, do create a guide about it :)

Thank you for the amazing keyboard!
