### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Charunoptic** [florisboard/florisboard#1286]
~~~ 1632553163866.stacktrace ~~~

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.biz2.nowfloats/com.nowfloats.Analytics_Screen.VmnCallCardsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.framework.pref.TokenResult.getToken()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.framework.pref.TokenResult.getToken()' on a null object reference
	at com.nowfloats.util.Utils.getAuthToken(Utils.java:461)
	at com.nowfloats.util.Utils$2.intercept(Utils.java:498)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:273)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy40.trackerCalls(Unknown Source)
	at com.nowfloats.Analytics_Screen.VmnCallCardsActivity.getCalls(VmnCallCardsActivity.java:325)
	at com.nowfloats.Analytics_Screen.VmnCallCardsActivity.onCreate(VmnCallCardsActivity.java:151)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	... 11 more

**Comment by patrickgold** [comment]
Thanks for your issue. Could you please fill out the bug report form, this stack trace alone does not help at all.

**Comment by patrickgold** [comment]
Closing as this crash log does not provide sufficient information. Will reopen it if I have more info on what happened and if the bug report is correctly filled out.
