### ISSUE TITLE
My FlorisBoard Crashed

### ISSUE THREAD

**Issue by SelQuarter** [florisboard/florisboard#1300]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Mi Note 10 Lite
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = false
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1632888717293.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.SubtypeManager$Companion.default(SubtypeManager.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity.getSubtypeManager(SettingsMainActivity.kt:56)
	at dev.patrickgold.florisboard.settings.SettingsMainActivity$SettingsFragment.onCreate(SettingsMainActivity.kt:216)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:472)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
	at android.app.Activity.performStart(Activity.java:8140)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3527)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>

**Comment by rockerritesh** [comment]
Same on Redmi 8!!
``` 
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Redmi 8
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1632982883951.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: start > length()
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:853)
	at java.lang.StringBuilder.replace(StringBuilder.java:263)
	at dev.patrickgold.florisboard.ime.core.EditorInstance$CachedInput.updateText(EditorInstance.kt:945)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.updateText(EditorInstance.kt:141)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateExtractedText(FlorisBoard.kt:349)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateExtractedText(InputMethodService.java:722)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:98)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by Glitchy-Tozier** [comment]
@SelQuarter Could you please complete the bug report by filling in the first two points of the issue-template?

@rockerritesh As far as I can tell (I'm looking at the first line of the stacktrace), your crash is something completely different. It's still a new crash I think, meaning that you could open a new issue and mark this comment as off-topic.
