### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: start > length()

### ISSUE THREAD

**Issue by rockerritesh** [florisboard/florisboard#1301]
#### Short description
Crashed on my Redmi 8
``` 
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Redmi 8
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1632982883951.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: start > length()
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:853)
	at java.lang.StringBuilder.replace(StringBuilder.java:263)
	at dev.patrickgold.florisboard.ime.core.EditorInstance$CachedInput.updateText(EditorInstance.kt:945)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.updateText(EditorInstance.kt:141)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateExtractedText(FlorisBoard.kt:349)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateExtractedText(InputMethodService.java:722)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:98)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by Glitchy-Tozier** [comment]
Thank you for taking the time to post this issue!

Are you able to replicate the crash? If yes, how?

**Comment by rockerritesh** [comment]
No, I think this occurs when i was trying  to past something!!

**Comment by Glitchy-Tozier** [comment]
Just for clarification, did you mean to type "paste", "undo" or something else?

**Comment by rockerritesh** [comment]
Paste!!
