### ISSUE TITLE
Crash when switching keyboard

### ISSUE THREAD

**Issue by schorschfunke** [florisboard/florisboard#1392]
#### Short description
It sometimes crashed when i switch the keyboard

#### Steps to reproduce
Switch keyboard

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Device: ONEPLUS A6013
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1635707881831.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:181)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getFlorisboard(TextInputManager.kt:85)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getActiveState(TextInputManager.kt:112)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$evaluator$1.evaluateEnabled(TextInputManager.kt:167)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$internalComputingEvaluator$1.evaluateEnabled(TextKeyboardView.kt:97)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKey.compute(TextKey.kt:113)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:216)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$3$1$1.invokeSuspend(SmartbarView.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1635721880314.stacktrace</summary>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter jsonConfig
	at dev.patrickgold.florisboard.res.AssetManager.loadJsonAsset-0E7RQCE(Unknown Source:12)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.indexInternalModule(ExtensionManager.kt:184)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.refresh(ExtensionManager.kt:145)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.access$refresh(ExtensionManager.kt:103)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex$1.invokeSuspend(ExtensionManager.kt:139)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1636443467191.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:181)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:69)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-47(TextKeyboardView.kt:1296)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$YFHtd2enSAhbYy8LsiVlmx3aUOs(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1635791830255.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:181)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getFlorisboard(TextInputManager.kt:85)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getActiveState(TextInputManager.kt:112)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$evaluator$1.evaluateEnabled(TextInputManager.kt:167)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$internalComputingEvaluator$1.evaluateEnabled(TextKeyboardView.kt:97)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKey.compute(TextKey.kt:113)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.computeKeyboard(TextKeyboardView.kt:853)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:216)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$3$1$1.invokeSuspend(SmartbarView.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1635720867978.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:181)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:69)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-47(TextKeyboardView.kt:1296)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$YFHtd2enSAhbYy8LsiVlmx3aUOs(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

<details>
<summary>1635791808844.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:181)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:69)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.initGlideClassifier$lambda-47(TextKeyboardView.kt:1296)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.$r8$lambda$YFHtd2enSAhbYy8LsiVlmx3aUOs(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

**Comment by schorschfunke** [comment]
With beta06 it seems OK now! Thanks for your hard work

**Comment by patrickgold** [comment]
Great to hear, thanks for the feedback!
