### ISSUE TITLE
Add support for Chat-Bubbles

### ISSUE THREAD

**Issue by lm41** [florisboard/florisboard#1399]
#### Short description
The Keyboard crashes when using the android chatbubbles.

#### Steps to reproduce
1. Get a message.
2. Open the Chat-bubble

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Install-source: F-Droid
- Device: Motorola moto g(30)
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1637242570430.stacktrace</summary>

```
android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@b467268 -- the specified display can not be found
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1149)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:441)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.app.Dialog.show(Dialog.java:340)
	at android.inputmethodservice.SoftInputWindow.show(SoftInputWindow.java:270)
	at android.inputmethodservice.SoftInputWindow.setToken(SoftInputWindow.java:104)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.attachToken(InputMethodService.java:769)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.initializeInternal(InputMethodService.java:739)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:173)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>

<details>
<summary>1637242572531.stacktrace</summary>

```
android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@6cbb232 -- the specified display can not be found
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1149)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:441)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.app.Dialog.show(Dialog.java:340)
	at android.inputmethodservice.SoftInputWindow.show(SoftInputWindow.java:270)
	at android.inputmethodservice.SoftInputWindow.setToken(SoftInputWindow.java:104)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.attachToken(InputMethodService.java:769)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.initializeInternal(InputMethodService.java:739)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:173)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

FlorisBoard does currently not support chat bubbles at all, so this is probably why it crashes for them. I may add support for them, although atm the preference / keyboard UI rework has a lot higher priority than this feature, I hope you can understand. Will mark this as a proposal which may gets implemented.

**Comment by BobIsMyManager** [comment]
Works fine for me
Device: redmi note 9 pro
Android version: 11
Florisboard version: 0.3.14-beta0.5
Installation source: f-droid

**Comment by BobIsMyManager** [comment]
![Screenshot_2021-11-27-22-42-11-394_org telegram messenger web](https://user-images.githubusercontent.com/70704875/143722451-8cefcdf5-2cb7-4f40-944d-5a57db55f95b.jpg)

**Comment by patrickgold** [comment]
If it works then its great, it means for your device no specific implementation is needed. Still it seems that chat bubbles don't work flawlessly across all devices, so I need to specifically work on that someday in the future.
