### ISSUE TITLE
Sudden crash in Chrome

### ISSUE THREAD

**Issue by DanielProg39** [florisboard/florisboard#1400]
In Chrome I tapped on url bar and saw a message from FlorisBoard, tapped on it, this crash log appeared:

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi M2007J3SY
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = false
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1637303994567.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: start > length()
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:853)
	at java.lang.StringBuilder.replace(StringBuilder.java:263)
	at dev.patrickgold.florisboard.ime.core.EditorInstance$CachedInput.updateText(EditorInstance.kt:945)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.updateText(EditorInstance.kt:141)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateExtractedText(FlorisBoard.kt:349)
	at android.inputmethodservice.InputMethodService$InputMethodSessionImpl.updateExtractedText(InputMethodService.java:919)
	at android.inputmethodservice.IInputMethodSessionWrapper.executeMessage(IInputMethodSessionWrapper.java:99)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report, but it already exists in the issue list (although not yet triaged/worked on it). Will close this issue thus.

Duplicate #1301
