### ISSUE TITLE
Crash when bringing up florisboard after restart. (outofmemory error)

### ISSUE THREAD

**Issue by TheFunnyBrain** [florisboard/florisboard#1438]
Crash when first bringing up the keyboard after an unexpected reboot

#### Short description
Describe what you were doing that could've led to the crash.

I had the crash when opening the address bar in firefox. The unexpected reboot might have been related.

#### Steps to reproduce
1. Go to '…' 
2. Click on '…'
3. Scroll down to '…'
4. See crash

1) Open firefox app (possibly any app with text input)
2) Press the address bar

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-G973F
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1639379213499.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 254424 free bytes and 248KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 113246208 bytes)
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:245)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:134)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1638309531888.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/dev.patrickgold.florisboard/databases/pins': Directory /data/user/0/dev.patrickgold.florisboard/databases doesn't exist
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
		at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
		at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
		at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
		at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:980)
		at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:444)
		at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
		at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
		at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
		at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
		at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
		at dev.patrickgold.florisboard.ime.clip.provider.PinnedClipboardItemDao_Impl.getAll(PinnedClipboardItemDao_Impl.java:119)
		at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:304)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
	Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
		at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
		... 21 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 13 more

```
</details>

<details>
<summary>1638474835630.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/dev.patrickgold.florisboard/databases/pins': Directory /data/user/0/dev.patrickgold.florisboard/databases doesn't exist
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
		at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
		at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
		at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
		at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:980)
		at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:444)
		at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
		at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
		at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
		at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
		at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
		at dev.patrickgold.florisboard.ime.clip.provider.PinnedClipboardItemDao_Impl.getAll(PinnedClipboardItemDao_Impl.java:119)
		at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:304)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
	Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
		at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
		... 21 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 13 more

```
</details>

<details>
<summary>1638309531890.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@2939c2c]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
		at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
		... 5 more
	Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
		at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
		at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
		at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
		at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
		at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		... 4 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 7 more

```
</details>

<details>
<summary>1638309531891.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1638474835629.stacktrace</summary>

```
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/dev.patrickgold.florisboard/databases/pins': Directory /data/user/0/dev.patrickgold.florisboard/databases doesn't exist
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:980)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:444)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at dev.patrickgold.florisboard.ime.clip.provider.PinnedClipboardItemDao_Impl.getAll(PinnedClipboardItemDao_Impl.java:119)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
	... 21 more

```
</details>

<details>
<summary>1638309531886.stacktrace</summary>

```
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/dev.patrickgold.florisboard/databases/pins': Directory /data/user/0/dev.patrickgold.florisboard/databases doesn't exist
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:980)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:444)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at dev.patrickgold.florisboard.ime.clip.provider.PinnedClipboardItemDao_Impl.getAll(PinnedClipboardItemDao_Impl.java:119)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
	... 21 more

```
</details>

<details>
<summary>1638474835632.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1638474835631.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@a6c24ab]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:530)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more

```
</details>

**Comment by Glitchy-Tozier** [comment]
Thanks for your bug report!

The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.
