### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by velteyn** [florisboard/florisboard#1443]
Hello,
the app suggests me to report this crash occurred right now. Dont' know exactly how to reproduce.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi M2010J19SY
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1639474655327.stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property fileUriDao has not been initialized
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$insert$1$1.invokeSuspend(FlorisContentProvider.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! This exact issue cannot occur on the latest beta anymore, as the corresponding source code has changed. Will close this issue thus.
