### ISSUE TITLE
Crashed while coping a image 

### ISSUE THREAD

**Issue by adivish** [florisboard/florisboard#1462]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Realme RMX2151
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1640011209982.stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property fileUriDao has not been initialized
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$insert$1$1.invokeSuspend(FlorisContentProvider.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
This particular crash is not possible anymore on the latest beta (although copying images is still quite the crash experience). Closing this issue thus to keep the list of issues a bit more clean.
