### ISSUE TITLE
crashed 

### ISSUE THREAD

**Issue by Bharadwaj1234567890** [florisboard/florisboard#1464]
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: HMD Global Nokia 8.1
- Android: 11 (cn=R sdk=30)

#### Features enabled
kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true

#### Attached stacktrace files
<details>
<summary>1640173954652.stacktrace</summary>

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:245)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:134)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Thanks for your bug report!

The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.

**Comment by Bharadwaj1234567890** [comment]
Thank you

**Comment by Glitchy-Tozier** [comment]
(I closed the issue due to it being a duplicate of #1268)
