### ISSUE TITLE
FB beta08 crashes on launching the app and switching keyboard to FB

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1493]
I can't enter the new 0.3.14 beta08. It crashes both on app start and on switching keyboard to beta08. Android 6.0.1 

The Scoop app caught the following error:

```
FATAL EXCEPTION: main
Process: dev.patrickgold.florisboard.beta, PID: 10159
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;
	at dev.patrickgold.florisboard.app.prefs.AppPrefs$Theme.<init>(AppPrefs.kt:561)
	at dev.patrickgold.florisboard.app.prefs.AppPrefs.<init>(AppPrefs.kt:534)
	at dev.patrickgold.florisboard.app.prefs.AppPrefsKt$florisPreferenceModel$1.invoke(AppPrefs.kt:40)
	at dev.patrickgold.florisboard.app.prefs.AppPrefsKt$florisPreferenceModel$1.invoke(AppPrefs.kt:40)
	at dev.patrickgold.jetpref.datastore.JetPrefManager.getOrCreatePreferenceModel(JetPrefManager.kt:99)
	at dev.patrickgold.jetpref.datastore.JetPrefManagerKt.preferenceModel(JetPrefManager.kt:117)
	at dev.patrickgold.florisboard.app.prefs.AppPrefsKt.florisPreferenceModel(AppPrefs.kt:40)
	at dev.patrickgold.florisboard.FlorisApplication.<init>(FlorisApplication.kt:66)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1019)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalTime" on path: DexPathList[[zip file "/data/app/dev.patrickgold.florisboard.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/dev.patrickgold.florisboard.beta-1/lib/arm, /data/app/dev.patrickgold.florisboard.beta-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 21 more
	Suppressed: java.lang.ClassNotFoundException: java.time.LocalTime
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 22 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by patrickgold** [comment]
I am aware of this issue, it is caused by my preference library which pulls in Java's LocalTime, which is not supported on your Android version. Beta09 will fix this.
