### ISSUE TITLE
Crash on almost Xiaomi device

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1509]
#### Environment information- 
- FlorisBoard Version: 0.3.13 (56) 
- Device: Xiaomi M1908C3JGG
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = false
suggestions_next_word = false
glide = false
clipboard_internal = true
clipboard_history = true
```
#### Attached stacktrace files
<details>
<summary>1642333710376.stacktrace</summary>

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView$onTouchDownInternal$4.invokeSuspend(TextKeyboardView.kt:437)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:484)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

The class this crash originates from does not exist anymore in the latest beta release 0.3.14-beta09, so I will close this issue.
