### ISSUE TITLE
NullPointerEx in FlorisContentProvider

### ISSUE THREAD

**Issue by Luensche** [florisboard/florisboard#1512]
#### Environment information
- FlorisBoard Version: 0.3.14-beta08 (64)
- Device: LeMobile X52X
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1627586409108.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$Companion.getInstance(FlorisContentProvider.kt:36)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:307)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1627586409159.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.NullPointerException
		at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider$Companion.getInstance(FlorisContentProvider.kt:36)
		at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt:307)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 13 more

```
</details>

<details>
<summary>1627586409202.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@3af394]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more

```
</details>

<details>
<summary>1627586409209.stacktrace</summary>

```
java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager$initialize$2.invokeSuspend(FlorisClipboardManager.kt)@3af394]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
		at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
		... 5 more
	Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
		at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
		at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
		at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
		at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
		at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
		at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
		at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		... 4 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
	... 7 more

```
</details>

<details>
<summary>1627586409244.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:33)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1627586409256.stacktrace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:458)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:443)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.getLastCrashTimestamp(CrashUtility.kt:213)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$getLastCrashTimestamp(CrashUtility.kt:46)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:389)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1639250186301.stacktrace</summary>

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at dev.patrickgold.florisboard.ime.keyboard.LayoutManager.mergeLayouts(LayoutManager.kt:241)
	at dev.patrickgold.florisboard.ime.keyboard.LayoutManager.access$mergeLayouts(LayoutManager.kt:65)
	at dev.patrickgold.florisboard.ime.keyboard.LayoutManager$mergeLayouts$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1642573860251.stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.<init>(StatisticalGlideTypingClassifier.kt:403)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.initializePruner(StatisticalGlideTypingClassifier.kt:149)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.setLayout(StatisticalGlideTypingClassifier.kt:117)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:67)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.TextKeyboardLayout(TextKeyboardLayout.kt:123)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt.TextInputLayout(TextInputLayout.kt:46)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt$TextInputLayout$2.invoke(Unknown Source:8)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt$TextInputLayout$2.invoke(Unknown Source:8)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Comment by surajeet310** [comment]
Can I work on this bug?

**Comment by patrickgold** [comment]
If you want to, yes! Be aware that the image content provider this crash originates from has not been adapted for the new clipboard manager, so that is also a possible reason why this crash occurs.

**Comment by surajeet310** [comment]
Thanks! 
Can you just point me to where should I begin?

**Comment by patrickgold** [comment]
I just discovered that the crash itself is not reproducible anymore, but at the cost that content provider for images does not work at all atm. So if you want to work on fixing the content provider so the clipboard manager can work with images again, I am happily accepting help in that regard. If you just wanted to fix this crash (which is currently impossible in the latest beta) and don't want to work on the provider, that's also ok with me.

Below just some useful hints for the provider if you decide to work on that:

The general area of clipboard related stuff: https://github.com/florisboard/florisboard/tree/master/app/src/main/java/dev/patrickgold/florisboard/ime/clipboard

This is the provider, which is the main subject to fix for images to work again: https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/provider/FlorisContentProvider.kt

**Comment by patrickgold** [comment]
This issue has several other crash logs attached too, which are a lot more concern to me, as these are more new. @Luensche does this crash: `java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked` occur often and when does it happen for you?

**Comment by Luensche** [comment]
I didn't remember any crashes in recent times. I thought about consequential errors, so one ex is leading to an illegal state and the other exceptions are following because of this. Not sure, if this can happen at this point.

I can't reproduce this error, btw.

**Comment by surajeet310** [comment]
@patrickgold Can you point me to bugs which are well suited for beginner ?
