### ISSUE TITLE
Tapping copy icon twice crashed the keyboard

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1576]
#### Short description
I accidentally tapped on copy button on Florisboard and it crashed.

#### Steps to reproduce
Couldn't replicate it.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-A307FN
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1644911207200.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>

**Comment by vis2021t** [comment]
Same happened to me lol

**Comment by patrickgold** [comment]
Thanks for your bug report! Can fully reproduce this bug with Glitchy's method. Will investigate into this further when I am fixing some other editor instance related crashes too.

**Comment by suhan-paradkar** [comment]
Looks like a classic NPE.....
Guess it can be solved by using an if loop to exclude passing null parameter [here](https://github.com/florisboard/florisboard/blob/8674a04a5cdc7200590e8877afeee3fbf81d99c6/app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt#L947)....
