### ISSUE TITLE
Memory leak(?) Once in a while

### ISSUE THREAD

**Issue by H3n-beep** [florisboard/florisboard#1621]
#### Short description
Some times the keyboard starts lagging and when measured its using ~1.3 gigabytes of ram
#### Steps to reproduce
No idea 

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Fdroid
- Device: Xiaomi poco x3
- Android: miui global 12.5.5

**Comment by tsiflimagas** [comment]
The version you're using is 11 months old. Also, this problem is well known when using word suggestions. A new word suggestions mechanism will be implemented in version 0.3.15, which will fix memory and other issues. Closing thus.

**Comment by H3n-beep** [comment]
But i've turned off word suggestions, and when will the fdroid build get updated?

**Comment by H3n-beep** [comment]
I found the log 
~~~ 1626631921933.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-07-18:602222046
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1696)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:303)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	... 3 more
~~~ 1628601506631.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-08-10:320224649
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1696)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:303)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	... 3 more
~~~ 1629559487569.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-08-21:44763909
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1696)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:303)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	... 3 more
~~~ 1629559501676.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-08-21:866679781
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1696)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:303)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	... 3 more
~~~ 1633367632371.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-10-04:45436292
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1996)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1696)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:303)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	... 3 more
~~~ 1646680460766.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:65)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView$initGestureClassifier$1.run(KeyboardView.kt:147)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
