### ISSUE TITLE
Copied images not getting displayed in clipboard history

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1642]
#### Short description
When copying an image from the web or anywhere, it doesn't get displayed in clipboard history nor in primary clip on the smartbar. Instead, it just shows as an empty item.
I should note, though, that the image can be copied just fine.
 
#### Steps to reproduce
1. Go to a browser
2. Copy an image
3. Open clipboard history
4. See the empty item 

#### Environment information
- FlorisBoard Version: 0.3.14-rc01
- Install Source: GitHub
- Device: Xiaomi Redmi note 8
- Android: 12, Custom rom

**Comment by GoRaN909** [comment]
Yes you right the copied images doesn't show up in the older 3.10 stable or betas versions.

**Comment by patrickgold** [comment]
Above PR contains a new implementation for the clipboard image logic. I tested it on my device with Bromite, Element and Signal, which all worked fine.

If possible, could both of you please try out the debug APK and give me feedback if the clipboard image support works or if not which apps refuse to work. This would be incredible so I can make a final touch to it tomorrow before doing the rc02 release. Thanks in advance!

**Comment by GoRaN909** [comment]
> If possible, could both of you please try out the debug APK and give me feedback if the clipboard image support works or if not which apps refuse to work.

Hi I just tested the debug apk and i can confirm that when you copy an image from any source it copies to floris clipboard history and shows without ant problems, but I tried with screenshot when i take a device screenshot and click on Share button to copy screenshot to clipboard the FlorisBoard just get a crash. 

This is the crash report:

#### Environment information
- FlorisBoard Version: 0.3.14-debug (71)
- Device: Samsung SM-G781B
- Android: 12 (cn=S sdk=31)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = false
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647567818235.stacktrace</summary>

```
android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _display_name FROM ClipboardImageTable WHERE (id=42) ORDER BY _data
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1226)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardItem$Companion.fromClipData(ClipboardDatabase.kt:100)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardManager.onPrimaryClipChanged(ClipboardManager.kt:170)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:319)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:85)
	at android.content.ClipboardManager$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

```
</details>

**Comment by tsiflimagas** [comment]
Hey, nice job! I confirm images are displayed in clipboard history now. There are just a few things to mention. When the primary clip is an image, it's not displayed on the smartbar, when suggestions are on (maybe this should be left for the new suggestions mechanism?). Also, it seems like FlorisBoard supplements the images with empty space to adjust the item's size. I wonder if it's possible to change that and maybe display them a bit cropped in order for them fit in the history (just guessing, I don't really know what can be done there). Here's a screenshot of what I'm referring to
 
![Screenshot_20220318-180947_FlorisBoard Beta](https://user-images.githubusercontent.com/45879751/159040305-53a5557e-7847-4580-8b5d-8301c23d4e37.png)

Btw, it seems like my system doesn't provide clipboard as an option to copy screenshots to, so I can't try what @GoRaN909 mentioned.
Lastly, this crash now occurs when deleting text items, not for images though.

#### Environment information
- FlorisBoard Version: 0.3.14-debug (71)
- Device: Xiaomi Redmi Note 8
- Android: 12 (cn=S sdk=31)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647619887954.stacktrace</summary>

```
java.lang.IllegalArgumentException: Unknown URL null
	at android.content.ContentResolver.delete(ContentResolver.java:2334)
	at android.content.ContentResolver.delete(ContentResolver.java:2304)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardManager$deleteClip$1.invokeSuspend(ClipboardManager.kt:270)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks Kostas for testing out the clipboard image feature, really appreciate it!

> When the primary clip is an image, it's not displayed on the smartbar, when suggestions are on (maybe this should be left for the new suggestions mechanism?).

Will leave that for 0.4.0, because I need to determine if the target app even supports pasting images and then I need to adjust the clip suggestion view, which is intertwined with suggestions.

> Also, it seems like FlorisBoard supplements the images with empty space to adjust the item's size. I wonder if it's possible to change that and maybe display them a bit cropped in order for them fit in the history (just guessing, I don't really know what can be done there).

In this particular case it is as easy as changing `contentScaling` from `Fit` to `FillWidth` :smile: It just does look gross for images that are very low res (<100px), but yeah don't really know how to fix that.

> Btw, it seems like my system doesn't provide clipboard as an option to copy screenshots to, so I can't try what mentioned.

Same for me. Now that I know Samsung has this feature I want this on my device too... Seems like this is an instance where Samsung is better that OnePlus...

> Lastly, this crash now occurs when deleting text items, not for images though.

This is correct. Text clips have set the uri to null, but not to `null` but `"null"` (seems to be a database thing??). Thus my neat null check was tricked and I tried to delete an uri just with the null string :smile: Now I surrounded the whole deletion in a try block, so this cannot happen anymore.

Could you just test out the new debug apk on your device to confirm everything works as intended? Thanks!

**Comment by tsiflimagas** [comment]
Yes, everything's good now. I can't see any bug, and images look great like that. Nice job!

**Comment by GoRaN909** [comment]
Yeah it's very good now everything works great Thank you so much I love this amazing keyboard God bless you dear @patrickgold  and as @tsiflimagas said the only thing need fix clipboard suggestions on smartbar is an empty copied images not showing on smartbar that's not a problem for now i hope you fix that when word suggestions has been implemented again.

![Screenshot_20220318-202930_Samsung Notes](https://user-images.githubusercontent.com/3160786/159054430-55976377-c472-4582-92f1-9c0f86172d80.png)


![Screenshot_20220318-202958_Samsung Notes](https://user-images.githubusercontent.com/3160786/159054811-a6f60cbc-15c2-41ca-b29d-d90cb4effac3.png)

**Comment by patrickgold** [comment]
Thanks both of you for testing out the changes and for your feedback! Will merge the changes now in, and will then make the 0.3.14-rc02 release.
