### ISSUE TITLE
Crash after trying to copy quickly from in-site input field

### ISSUE THREAD

**Issue by JVS-XII** [florisboard/florisboard#1647]
#### Short description
I tried to copy the link directly to the Floris clipboard from the input field on site (Chromium).
#### Steps to reproduce
1. open link on https://www.proxysite.com
2. insert the cursor in the adress field on site
3. press "select all"
_the site took the last click as pressing the button next to the input field and long press-menu is opens_
4. trying to tap "copy" on smartboard ahead of trigger
_after success app are reports about failure to work_

**Note:** at attempt to also quickly "copy all"
from some other input fields any obstacles don't have. This is not a performance issue and is associated with this point with long press-menu.

#### Environment information
- FlorisBoard Version: 0.3.14-rc01 (71)
- Device: HUAWEI PRA-LA1
- Android: 8.0.0 (cn=O sdk=26)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1647355538192.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:954)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:651)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.onInputKeyUp(KeyboardManager.kt:592)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
</details>

**Comment by patrickgold** [comment]
Above pull requests addresses this crash (adding a toast message when it fails instead of simply silently ignoring that something is wrong), but it was also previously fixed by PR #1637 already. Will be released in 0.3.14-rc02 soon.
