### ISSUE TITLE
java.lang.OutOfMemoryError Crash Report

### ISSUE THREAD

**Issue by s4z3n** [florisboard/florisboard#1652]
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Google Pixel 5
- Android: 12 (cn=S_V2 sdk=32)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = false
suggestions_next_word = false
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1647467743785.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 991648 free bytes and 968KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:188)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by GoRaN909** [comment]
This is known bug for more info look at #677

**Comment by Glitchy-Tozier** [comment]
As @GoRaN909 pointed out, this issue is well known. Check out #1268.

The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.
