### ISSUE TITLE
Clipboard isn't working anymore

### ISSUE THREAD

**Issue by z0xrv** [florisboard/florisboard#1660]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Simply click on the clipboard button to view history
2. See crash

#### Environment information
- FlorisBoard Version: 0.3.14-rc02 (72)
- Device: Condor PGN528
- Android: 7.0 (cn=N sdk=24)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = false
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647641977037.stacktrace</summary>

```
java.lang.NullPointerException: decodeFile(file.absolutePath) must not be null
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:223)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:218)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:99)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:52)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:49)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:200)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.access$ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:1)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:287)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:285)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.app.ui.components.FlorisStaggeredVerticalGridKt.FlorisStaggeredVerticalGrid-uFdPcIQ(FlorisStaggeredVerticalGrid.kt:112)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$HistoryMainView(ClipboardInputLayout.kt:285)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout(ClipboardInputLayout.kt:515)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:511)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:502)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:502)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:475)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:99)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:52)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:49)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:466)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:465)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService.ImeUi(FlorisImeService.kt:465)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:115)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(FlorisImeService.kt)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(FlorisImeService.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:641)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>

**Comment by GoRaN909** [comment]
Yeah you right me too just got same crash when try to Enable Clipboard History that's so strange I tested the debug apk file before release 3.14-rc02 everything works great but idk what's the problem with the latest beta 0.3.14-rc02 (72) version why clipboard is not working! 

#### Environment information

- FlorisBoard Version: 0.3.14-rc02 (72)
- Device: Samsung SM-G781B
- Android: 12 (cn=S sdk=31)

#### Features enabled

```ktsmartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = false
glide = false
clipboard_internal = true
clipboard_history = true
```
#### Attached stacktrace files
<details>
<summary>1647652956535.stacktrace</summary>

```
java.lang.NullPointerException: decodeFile(file.absolutePath) must not be null	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:210)	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:205)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:82)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:35)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:32) 	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:187)	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.access$ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:1)	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:274)	
at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:272)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at dev.patrickgold.florisboard.app.ui.components.FlorisStaggeredVerticalGridKt.FlorisStaggeredVerticalGrid-uFdPcIQ(FlorisStaggeredVerticalGrid.kt:95)	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$HistoryMainView(ClipboardInputLayout.kt:272)	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout(ClipboardInputLayout.kt:503)	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:498)	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:489)	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:489)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:460)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:82)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:35)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)	
at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:32)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:451)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:450)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)	
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)	
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)	
at dev.patrickgold.florisboard.FlorisImeService.ImeUi(FlorisImeService.kt:450)	
at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:99)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(Unknown Source:8)	
at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(Unknown Source:10)	
at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)	
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)	
at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)	
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)	
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)	
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)	
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)	
at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)	
at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)	
at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)	
at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)	
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)	
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)	
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)	
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)	
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)	
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)	
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1061)	
at android.view.Choreographer.doCallbacks(Choreographer.java:845)	
at android.view.Choreographer.doFrame(Choreographer.java:775)	
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)	
at android.os.Handler.handleCallback(Handler.java:938)	
at android.os.Handler.dispatchMessage(Handler.java:99)	
at android.os.Looper.loopOnce(Looper.java:226)	
at android.os.Looper.loop(Looper.java:313)	
at android.app.ActivityThread.main(ActivityThread.java:8641)	
at java.lang.reflect.Method.invoke(Native Method)	
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```
</details>

**Comment by Glitchy-Tozier** [comment]
@patrickgold seems important.

**Comment by patrickgold** [comment]
Thanks for your crash reports!

I cannot directly reproduce it atm but based on the code it is possible that the decoding process fails (file not found error) and thus the crash occurs. Am currently working on a possible fix.

**Comment by patrickgold** [comment]
So I was able to reproduce the issue if I purposely deleted the image data file. I suspect that you had old images saved in the clipboard history, and as the location of the files has moved the image data file was lost too.

If you want to test out the fix you'd probably have to wait for 0.3.14-rc03 later today or tomorrow. If you have root access you could test it out with the debug too, but I think this is too much of a hassle. Anyways, thanks for reporting!

**Comment by z0xrv** [comment]
I still get the error when i try to clear the clipboard
#### Environment information
- FlorisBoard Version: 0.3.14-rc03 (73)
- Device: Condor PGN528
- Android: 7.0 (cn=N sdk=24)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647707809107.stacktrace</summary>

```
java.lang.NullPointerException: decodeFile(file.absolutePath) must not be null
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:223)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$ClipItemView$4.invoke(ClipboardInputLayout.kt:218)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:99)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:52)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:49)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:200)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.access$ClipboardInputLayout$ClipItemView(ClipboardInputLayout.kt:1)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:287)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$3.invoke(ClipboardInputLayout.kt:285)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.app.ui.components.FlorisStaggeredVerticalGridKt.FlorisStaggeredVerticalGrid-uFdPcIQ(FlorisStaggeredVerticalGrid.kt:112)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$HistoryMainView(ClipboardInputLayout.kt:285)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout(ClipboardInputLayout.kt:515)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:511)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:502)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:502)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:475)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:99)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:52)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:49)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:466)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:465)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService.ImeUi(FlorisImeService.kt:465)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:115)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(FlorisImeService.kt)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(FlorisImeService.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:641)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>

<details>
<summary>1647722931083.stacktrace</summary>

```
java.lang.IllegalArgumentException: Unknown URL content://dev.patrickgold.florisboard.beta.provider.clip/clips/2072899223352
	at android.content.ContentResolver.delete(ContentResolver.java:1418)
	at dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardItem.close(ClipboardDatabase.kt:156)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardManager$clearHistory$1.invokeSuspend(ClipboardManager.kt:272)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
> Unknown URL content://dev.patrickgold.florisboard.beta.provider.clip/clips/2072899223352

That's indeed unknown and confirms my theory that you still have old images on your history. (The provider ID has changed as well as the path). Above commit thus wraps the delete call in a try block and thus it won't crash anymore for old images (hopefully). This means I will have to make an rc04 release, which will be released later today.
