### ISSUE TITLE
null pointer crash when gesture typing enabled when lastkey is not yet set

### ISSUE THREAD

**Issue by magnus-ISU** [florisboard/florisboard#1661]
#### Short description
Describe what you were doing that could've led to the crash.

I don't know as I just installed this today, however I think the stacktrace is useful

#### Steps to reproduce
1. Unsure

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-G928V
- Android: 7.0 (cn=N sdk=24)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647666441784.stacktrace</summary>

```
java.lang.NullPointerException: lastKey must not be null
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner$Companion.getFirstKeyLastKey(StatisticalGlideTypingClassifier.kt:361)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner$Companion.access$getFirstKeyLastKey(StatisticalGlideTypingClassifier.kt:346)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.<init>(StatisticalGlideTypingClassifier.kt:396)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.initializePruner(StatisticalGlideTypingClassifier.kt:149)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.setWordData(StatisticalGlideTypingClassifier.kt:132)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Can you reproduce this crash in 0.3.14-rc02? If not, we can close this issue, as the file this crash occurs has changed a bit and I cannot see where the crash should occur.

**Comment by magnus-ISU** [comment]
I don't know why it happened in the first place. Going to close as it's probably nothing.
