### ISSUE TITLE
Copy/Cut general text issue. Large clipboard usage.

### ISSUE THREAD

**Issue by Edeamas** [florisboard/florisboard#1663]
#### Short description
Crash. Reproduce aren't clean. Showed up 3 times (One in 2021.02. Second in 2021.05. Third in 2021.11.) and now.
Copy/Cut text from Firefox's platform browser (don't tried another platform) [versions different].

#### Steps to reproduce (Or what was before crash.)
0. I have 15 different sized pinned notes and few more different sized notes, (~10 maybe). Max history size is 50 notes. "Sync from System clipboard" is enable. Have opened in browser almoust 200 - 340 pages. And some music/video play at back.
1. Go to 'web site'
2. Select the text. Field/General text/Long url
3. Copy/Cut on 'some text(800-950 symbols)' 
- [Copy/Cut can be by system button or smart bar  button.].
- Action is not happen. (Text highlighting is not gone.)
4. Wait for 1-2 seconds.
5. Copy/Cut another more. '×1/×2 pressed button'
- Action is go on. (Text highlighting is gone.)
6. Everything can freese.
7. Get crash
8. See error
9. Try to copy/cut text once more. No errors.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Install Source: F-Droid
- Device: LGE LG-H930
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = false
suggestions_next_word = false
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1647659830220.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6991)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

Could you please check the behavior in the latest release candidate for 0.3.14? The clipboard has massively changed and thus I cannot at all say if this error is still existing in this form.

**Comment by patrickgold** [comment]
Closing as this issue is stale. If still an issue in 0.3.15-rc01 we can reopen this issue.
