### ISSUE TITLE
Crash - Reason unknown

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1771]
#### Environment information
- FlorisBoard Version: 0.3.15-rc02 (79)
- Device: Xiaomi Mi 9T Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1649536773433.stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property popupUiController has not been initialized
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutController.getPopupUiController(TextKeyboardLayout.kt:439)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:146)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.access$TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:1)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:162)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:160)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.invoke$lambda-0(DisposableLifecycleEffect.kt:37)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.$r8$lambda$-3ALqMvi9iwlusIGFG3z5Hb_ybQ(Unknown Source:0)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at dev.patrickgold.florisboard.ime.lifecycle.LifecycleInputMethodService.onWindowHidden(LifecycleInputMethodService.kt:81)
	at dev.patrickgold.florisboard.FlorisImeService.onWindowHidden(FlorisImeService.kt:372)
	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2025)
	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2014)
	at android.inputmethodservice.InputMethodService.access$500(InputMethodService.java:248)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:613)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:223)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Comment by patrickgold** [comment]
Thanks for reporting!

Above commit fixes the crash, will be included in today's 0.3.15 stable release.
