### ISSUE TITLE
Special characters crash FlorisBoard when using remotely using scrcpy

### ISSUE THREAD

**Issue by xkr47** [florisboard/florisboard#1811]
#### Short description
Special characters crash FlorisBoard every time when using remotely using scrcpy — **not** clicking the actual florisboard ui to enter the characters.

#### Steps to reproduce
1. Use phone remotely from a Linux computer running X using https://github.com/Genymobile/scrcpy
2. Open FlorisBoard app
3. Click the "Try out your setup" field
4. Either of the following:
    * On the computer keyboard, press some international key like `äöÄÖ`, OR
    * Install `xdotool` and run the following in a terminal, and switch to the scrcpy app within 3 seconds to simulate international keypress of `Ö`: `sleep 3 ; xdotool keydown Odiaeresis ; sleep 0.2 ;  xdotool keyup Odiaeresis`
5. See crash

#### Environment information
- FlorisBoard Version: 0.3.15 (80)
- Device: Fairphone FP3
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1650619465662.stacktrace</summary>

```
java.lang.IllegalArgumentException
	at java.lang.AbstractStringBuilder.appendCodePoint(AbstractStringBuilder.java:800)
	at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:236)
	at androidx.compose.foundation.text.StringHelpers_jvmKt.appendCodePointX(StringHelpers.jvm.kt:20)
	at androidx.compose.foundation.text.TextFieldKeyInput.typedCommand-ZmokQxo(TextFieldKeyInput.kt:71)
	at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:79)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke-ZmokQxo(TextFieldKeyInput.kt:223)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke(TextFieldKeyInput.kt:223)
	at androidx.compose.ui.node.ModifiedKeyInputNode.propagateKeyEvent-ZmokQxo(ModifiedKeyInputNode.kt:47)
	at androidx.compose.ui.input.key.KeyInputModifier.processKeyInput-ZmokQxo(KeyInputModifier.kt:78)
	at androidx.compose.ui.platform.AndroidComposeView.sendKeyEvent-ZmokQxo(AndroidComposeView.android.kt:531)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:538)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1863)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5821)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5524)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5682)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3180)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3157)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

**Comment by patrickgold** [comment]
If I had to guess that scrcpy does not enter the `äöÄÖ` characters in their proper Unicode encoding or it adds some helper char which is not defined in the Unicode standard. Do you by any chance have a way to test this on a byte level what an `Ö` key really produces in the transfer to the phone? Does not seem like the standard encoding.

**Comment by xkr47** [comment]
Hi, thanks for your quick reply!

Ok, dug into the code a bit and it seems to decompose characters like `Ö` into two characters `U+0308` "[combining diaresis](https://www.compart.com/en/unicode/U+0308)" + `O` [here](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/KeyComposition.java) before it sends them off to the device as key events [here](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/Controller.java#L149).

The KeyComposition.java class documentation refers to [this android documentation](https://source.android.com/devices/input/key-character-map-files#behaviors) which states that:

> When a dead key is typed followed by another character, the dead key and the following characters are composed. For example, when the user types a grave accent dead key followed by the letter 'a', the result is 'à'.
With this brief look into things it seems this method is a supported way of entering characters on Android devices.

So it seems like it would be a valid way to enter characters on Android, as the code specifically creates key events.

I want to add that this documented behaviour does **not** match [how Unicode decomposes characters](https://en.wikipedia.org/wiki/Unicode_equivalence#Combining_and_precomposed_characters), which would put the example two characters above in opposite order. But the individual characters should indeed be Unicode characters.

I also want to add that I tried several programs and have not yet found another application that wouldn't support this way of entering characters — and now that I look closer, I can see "just the dots" of the `ö` character i.e. the "dead key" render before it is converted later when allegedly the event for the `o` character arrives.

**Comment by patrickgold** [comment]
> I want to add that this documented behaviour does not match how Unicode decomposes characters, which would put the example two characters above in opposite order. But the individual characters should indeed be Unicode characters.

This is exactly the problem, and Java String Builders only work this way.

However I just noticed that the stacktrace only contains compose namespaces, so it is possible that the bug is caused by Jetpack Compose and not FlorisBoard. This is especially true because I use the default text box for the preview field.

You could try other apps using Jetpack Compose and see if they crash too.
