### ISSUE TITLE
Random crash while searching in Youtube Vanced

### ISSUE THREAD

**Issue by daraul** [florisboard/florisboard#1812]
#### Short description
I opened the search bar in Youtube Vanced. I tried again and it worked fine.

#### Steps to reproduce
1. Go to 'Youtube Vanced'
2. Click on the search button
3. See crash

#### Environment information
- FlorisBoard Version: 0.3.15-rc02 (79)
- Device: Xiaomi M2102J20SG
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1650884815038.stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property popupUiController has not been initialized
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutController.getPopupUiController(TextKeyboardLayout.kt:439)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:146)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.access$TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:1)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:162)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:160)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.invoke$lambda-0(DisposableLifecycleEffect.kt:37)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.$r8$lambda$-3ALqMvi9iwlusIGFG3z5Hb_ybQ(Unknown Source:0)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at dev.patrickgold.florisboard.ime.lifecycle.LifecycleInputMethodService.onWindowHidden(LifecycleInputMethodService.kt:81)
	at dev.patrickgold.florisboard.FlorisImeService.onWindowHidden(FlorisImeService.kt:372)
	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2283)
	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2264)
	at android.inputmethodservice.InputMethodService.access$700(InputMethodService.java:262)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:703)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInputWithToken(InputMethodService.java:673)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:233)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>

**Comment by daraul** [comment]
It happened again, and I was able to reproduce only once by closing Youtube Vanced, reopening, and trying to search again:

#### Environment information
- FlorisBoard Version: 0.3.15-rc02 (79)
- Device: Xiaomi M2102J20SG
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1650888158241.stacktrace</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property popupUiController has not been initialized
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutController.getPopupUiController(TextKeyboardLayout.kt:439)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:146)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.access$TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:1)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:162)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:160)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.invoke$lambda-0(DisposableLifecycleEffect.kt:37)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.$r8$lambda$-3ALqMvi9iwlusIGFG3z5Hb_ybQ(Unknown Source:0)
	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at dev.patrickgold.florisboard.ime.lifecycle.LifecycleInputMethodService.onWindowHidden(LifecycleInputMethodService.kt:81)
	at dev.patrickgold.florisboard.FlorisImeService.onWindowHidden(FlorisImeService.kt:372)
	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2283)
	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2264)
	at android.inputmethodservice.InputMethodService.access$700(InputMethodService.java:262)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:703)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInputWithToken(InputMethodService.java:673)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:233)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>
