### ISSUE TITLE
Failure on settings export

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1847]
#### Short description
When exporting FlorisBoard's settings, it usually fails on the first attempt with a "Failed to export backup archive: null" toast, and creates a zero length archive. The second attempt is successful though.

#### Steps to reproduce
1. Go to Advanced settings
2. Click on 'Back up data'
3. See error

#### Environment information
- FlorisBoard Version: 0.3.16-beta02
- Install Source: GitHub
- Device: Xiaomi Redmi note 8
- Android: 12.1, Custom

**Comment by tsiflimagas** [comment]
It also fails after some consecutive tries (I don't think the number is stable).

**Comment by patrickgold** [comment]
Hmm that's a strange bug, cannot reproduce this at all, it always succeeds for me.

I would need some additional info please, which may help me reproducing this bug:

1. When exporting, do you have the extensions also checked or only "Preferences"?
2. Do you export it to a third-party app or store it on local file system?

**Comment by tsiflimagas** [comment]
> Hmm that's a strange bug, cannot reproduce this at all, it always succeeds for me.

Yeah, sometimes it's hard for me to reproduce it too, it seems to be taking too many tries. Force closing the app seems to be helping in this.

> When exporting, do you have the extensions also checked or only "Preferences"?
Do you export it to a third-party app or store it on local file system?

1. Yep, all four checked.
2. On local filesystem.

I tried taking a logcat filtered by pid, but there was nothing about the problem there, so I recorded a full one (there will be some chatter from the system). Note that I made 2-3 successful tries before the failed one.
[floris-settings-export.txt](https://github.com/florisboard/florisboard/files/8691988/floris-settings-export.txt)

**Comment by patrickgold** [comment]
I couldn't find something specifically, only this stack strace, which appears several times:

```
05-14 04:58:48.542  2367  2367 W ziparchive: Unable to open '/data/app/~~8TQIXkc6Funv2w4j6Wfx3g==/dev.patrickgold.florisboard.debug-Av5d68t3QTjZX2r17w7CLw==/base.apk': No such file or directory
05-14 04:58:48.542  2367  2367 E ndroid.systemu: Failed to open APK '/data/app/~~8TQIXkc6Funv2w4j6Wfx3g==/dev.patrickgold.florisboard.debug-Av5d68t3QTjZX2r17w7CLw==/base.apk': I/O error
05-14 04:58:48.542  2367  2367 W ResourcesManager: failed to preload asset path '/data/app/~~8TQIXkc6Funv2w4j6Wfx3g==/dev.patrickgold.florisboard.debug-Av5d68t3QTjZX2r17w7CLw==/base.apk'
05-14 04:58:48.542  2367  2367 W ResourcesManager: java.io.IOException: Failed to load asset path /data/app/~~8TQIXkc6Funv2w4j6Wfx3g==/dev.patrickgold.florisboard.debug-Av5d68t3QTjZX2r17w7CLw==/base.apk
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.content.res.ApkAssets.nativeLoad(Native Method)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:980)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ResourcesManager.getResources(ResourcesManager.java:1101)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2415)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1759)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1745)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1514)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3037)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:286)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.systemui.toast.ToastUI$ToastOutAnimatorListener.onAnimationEnd(ToastUI.java:218)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.os.Handler.handleCallback(Handler.java:938)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.os.Looper.loopOnce(Looper.java:201)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.os.Looper.loop(Looper.java:288)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-14 04:58:48.542  2367  2367 W ResourcesManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

It does not make really sense though, as I am reading from the internal file system of the app, not the base APK. Will have to look into this more.

**Comment by patrickgold** [comment]
Interesting during testing for #1873 I had to backup my config and then I got the exact same error as you got. Second attempt worked completely fine though. Interestingly, the file itself is written, just that it has 0 bytes. Now I can at least pinpoint it a bit better, where the issue must occur.

**Comment by patrickgold** [comment]
So I ran the backup about 200 times and the null error only occurred exactly once. When it occurred, this was the stack trace:

```
2022-05-27 19:55:58.738 10831-10831/dev.patrickgold.florisboard.debug E/ComposableSingletons$BackupScreenKt$lambda-1$1$backUpToFileSystemLauncher$1: invoke() - java.lang.NullPointerException
        at dev.patrickgold.florisboard.app.settings.advanced.ComposableSingletons$BackupScreenKt$lambda-1$1$backUpToFileSystemLauncher$1.invoke(BackupScreen.kt:116)
        at dev.patrickgold.florisboard.app.settings.advanced.ComposableSingletons$BackupScreenKt$lambda-1$1$backUpToFileSystemLauncher$1.invoke(BackupScreen.kt:105)
        at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$1.onActivityResult(ActivityResultRegistry.kt:106)
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:227)
        at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.invoke(ActivityResultRegistry.kt:105)
        at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.invoke(ActivityResultRegistry.kt:104)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:802)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:647)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:488)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1040)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

It seems that the backup workspace, even if previously verified to be not null, is null all of a sudden, and then only in 1 out of 200 runs. This is very very strange and I currently don't really know how to fix this.

**Comment by tsiflimagas** [comment]
> So I ran the backup about 200 times and the null error only occurred exactly once.

Wow, that's a big number. Did you make a script for that? As for reproducibility, killing the app seems to be setting it again to the right state for the bug to happen, I'm not sure though how stable is this too.
Well, since that's so rare to happen (I haven't even seen any other reports), it's just a mark to be polished, not high on priority.

**Comment by patrickgold** [comment]
> Wow, that's a big number. Did you make a script for that?

Nope, as this is a very specific test involving UI on an actual devcice and it would have taken me much longer to set up such script than actually doing it by hand (which was only like 15 mins because the it is really just a few taps and I did it on my high-end phone).

> As for reproducibility, killing the app seems to be setting it again to the right state for the bug to happen, I'm not sure though how stable is this too.

**Comment by patrickgold** [comment]
Relabeling this issue as I created a new area for Backup&Restore issues (as this isn't exactly a Settings issue per se).

**Comment by tsiflimagas** [comment]
I can no longer reproduce this bug. It's been two years, I've switched to a different device, I'm two Android versions ahead, but apart from that there have been many changes in the codebase and dependencies. So, I guess it's possible that the bug has vanished by itself, thus I'm closing this issue.
