### ISSUE TITLE
Random crashes while typing

### ISSUE THREAD

**Issue by PowerMan2206** [florisboard/florisboard#192]
Florisboard has been crashing (seemingly) randomly when I type. Here's the whatever it gives me
```
~~~ 1610665040611.stacktrace ~~~

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1000)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1595)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1436)
	at dev.patrickgold.florisboard.ime.popup.KeyPopupManager.extend(KeyPopupManager.kt:389)
	at dev.patrickgold.florisboard.ime.text.key.KeyView$onFlorisTouchEvent$3.run(KeyView.kt:258)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

Android 10 if that helps

**Comment by patrickgold** [comment]
Thanks for reporting! This issue should normally not even exist anymore, as the PopupWindows which cause this crash are not existent anymore since the popup rework (not yet released). I will let this issue open until v0.3.3 is out though (will release it this Sunday), so you can confirm that it has been fixed for you. Thanks in advance!

**Comment by patrickgold** [comment]
@PowerMan2206 Does this crash still occur for you in the latest version (v0.3.4 if you are gettting it via F-Droid)?

**Comment by PowerMan2206** [comment]
Doesn't look like it. Has been pretty stable since I updated

**Comment by patrickgold** [comment]
Cool, thanks for reporting back! As the PopupWindow class (which caused this crash) is not existent in the newest versions anymore, I will see this as resolved and will close the issue.
