### ISSUE TITLE
Provide workaround for missing Java API in NetworkUtils on Android 7.0 and 7.1

### ISSUE THREAD

**Issue by thane-k** [florisboard/florisboard#1970]
issue tracker:
#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-26T10:28:37.876+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.90 GiB (69.91% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 14.90 MiB (3.88% used, 384.00 MiB max)
Native heap memory  : 25.10 MiB (73.82% used, 34.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1658822134431.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$1.invoke(NlpManager.kt:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:6)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:2)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:3)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:7)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:11)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a123a7b, Dispatchers.Default]

```
</details>

this wasn't any inconvenience (on the contrary, it seemed to happen during inactive phone time), but thought it might be helpful to post? happy to take down if this was mistaken.
so much love for this beautiful project

**Comment by thane-k** [comment]
happened again, very close in time to another app sending a notification that it won't run unless GP-Services are enabled? (semi-mid bumbling de-googling the phone)
probably confidence, especially given that FB was downloaded as an apk from here, but hey possibly not?

#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-26T10:40:21.281+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.67 GiB (61.45% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 10.95 MiB (2.85% used, 384.00 MiB max)
Native heap memory  : 25.03 MiB (78.22% used, 32.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1658831809162.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$internalSuggestions$2$1.invokeSuspend(NlpManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@45bebfe, Dispatchers.Default]

```
</details>

**Comment by Glitchy-Tozier** [comment]
Thank you for posting this bug-report! 

> but thought it might be helpful to post?

It's definitely helpful, I (and possibly Patrick, as well) wasn't aware of this bug.

Off-topic:
Just curious; how did you create this issue? Normally, there shouldn't be a way to prevent receiving a tag such as `bug` or `question`.

**Comment by patrickgold** [comment]
I really don't know what causes this bug, however I suspect it has something to do with the fact that your device misses a Regex API that should normally exist. I can test it out on my Android 7 device to see if I can reproduce this issue.

> Just curious; how did you create this issue? Normally, there shouldn't be a way to prevent receiving a tag such as bug or question.

I suspect either a custom Android client or through the super-stable-and-not-buggy-at-all GitHub mobile site (it allows blank issues even if I disable them).

**Comment by patrickgold** [comment]
OK I can actually reproduce this issue, it is indeed caused by a missing Java API on Android 7. The missing API is used for checking if a clipboard entry is a URL or email address, so the crash occurs every-time you or an app copies something.

The annoying thing is I don't know if I can provide an alternative on Android 7, if not the "smart clipboard" extraction of URLs and email addresses will be an Android 8+ feature.

**Comment by thane-k** [comment]
it was indeed done through the mobile site. if this brings inconvenience, is there perhaps something that could be done to prevent it? just copied the report and clicked on the button included in the crash report to open the FlorisB GitHub, didn't give much thought to it at the time.

it did bring some curiosity as to why it was not showing the link atop the keyboard; the tired mind (that was being used way later than in the day than it perhaps should have been) just assumed it to be a feature that had been enabled on the previously lost phone, but escaped notice on this one.
also, a possible idea (please bear with me; on this end, little is known about systems such as this so unsure if it would be viable/etc.): if there are more than a small few using it on android prior to 8, perhaps it might be a suitable alternative, at least temporarily, to have any details recently copied to clipboard to show up where the link does? and maybe this could be a toggleable option somewhere in settings

**Comment by patrickgold** [comment]
Above commit now disables smart clipboard extraction on Android 7.0 and 7.1, which only means that email addresses, URLs and phone numbers won't get extracted but else every clipboard feature continues to work as intended. If you want you can try the debug artifact of linked PR above (installs separately) and confirm this for yourself (type a URL or email address like john.doe@example.com and copy it)

**Comment by thane-k** [comment]
it did not seem to be a fault on this end, all is well!

> assuming such a thing is very hard
very understandable.

**Comment by patrickgold** [comment]
> that the crash happens only when confirmed as a website/email?

Yes this is indeed the case - only if a website or email match was found the missing API which causes the crash tries to get called. As said 0.4.0-alpha02 should fix this issue,  I just don't extract websites and emails on Android 7 or 7.1

**Comment by patrickgold** [comment]
> that the crash happens only when confirmed as a website/email?

Yes this is indeed the vase - only if a website or email match was found the missing API which causes the crash tries to get called. As said 0.4.0-alpha02 should fix this issue,  I just don't extract websites and emails on Android 7 or 7.1

**Comment by patrickgold** [comment]
> that the crash happens only when confirmed as a website/email?

Yes this is indeed the case - only if a website or email match was found the missing API which causes the crash tries to get called. As said 0.4.0-alpha02 should fix this issue,  I just don't extract websites and emails on Android 7 or 7.1

**Comment by patrickgold** [comment]
> that the crash happens only when confirmed as a website/email?

Yes this is indeed the case - only if a website or email match was found the missing API which causes the crash tries to get called. As said 0.4.0-alpha02 should fix this issue,  I just don't extract websites and emails on Android 7 or 7.1

**Comment by thane-k** [comment]
aha! the previous impression was that the crash happens when going through the process of checking, rather than after confirming that it is website/email. this is good to know

immense gratitude and appreciation to you and @Glitchy-Tozier and any other devs that might have escaped notice from this perspective

**Comment by thane-k** [comment]
happened again, with no recollection of copying url/email?
the plot thickens!

#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-28T08:37:24.251+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.61 GiB (59.35% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 13.94 MiB (3.63% used, 384.00 MiB max)
Native heap memory  : 25.32 MiB (70.35% used, 36.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1658994976676.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$internalSuggestions$2$1.invokeSuspend(NlpManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5982190, Dispatchers.Default]

```
</details>

<details>
<summary>1658995796106.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$internalSuggestions$2$1.invokeSuspend(NlpManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6543733, Dispatchers.Default]

```
</details>

**Comment by thane-k** [comment]
(please also note it certainly is possible that one was copied but with little thought given to it, the day is nearing it's end)

**Comment by thane-k** [comment]
another one, as above, no recollected url/email copied

**Comment by thane-k** [comment]
seemed to happen immediately after pasting the debug log into the thread just opened in the crash section?
may have also possibly been what fixed the crash of that thread (does that mean it should be posted there instead of here?.. confused but eh)

#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-28T10:56:22.202+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.57 GiB (57.76% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 4.07 MiB (1.06% used, 384.00 MiB max)
Native heap memory  : 20.20 MiB (84.16% used, 24.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1659005556845.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$1.invoke(NlpManager.kt:4)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:6)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:2)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:3)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:7)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:11)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@244b30f, Dispatchers.Default]

```
</details>

**Comment by thane-k** [comment]
aaand again.
are these posted logs still helpful? aside from when they're possibly relevant to something else as above

#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-28T11:05:29.647+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.69 GiB (62.25% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 11.91 MiB (3.10% used, 384.00 MiB max)
Native heap memory  : 27.22 MiB (85.05% used, 32.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

**Comment by patrickgold** [comment]
> aha! the previous impression was that the crash happens when going through the process of checking, rather than after confirming that it is website/email. this is good to know

Tbh after some thought and testing I think it happens always when **attempting** to check if a string has URLs in it, doesn't necessarily have to be one in it. Like I said this check has been safeguarded in #1974 and on Android 7 and 7.1 it just always assumes no URL is in the string.

>  are these posted logs still helpful? aside from when they're possibly relevant to something else as above

Nope they aren't helpful anymore because they are always the same stack trace. If this crash still occurs in 0.4.0-alpha02 please let me know, then I need to dig further, but I think (at least based on testing on my old Huawei with Android 7) that I fixed the issue.
