### ISSUE TITLE
keyboard completely void of buttons to enter any letters/numbers/etc.

### ISSUE THREAD

**Issue by thane-k** [florisboard/florisboard#1980]
see attached image for a better understanding
mystified as to what might have caused it
happens anywhere and everywhere that brings up the keyboard. going to have to shift some things around/possibly temporarily re-enable Gboard as a backup in the morning when more awake.. bleh

will find a log on the phone in a moment (this had to be typed using laptop)
will it be possible to paste as a comment with a largely unusable keyboard? let's find out! (the keyboard's built in clipboard will likely be of immense help here)

![image](https://user-images.githubusercontent.com/108777421/181488189-835274ba-d471-446d-9c14-f6c67867a14a.png)

**Comment by thane-k** [comment]
note: the black box above the keyboard was added as an edit after the screenshot for privacy reasons, and is unrelated to the issue
also note: it's not just that the key buttons are still there but no longer visible; tapping where they should be brings no results

**Comment by thane-k** [comment]
update: it works again!
the only thing that might have restored it was copying of debug log and/or the app having some quiet alone time in the naughty corner to think about what's happened and seemingly fix all by itself?

anyway here's the debug log
#### Environment information
- FlorisBoard [0.4.0-alpha01](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha01) (87)
- Device: HUAWEI NXT-L09 (NXT-L09)
- Android: 7.0 (cn=N sdk=24)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-07-28T10:01:13.800+0000
Manufacturer        : HUAWEI
Model               : HUAWEI NXT-L09
Product             : NXT-L09
Android             : 7.0 (cn=N sdk=24) [NXT-L09C636B598]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.56 GiB (57.33% used, 2.72 GiB max)
Font scale          : 0.85
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha01 (87)
Build type          : beta
Build commit hash   : 07e92f052b90049044be1646970c5220254a6d94
Java heap memory    : 14.83 MiB (3.86% used, 384.00 MiB max)
Native heap memory  : 26.70 MiB (74.18% used, 36.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1659000217287.stacktrace</summary>

```
java.lang.NoSuchMethodError: No virtual method start(Ljava/lang/String;)I in class Ljava/util/regex/Matcher; or its super classes (declaration of 'java.util.regex.Matcher' appears in /system/framework/core-oj.jar)
	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:2)
	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:3)
	at androidx.lifecycle.viewmodel.R$id.get(Unknown Source)
	at dev.patrickgold.florisboard.lib.util.NetworkUtils$getUrls$1.invoke(NetworkUtils.kt:3)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$ClipboardSuggestionProvider.suggest(NlpManager.kt:28)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$assembleCandidates$1.invokeSuspend(NlpManager.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager.access$assembleCandidates(NlpManager.kt:2)
	at dev.patrickgold.florisboard.ime.nlp.NlpManager$internalSuggestions$2$1.invokeSuspend(NlpManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c830dab, Dispatchers.Default]

```
</details>

**Comment by thane-k** [comment]
a possibly relevant debug log posted into thread "Provide workaround for missing Java API in NetworkUtils on Android 7.0 and 7.1 #1970"

**Comment by thane-k** [comment]
a possibly relevant debug log posted into thread " Provide workaround for missing Java API in NetworkUtils on Android 7.0 and 7.1 #1970 "

**Comment by patrickgold** [comment]
I think you completely destroyed my logic with your repeated crashes in #1970, and the layout loader got stuck in the loading process. Simplest workaround is to go into System Settings > Apps > FlorisBoard Beta > Force Stop **and** Clear Cache (NOT Storage though!!) and then click a text field again so the keyboard has a chance to reload.

The provided stacktrace is also the one from #1970, so I think this issue is indirectly or even directly caused by #1970.

**Comment by patrickgold** [comment]
I know how this issue can occur and during development in the layout manager I had this blank keyboard occurring multiple times, however in production this hasn't been reported in the latest few stable and beta versions. So I do not know how much help this issue is and if it is worth keeping open tbh.

**Comment by thane-k** [comment]
thank you for your answers on this and the other threads. all very helpful

**Comment by thane-k** [comment]
after thinking about this a little further, this had happened right in the middle of the four crashes posted toward the end of #1970 ; suggesting that this crash posted here would have been caused by just the first two crashes? could that have been so?
not complaining about anything of course, love the keyboard! just trying to understand

**Comment by patrickgold** [comment]
IMO this issue is a result of the repeated crashes in #1970. Even if the crash is in an entirely different area of the code, once an unhandled crash occurs anywhere it drags everything with it. So I think we should see how this behaves in 0.4.0-alpha02 once I release it.

**Comment by thane-k** [comment]
🙏

**Comment by BBaoVanC** [comment]
This has just happened to me, at the unlock screen after doing an OS update. Is this issue known by anyone else? I can't do anything because the phone is BFU and needs password entered, and there doesn't seem to be a way to change to a different keyboard.

**Comment by lm41** [comment]
https://github.com/florisboard/florisboard/issues/2362 could be what you are looking for
