### ISSUE TITLE
Crash report out of the blue

### ISSUE THREAD

**Issue by Tealk** [florisboard/florisboard#2016]
#### Short description
Crash report as push notification while I switched between apps
Last opened app was fennic

#### Environment information
- FlorisBoard [0.3.16](https://github.com/florisboard/florisboard/releases/v0.3.16) (86)
- Device: Google Pixel 6 (oriole)
- Android: 12 (cn=S_V2 sdk=32)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-14T08:42:00.252Z
Manufacturer        : Google
Model               : Pixel 6
Product             : oriole
Android             : 12 (cn=S_V2 sdk=32) [SQ3A.220705.003.A1.22307002]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 6,16 GiB (83,04% used, 7,41 GiB max)
Font scale          : 1.0
Locales             : de-DE

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.3.16 (86)
Build type          : release
Build commit hash   : null
Java heap memory    : 4,32 MiB (1,69% used, 256,00 MiB max)
Native heap memory  : 27,04 MiB (84,67% used, 31,93 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : false
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1660466465274.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: length=161; index=162
	at java.lang.String.getChars(String.java:788)
	at android.text.SpannableStringInternal.getChars(SpannableStringInternal.java:181)
	at android.text.TextUtils.getChars(TextUtils.java:155)
	at android.text.TextUtils.substring(TextUtils.java:346)
	at android.view.inputmethod.EditorInfo.getInitialTextBeforeCursor(EditorInfo.java:739)
	at androidx.core.view.inputmethod.EditorInfoCompat$Api30Impl.getInitialTextBeforeCursor(Unknown Source:3)
	at dev.patrickgold.florisboard.ime.editor.EditorInstance.handleStartInputView(EditorInstance.kt:10)
	at dev.patrickgold.florisboard.FlorisImeService.onStartInputView(FlorisImeService.kt:10)
	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2450)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.restartInput(InputMethodService.java:707)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:723)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:199)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>

**Comment by lm41** [comment]
Is this still a problem in the latest version `v0.4.6`?
