### ISSUE TITLE
Florisboard notification about crash

### ISSUE THREAD

**Issue by Bugaddr** [florisboard/florisboard#2039]
#### Short description
Sorry, idk what exactly is triggering this, the notification appears repeatedly.

#### Steps to reproduce
Sorry cant tell exactly how to reproduce, i think app is crashing or not responding in background. I had downloaded this update recently

#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Xiaomi Redmi Note 4 (lineage_mido)
- Android: 11 (cn=R sdk=30)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-30T19:17:14.646Z
Manufacturer        : Xiaomi
Model               : Redmi Note 4
Product             : lineage_mido
Android             : 11 (cn=R sdk=30) [lineage_mido-userdebug 11 RQ3A.211001.001 eng.zeelog.20220107.110628 release-keys]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.89 GiB (54.10% used, 3.49 GiB max)
Font scale          : 1.0
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 8.86 MiB (4.61% used, 192.00 MiB max)
Native heap memory  : 24.19 MiB (88.76% used, 27.25 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : false
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661878722627.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.lib.StateAdaptersKt.observeAsNonNullState(StateAdapters.kt:10)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.observeActiveState(Unknown Source:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1$1.invoke(FlorisImeService.kt:73)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1$1.invoke(FlorisImeTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1.invoke(FlorisImeTheme.kt:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:4)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:6)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:132)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt.FlorisImeTheme(FlorisImeTheme.kt:32)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1.invoke(FlorisImeService.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt$ProvideKeyboardRowBaseHeight$2.invoke(FlorisImeSizing.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt.ProvideKeyboardRowBaseHeight(FlorisImeSizing.kt:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt$ProvideLocalizedResources$1.invoke(Resources.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt.ProvideLocalizedResources(Resources.kt:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUiWrapper(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ComposeInputView.Content(FlorisImeService.kt:4)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:23)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:88)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at kotlin.LazyKt__LazyJVMKt.invokeComposable(LazyJVM.kt:2)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:5)
	at kotlin.text.UStringsKt.observeDerivedStateRecalculations(UStrings.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:7)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:12)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5036)
	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:1920)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1755)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2182)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2131)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:750)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:722)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:226)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```
</details>

**Comment by Bugaddr** [comment]
Duplicate #2025
