### ISSUE TITLE
FlorisBoard crashes more often after the last update

### ISSUE THREAD

**Issue by lm41** [florisboard/florisboard#2040]
#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Motorola Moto g(30) (caprip_retailen)
- Android: 12 (cn=S sdk=31)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-31T09:12:19.655576Z
Manufacturer        : motorola
Model               : moto g(30)
Product             : caprip_retailen
Android             : 12 (cn=S sdk=31) [S0RCS32.41-10-19-3]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 2,00 GiB (55,06% used, 3,64 GiB max)
Font scale          : 1.0
Locales             : en-DE,de-DE

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 10,05 MiB (5,24% used, 192,00 MiB max)
Native heap memory  : 26,87 MiB (85,59% used, 31,40 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1661937082015.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.lib.StateAdaptersKt.observeAsNonNullState(StateAdapters.kt:10)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.observeActiveState(Unknown Source:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1$1.invoke(FlorisImeService.kt:73)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1$1.invoke(FlorisImeTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1.invoke(FlorisImeTheme.kt:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:4)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:6)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:132)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt.FlorisImeTheme(FlorisImeTheme.kt:32)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1.invoke(FlorisImeService.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt$ProvideKeyboardRowBaseHeight$2.invoke(FlorisImeSizing.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt.ProvideKeyboardRowBaseHeight(FlorisImeSizing.kt:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt$ProvideLocalizedResources$1.invoke(Resources.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt.ProvideLocalizedResources(Resources.kt:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUiWrapper(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ComposeInputView.Content(FlorisImeService.kt:4)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:23)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:88)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at kotlin.LazyKt__LazyJVMKt.invokeComposable(LazyJVM.kt:2)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:5)
	at kotlin.text.UStringsKt.observeDerivedStateRecalculations(UStrings.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:7)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:12)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:20843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5048)
	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:2451)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2268)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2714)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2678)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:1089)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:1048)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:225)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8058)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>

**Comment by lm41** [comment]
I've overlooked #2025 sorry for the inconvinience.
