### ISSUE TITLE
Florisboard crashed on device startup

### ISSUE THREAD

**Issue by snaik20** [florisboard/florisboard#2080]
#### Short description
Got an app crash notification when started the device.

#### Steps to reproduce
1. Shutdown the phone and start it.
2. Once phone is started, observe there is a system notification about the crash
3. Did not open any app after the start, not even florisboard.

#### Environment information
- FlorisBoard [0.4.0-alpha04](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha04) (90)
- Device: Motorola Moto G Play (lineage_harpia)
- Android: 10 (cn=Q sdk=29)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-10-03T10:23:00.824Z
Manufacturer        : Motorola
Model               : Moto G Play
Product             : lineage_harpia
Android             : 10 (cn=Q sdk=29) [e_harpia-userdebug 10 QQ3A.200805.001 eng.root.20220923.195713 dev-keys,dev-release]
ABIs                : [armeabi-v7a, armeabi]
Memory              : 931.43 MiB (48.82% used, 1.86 GiB max)
Font scale          : 1.0
Locales             : en-IN

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha04 (90)
Build type          : beta
Build commit hash   : 31a01c8d39ba425e4e1e424e9671ffbb96c24fc0
Java heap memory    : 12.54 MiB (6.53% used, 192.00 MiB max)
Native heap memory  : 22.96 MiB (90.23% used, 25.45 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1664792356201.stacktrace</summary>

```
java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:9)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.query$1(RoomDatabase.java:2)
	at dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardHistoryDao_Impl$7.call(ClipboardHistoryDao_Impl.java:4)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:8)
	... 3 more

```
</details>

**Comment by snaik20** [comment]
@patrickgold Created https://github.com/florisboard/florisboard/pull/2085 to resolve this. Please take a look

**Comment by snaik20** [comment]
I have not seen this issue since. Closing this ticket, will revisit if the issue persists.
