### ISSUE TITLE
crash after force quit after modemcrash ?

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#2131]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. My phone's modem crashed
2. Phone entered qualcomm crashdump mode
3. Forced reboot
4. Preferences were not applied
5. Force stopped floris
6. Floris crashed after i reopened it

#### Environment information
- FlorisBoard [0.4.0-alpha04](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha04) (90)
- Device: OnePlus HD1905 (OnePlus7T)
- Android: 12 (cn=S_V2 sdk=32)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-12-10T19:37:16.038Z
Manufacturer        : OnePlus
Model               : HD1905
Product             : OnePlus7T
Android             : 12 (cn=S_V2 sdk=32) [SQ3A.220705.004]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.32 GiB (59.29% used, 7.29 GiB max)
Font scale          : 1.0
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha04 (90)
Build type          : beta
Build commit hash   : 31a01c8d39ba425e4e1e424e9671ffbb96c24fc0
Java heap memory    : 4.08 MiB (1.59% used, 256.00 MiB max)
Native heap memory  : 17.03 MiB (61.52% used, 27.68 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1670701033095.stacktrace</summary>

```
java.util.NoSuchElementException: List contains no element matching the predicate.
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:24)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:17)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
	at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:85)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:6)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:281)
	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(NavHost.kt:1)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:43)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:20)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:4)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:7)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:9)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:63)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:8)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:15)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@15f4bba, androidx.compose.ui.platform.MotionDurationScaleImpl@a821a6b, StandaloneCoroutine{Cancelling}@73409c8, AndroidUiDispatcher@4d34a61]

```
</details>

Maybe the settings got corrupted

**Comment by tsiflimagas** [comment]
This looks like #1726 but has the added crashlog.

**Comment by lm41** [comment]
This stack-trace has no function call in the florisboard namespace, so definitely a weird one
