### ISSUE TITLE
Crashes everytime i press  volume key

### ISSUE THREAD

**Issue by SudirEbi** [florisboard/florisboard#2144]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

**Comment by ebenezerk846** [comment]
#### Environment information
- FlorisBoard [0.3.16](https://github.com/florisboard/florisboard/releases/v0.3.16) (86)
- Device: Xiaomi Redmi K20 Pro (syberia_raphael)
- Android: 13 (cn=TIRAMISU sdk=33)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2023-01-17T10:18:09.999025Z
Manufacturer        : Xiaomi
Model               : Redmi K20 Pro
Product             : syberia_raphael
Android             : 13 (cn=TIRAMISU sdk=33) [syberia_raphael-userdebug 13 TQ1A.221205.011 1672336021 release-keys]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.59 GiB (86.51% used, 5.31 GiB max)
Font scale          : 1.0
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.3.16 (86)
Build type          : release
Build commit hash   : null
Java heap memory    : 5.78 MiB (2.26% used, 256.00 MiB max)
Native heap memory  : Failed to retrieve memory usage: Format specifier '%d'

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1673950688644.stacktrace</summary>

```
java.lang.SecurityException: Settings key: <volume_key_cursor_control> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3065)
	at android.provider.Settings$System.getStringForUser(Settings.java:3740)
	at android.provider.Settings$System.getIntForUser(Settings.java:3845)
	at android.provider.Settings$System.getInt(Settings.java:3839)
	at android.inputmethodservice.InputMethodService.onKeyDown(InputMethodService.java:3073)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2901)
	at android.inputmethodservice.AbstractInputMethodService$AbstractInputMethodSessionImpl.dispatchKeyEvent(AbstractInputMethodService.java:181)
	at android.inputmethodservice.IInputMethodSessionWrapper$ImeInputEventReceiver.onInputEvent(IInputMethodSessionWrapper.java:253)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)

```
</details>

**Comment by lm41** [comment]
Closing this issue as stale
