### ISSUE TITLE
Crash after keyboard testing

### ISSUE THREAD

**Issue by cewbdex** [florisboard/florisboard#2336]
#### Short description

I have set backspace key hold to delete whole words and then clicked in the test field, typed some stuff, then held the backspace key and when it deleted everything, it crashed

#### Steps to reproduce

1. Set backspace hold to delete words
2. Type some stuff into test field
3. Hold backspace
4. Crash

#### Environment information
- FlorisBoard [0.4.0-alpha04](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha04) (90)
- Device: Xiaomi Redmi 4X (lineage_Mi8937)
- Android: 13 (cn=TIRAMISU sdk=33)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

======= SYSTEM INFO =======
Time                : 2023-11-26T08:30:47.989782Z
Manufacturer        : Xiaomi
Model               : Redmi 4X
Product             : lineage_Mi8937
Android             : 13 (cn=TIRAMISU sdk=33) [lineage_Mi8937-userdebug 13 TQ3A.230901.001 eng.root.20231110.051626 dev-keys]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 2,15 GiB (78,41% used, 2,75 GiB max)
Font scale          : 1.0
Locales             : cs-CZ

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha04 (90)
Build type          : beta
Build commit hash   : 31a01c8d39ba425e4e1e424e9671ffbb96c24fc0
Java heap memory    : 6,62 MiB (3,45% used, 192,00 MiB max)
Native heap memory  : 21,37 MiB (95,14% used, 22,46 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

</details>

<details>
<summary>1700987442688.stacktrace</summary>

`
java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0]
 at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:9)
 at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:2)
 at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:4)
 at androidx.compose.foundation.text.TextFieldKeyInput$process$2$5.invoke(TextFieldKeyInput.kt:5)
 at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:3)
 at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:95)
 at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:28)
 at androidx.compose.ui.input.key.KeyInputModifier.propagateKeyEvent-ZmokQxo(KeyInputModifier.kt:3)
 at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:24)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
 at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:488)
 at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1902)
 at android.app.Activity.dispatchKeyEvent(Activity.java:4259)
 at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
 at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:4)
 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:402)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6708)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6574)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)

Cristoforo Nero, [26.11.23 9:31]
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
 at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5799)
 at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5682)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7924)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

`
</details>

**Comment by lm41** [comment]
Can you confirm that this is only the case in the Florisboard settings? I don't know when and where, but I can no longer reproduce the problem on the latest master.

**Comment by Shivamhobbyist** [comment]
> Can you confirm that this is only the case in the Florisboard settings? I don't know when and where, but I can no longer reproduce the problem on the latest master.

Ya ! only in florisboard setting

**Comment by lm41** [comment]
This is fixed in the latest Alpha
