### ISSUE TITLE
Florisboard stop working for a while

### ISSUE THREAD

**Issue by Evething48** [florisboard/florisboard#239]
~~~ 1611581573423.stacktrace ~~~

java.lang.ArrayIndexOutOfBoundsException: length=1851; index=1851
	at java.util.ArrayList.add(ArrayList.java:468)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.addEventListener(FlorisBoard.kt:591)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyView.<init>(EmojiKeyView.kt:65)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invokeSuspend(EmojiKeyboardView.kt:151)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView.buildLayoutForCategory(EmojiKeyboardView.kt:140)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2.invokeSuspend(EmojiKeyboardView.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by patrickgold** [comment]
What version of FlorisBoard are you on?

**Comment by Evething48** [comment]
Version 0.3.2

Pada tanggal Sen, 25 Jan 2021 20:56, Patrick Goldinger <
notifications@github.com> menulis:

**Comment by patrickgold** [comment]
I hope that v0.3.3 hits F-Droid soon, as this release fixed many bugs and crashes and this could be one of them. I will wait with further investigation until you can confirm whether or not this occurs on v0.3.3!

**Comment by Evething48** [comment]
Ok, thanks.

Pada tanggal Sen, 25 Jan 2021 21:32, Patrick Goldinger <
notifications@github.com> menulis:

**Comment by patrickgold** [comment]
@Evething48 v0.3.4 has been released on F-Droid. Did this fix your issue?

**Comment by Evething48** [comment]
So far i didn't find problem now. No force close again. Thanks for fixing
it.

Pada tanggal Jum, 29 Jan 2021 01:23, Patrick Goldinger <
notifications@github.com> menulis:

**Comment by patrickgold** [comment]
Thanks for your response.I will see this issue as fixed now.
