### ISSUE TITLE
Crash when trying to open clipboard

### ISSUE THREAD

**Issue by SebiTalent04** [florisboard/florisboard#2406]
### Short description

![screen-20240311-081331-ezgif com-optimize](https://github.com/florisboard/florisboard/assets/52084701/ec700b07-6d7c-4b53-8c6f-2b856b0af166)

Using the Gboardish theme, it happens on all variants.

### Steps to reproduce

1. Open the action bar
2. Click on the clipboard button
3. See crash

#### Environment information
- FlorisBoard [0.4.0-beta01](https://github.com/florisboard/florisboard/releases/v0.4.0-beta01) (93)
- Device: Google Pixel 6a (bluejay)
- Android: 14 (cn=UPSIDE_DOWN_CAKE sdk=34)
- GrapheneOS (AP1A.240305.019.A1)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-03-11T06:19:54.932244Z
Manufacturer        : Google
Model               : Pixel 6a
Product             : bluejay
Android             : 14 (cn=UPSIDE_DOWN_CAKE sdk=34) [2024030900]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.37 GiB (79.88% used, 5.47 GiB max)
Font scale          : 1.0
Locales             : en-US,ro-RO

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-beta01 (93)
Build type          : beta
Build commit hash   : 0dd1f90c83409865e2def316d7cb4089b2f1c8be
Java heap memory    : 27.48 MiB (10.73% used, 256.00 MiB max)
Native heap memory  : 30.25 MiB (64.33% used, 47.03 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : false
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1710137849509.stacktrace</summary>

```
java.lang.IllegalStateException: Only Sp can convert to Px
	at androidx.compose.ui.unit.DensityWithConverter.toDp-GaN1DYA(Unknown Source:34)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.access$ClipTextItemDescription(SourceFile:323)
	at androidx.compose.foundation.ClickableKt$clickable$2.invoke(SourceFile:102)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SourceFile:28)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SourceFile:3)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at _COROUTINE._BOUNDARY$$ExternalSyntheticOutline0.m(SourceFile:60)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:46)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt.SnyggSurface(SourceFile:211)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$ClipItemView(SourceFile:131)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$1.invoke(SourceFile:13)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt$ClipboardInputLayout$HistoryMainView$1$1$1.invoke(SourceFile:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at _COROUTINE._BOUNDARY$$ExternalSyntheticOutline0.m(SourceFile:60)
	at androidx.room.Room.FlorisStaggeredVerticalGrid-uFdPcIQ(SourceFile:270)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout$HistoryMainView(SourceFile:495)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardInputLayoutKt.ClipboardInputLayout(SourceFile:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(SourceFile:198)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at _COROUTINE._BOUNDARY$$ExternalSyntheticOutline0.m(SourceFile:60)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:24)
	at androidx.compose.material.AppBarKt$TopAppBar$1.invoke(SourceFile:104)
	at androidx.compose.material.AppBarKt$TopAppBar$1.invoke(SourceFile:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:14)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SourceFile:28)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SourceFile:3)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at _COROUTINE._BOUNDARY$$ExternalSyntheticOutline0.m(SourceFile:60)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:46)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt.SnyggSurface(SourceFile:211)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(SourceFile:212)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(SourceFile:14)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at _COROUTINE._BOUNDARY$$ExternalSyntheticOutline0.m(SourceFile:60)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:24)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(SourceFile:100)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(SourceFile:6)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(SourceFile:3)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(SourceFile:482)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(SourceFile:58)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:154)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(SourceFile:29)
	at androidx.compose.runtime.CompositionImpl.recompose(SourceFile:34)
	at androidx.compose.runtime.Recomposer.access$performRecompose(SourceFile:117)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(SourceFile:656)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:934)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2c154c6, androidx.compose.ui.platform.MotionDurationScaleImpl@b499c87, StandaloneCoroutine{Cancelling}@372f7b4, AndroidUiDispatcher@8a47fdd]

```
</details>

**Comment by SebiTalent04** [comment]
LE: Happens with the "Use internal clipboard" too.

**Comment by SebiTalent04** [comment]
https://github.com/itsmartashub/floristyle/issues/6#issuecomment-1987777878

So after updating the app things may break and the themes should be reimported again.
