### ISSUE TITLE
Crash with `Can't represent a size of [...] in Constraints` exception

### ISSUE THREAD

**Issue by Occhioverde** [florisboard/florisboard#2539]
### Short description

As per the title, FlorisBoard sometimes randomly crashes with the `Can't represent a size of [...] in Constraints` exception.

As of now the crash happened no more than a time per day for 3/4 days, but I wasn't able to find a specific pattern as the error is triggered when the keyboard is invoked by clicking on fields in completely unrelated apps and screens.

### Steps to reproduce

1. Select a text box/text area in an application
2. Wait for FlorisBoard to start rendering
3. (Sometimes) Observe the crash

#### Environment information
- FlorisBoard [0.4.0-rc01](https://github.com/florisboard/florisboard/releases/v0.4.0-rc01) (96)
- Device: ASUS_X00HD (WW_Phone)
- Android: 8.1.0 (cn=O_MR1 sdk=27)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-08-29T10:02:22.199Z
Manufacturer        : asus
Model               : ASUS_X00HD
Product             : WW_Phone
Android             : 8.1.0 (cn=O_MR1 sdk=27) [OPM1.171019.011.WW_Phone-15.2016.1909.526-1]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1.93 GiB (69.39% used, 2.78 GiB max)
Font scale          : 0.85
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-rc01 (96)
Build type          : beta
Build commit hash   : 671f97eddb6e5960141aa1ffae70413e9e83ffab
Java heap memory    : 15.19 MiB (7.91% used, 192.00 MiB max)
Native heap memory  : 7.05 MiB (70.55% used, 10.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1724837182297.stacktrace</summary>

```
java.lang.IllegalArgumentException: Can't represent a size of 2147483646 in Constraints
	at androidx.collection.internal.Lock.bitsNeedForSize(SourceFile:41)
	at androidx.collection.internal.Lock.createConstraints-Zbe2FdA$ui_unit_release(SourceFile:18)
	at androidx.compose.ui.geometry.RectKt.Constraints(SourceFile:11)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:397)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(SourceFile:117)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at dev.patrickgold.florisboard.ime.popup.PopupSet$1.invoke(SourceFile:383)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(SourceFile:55)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:124)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:87)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:15)
	at android.view.View.draw(View.java:19217)
	at android.view.View.updateDisplayListIfDirty(View.java:18164)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3021)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2825)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2370)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1403)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6521)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</details>

<details>
<summary>1724925730175.stacktrace</summary>

```
java.lang.IllegalArgumentException: Can't represent a size of 547925 in Constraints
	at androidx.collection.internal.Lock.bitsNeedForSize(SourceFile:41)
	at androidx.collection.internal.Lock.createConstraints-Zbe2FdA$ui_unit_release(SourceFile:18)
	at androidx.compose.ui.geometry.RectKt.Constraints(SourceFile:11)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:397)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(SourceFile:117)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at dev.patrickgold.florisboard.ime.popup.PopupSet$1.invoke(SourceFile:383)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(SourceFile:55)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:124)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:87)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:15)
	at android.view.View.draw(View.java:19217)
	at android.view.View.updateDisplayListIfDirty(View.java:18164)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
	at android.view.View.updateDisplayListIfDirty(View.java:18123)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3021)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2825)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2370)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1403)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6521)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</details>

**Comment by lm41** [comment]
Was the bug already present in 0.4.0-beta04 and earlier or only since 0.4.0-rc1? If it has only appeared since rc1, it will be easier to find the reason, as there were not so many code changes.

**Comment by Occhioverde** [comment]
Thank you very much for your reply.

I can confirm that the issue started appearing after the update to the 0.4.0-rc.1 version, but as I've been on vacation in a place with a slow Internet connection I have postponed the various app updates for several weeks, so unfortunately I may well have skipped a version.

Maybe, if there is a way to check in F-Droid from which version I last updated, I can take a look and let you know.

**Comment by lm41** [comment]
The beta02 was released on April 20th and the beta03 on August 10th. I therefore assume that you had previously installed beta02 in case you always did the updates when they came out, right?

Can you tell me which popup mappings or more generally which subtype you use?

**Comment by Occhioverde** [comment]
Yes, I always kept my apps updated, so I have at most skipped the August 10th update as I already was on vacation.

As for the subtypes I use, I have configured the Italian and English (US) ones with just one customization in the latter (i.e. Euro as the currency in place of the Dollar):

![Configured subtypes list](https://github.com/user-attachments/assets/b693748b-1cf7-4442-9436-16fde8321a4a)

**Comment by lm41** [comment]
Is the problem still there in the latest version?

**Comment by Occhioverde** [comment]
No, I haven't observed this problem in quite some time now. Maybe it was fixed by some update.
Anyway, I guess that I can close this issue and, eventually, reopen it in case this error pops up again.
