### ISSUE TITLE
there was crash report when my phone was restarted

### ISSUE THREAD

**Issue by sudhegan** [florisboard/florisboard#2557]
### Short description

no problems i encountered other than this crash,  carsh log below,  thought the crash log would help

### Steps to reproduce

just randomly crashed after unlocking the phone after restart

#### Environment information
- FlorisBoard [0.4.0-rc02](https://github.com/florisboard/florisboard/releases/v0.4.0-rc02) (97)
- Device: Motorola edge 30 (dubai_g)
- Android: 14 (cn=UPSIDE_DOWN_CAKE sdk=34)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-09-09T08:26:06.078834Z
Manufacturer        : motorola
Model               : motorola edge 30
Product             : dubai_g
Android             : 14 (cn=UPSIDE_DOWN_CAKE sdk=34) [U1RD34.80-40]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 3.38 GiB (64.24% used, 5.26 GiB max)
Font scale          : 0.85
Locales             : en-IN

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-rc02 (97)
Build type          : beta
Build commit hash   : 2171e16346e7ecd7d0071a27ffea642d5ffa7a49
Java heap memory    : 14.01 MiB (5.47% used, 256.00 MiB max)
Native heap memory  : 17.86 MiB (78.75% used, 22.68 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1725870344695.stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
	at java.util.ArrayList$Itr.next(ArrayList.java:1064)
	at dev.patrickgold.jetpref.datastore.model.PreferenceModel$PersistenceHandler$loadPrefs$2$1$1$1.invokeSuspend(SourceFile:486)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at androidx.room.TransactionExecutor$1.run(SourceFile:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5fa6798, Dispatchers.IO]

```
</details>

**Comment by patrickgold** [comment]
is this bug reproducible or was this a one-time bug?

**Comment by sudhegan** [comment]
did't happen again, just once, thought may be an helpful (i'm not a programmer so didn't understand the log)

**Comment by patrickgold** [comment]
Closing as stale and non-reproducible, if it occurs again please report.
