### ISSUE TITLE
Florisboard failed to build.

### ISSUE THREAD

**Issue by GitAlasGo** [florisboard/florisboard#2670]
### Short description

I was trying to compile florisboard, but it failed.

### Steps to reproduce

./gradlew assembleDebug

### Crash log

> Task :lib:kotlin:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :lib:snygg:preBuild UP-TO-DATE
> Task :lib:android:preBuild UP-TO-DATE
> Task :lib:android:preDebugBuild UP-TO-DATE
> Task :lib:native:preBuild UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :lib:snygg:preDebugBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :lib:native:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :lib:android:writeDebugAarMetadata UP-TO-DATE
> Task :lib:snygg:writeDebugAarMetadata UP-TO-DATE
> Task :lib:native:writeDebugAarMetadata UP-TO-DATE
> Task :lib:android:generateDebugResValues UP-TO-DATE
> Task :lib:native:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :lib:snygg:generateDebugResValues UP-TO-DATE
> Task :lib:android:generateDebugResources UP-TO-DATE
> Task :lib:native:generateDebugResources UP-TO-DATE
> Task :lib:snygg:generateDebugResources UP-TO-DATE
> Task :lib:android:packageDebugResources UP-TO-DATE
> Task :lib:android:extractDeepLinksDebug UP-TO-DATE
> Task :lib:native:packageDebugResources UP-TO-DATE
> Task :lib:android:processDebugManifest UP-TO-DATE
> Task :lib:snygg:packageDebugResources UP-TO-DATE
> Task :lib:native:extractDeepLinksDebug UP-TO-DATE
> Task :lib:android:compileDebugLibraryResources UP-TO-DATE
> Task :lib:snygg:extractDeepLinksDebug UP-TO-DATE
> Task :lib:native:processDebugManifest UP-TO-DATE
> Task :lib:snygg:processDebugManifest UP-TO-DATE
> Task :lib:android:parseDebugLocalResources UP-TO-DATE
> Task :lib:snygg:compileDebugLibraryResources UP-TO-DATE
> Task :lib:native:compileDebugLibraryResources UP-TO-DATE
> Task :lib:android:generateDebugRFile UP-TO-DATE
> Task :lib:snygg:parseDebugLocalResources UP-TO-DATE
> Task :lib:android:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :lib:native:parseDebugLocalResources UP-TO-DATE
> Task :lib:android:javaPreCompileDebug UP-TO-DATE
> Task :lib:snygg:generateDebugRFile UP-TO-DATE
> Task :lib:snygg:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :lib:android:mergeDebugShaders UP-TO-DATE
> Task :lib:native:generateDebugRFile UP-TO-DATE
> Task :lib:native:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :lib:snygg:javaPreCompileDebug UP-TO-DATE
> Task :lib:android:compileDebugShaders NO-SOURCE
> Task :lib:snygg:mergeDebugShaders UP-TO-DATE
> Task :lib:android:generateDebugAssets UP-TO-DATE
> Task :lib:snygg:compileDebugShaders NO-SOURCE
> Task :lib:snygg:generateDebugAssets UP-TO-DATE
> Task :lib:android:packageDebugAssets UP-TO-DATE
> Task :lib:snygg:packageDebugAssets UP-TO-DATE
> Task :lib:android:mergeDebugJniLibFolders UP-TO-DATE
> Task :lib:snygg:mergeDebugJniLibFolders UP-TO-DATE
> Task :lib:android:mergeDebugNativeLibs NO-SOURCE
> Task :lib:snygg:mergeDebugNativeLibs NO-SOURCE
> Task :lib:android:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :lib:snygg:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :lib:android:stripDebugDebugSymbols NO-SOURCE
> Task :lib:snygg:stripDebugDebugSymbols NO-SOURCE
> Task :lib:android:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
> Task :lib:android:extractDeepLinksForAarDebug UP-TO-DATE
> Task :lib:snygg:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
> Task :lib:android:prepareDebugArtProfile UP-TO-DATE
> Task :lib:snygg:extractDeepLinksForAarDebug UP-TO-DATE
> Task :lib:android:prepareLintJarForPublish UP-TO-DATE
> Task :lib:snygg:prepareDebugArtProfile UP-TO-DATE
> Task :lib:snygg:prepareLintJarForPublish UP-TO-DATE
> Task :lib:native:compileDebugKotlin UP-TO-DATE
> Task :lib:native:javaPreCompileDebug UP-TO-DATE
> Task :lib:kotlin:compileKotlin UP-TO-DATE
> Task :lib:native:compileDebugJavaWithJavac NO-SOURCE
> Task :lib:native:bundleLibCompileToJarDebug UP-TO-DATE
> Task :lib:kotlin:compileJava NO-SOURCE
> Task :lib:native:mergeDebugShaders UP-TO-DATE
> Task :lib:kotlin:processResources NO-SOURCE
> Task :lib:kotlin:classes UP-TO-DATE
> Task :lib:native:compileDebugShaders NO-SOURCE
> Task :lib:native:generateDebugAssets UP-TO-DATE
> Task :lib:native:packageDebugAssets UP-TO-DATE
> Task :lib:kotlin:jar UP-TO-DATE
> Task :lib:native:processDebugJavaRes UP-TO-DATE
> Task :lib:native:bundleLibRuntimeToDirDebug UP-TO-DATE

> Task :lib:native:configureCMakeDebug[arm64-v8a] FAILED
C/C++: /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake[1]: syntax error: unexpected ')'

> Task :lib:android:compileDebugKotlin UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:native:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /data/data/com.termux/files/home/testing/florisboard/lib/native/src/main/rust/CMakeLists.txt: C++ build system [configure] failed while executing:
      /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake \
        -H/data/data/com.termux/files/home/testing/florisboard/lib/native/src/main/rust \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=24 \
        -DANDROID_PLATFORM=android-24 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 \
        -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 \
        -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/data/data/com.termux/files/home/testing/florisboard/lib/native/.cxx/Debug/4jiy2d3k/arm64-v8a \
        -GNinja \
        -DCMAKE_ANDROID_API=24
    from /data/data/com.termux/files/home/testing/florisboard/lib/native
  /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake[1]: syntax error: unexpected ')' : com.android.ide.common.process.ProcessException: C++ build system [configure] failed while executing:
      /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake \
        -H/data/data/com.termux/files/home/testing/florisboard/lib/native/src/main/rust \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=24 \
        -DANDROID_PLATFORM=android-24 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 \
        -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 \
        -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/data/data/com.termux/files/home/testing/florisboard/lib/native/.cxx/Debug/4jiy2d3k/arm64-v8a \
        -GNinja \
        -DCMAKE_ANDROID_API=24
    from /data/data/com.termux/files/home/testing/florisboard/lib/native
  /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake[1]: syntax error: unexpected ')'
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:288)
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:108)
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:106)
  	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess(ExecuteProcess.kt:106)
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess$default(ExecuteProcess.kt:85)
  	at com.android.build.gradle.tasks.CmakeQueryMetadataGenerator.executeProcess(CmakeFileApiMetadataGenerator.kt:59)
  	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
  	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
  	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
  	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configureOneAbi(ExternalNativeJsonGenerator.kt:247)
  	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configure(ExternalNativeJsonGenerator.kt:113)
  	at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.doTaskAction(ExternalNativeBuildJsonTask.kt:90)
  	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:65)
  	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
  	at com.android.build.gradle.internal.tasks.UnsafeOutputsTask.taskAction(UnsafeOutputsTask.kt:63)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
  	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
  	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
  	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
  	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
  	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
  	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
  	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
  	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
  	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
  	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
  	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
  	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
  	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
  	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
  	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:67)
  	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:45)
  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
  	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
  	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
  	at org.gradle.internal.Either$Right.fold(Either.java:175)
  	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
  	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
  	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:76)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:54)
  	at java.base/java.util.Optional.orElseGet(Optional.java:364)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
  	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
  	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
  	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
  	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
  	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
  	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
  	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
  	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
  	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
  	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
  	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
  	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
  	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
  	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
  	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
  	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
  	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
  	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
  	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
  	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
  	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
  	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
  	at java.base/java.util.Optional.orElseGet(Optional.java:364)
  	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
  	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
  	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
  	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
  	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
  	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
  	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
  	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
  	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: com.android.ide.common.process.ProcessException: Error while executing process /data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake with arguments {-H/data/data/com.termux/files/home/testing/florisboard/lib/native/src/main/rust -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=24 -DANDROID_PLATFORM=android-24 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125 -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/home/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/testing/florisboard/lib/native/build/intermediates/cxx/Debug/4jiy2d3k/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/data/data/com.termux/files/home/testing/florisboard/lib/native/.cxx/Debug/4jiy2d3k/arm64-v8a -GNinja -DCMAKE_ANDROID_API=24}
  	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
  	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
  	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:277)
  	... 144 more
  Caused by: org.gradle.process.internal.ExecException: Process 'command '/data/data/com.termux/files/home/Android/sdk/cmake/3.22.1/bin/cmake'' finished with non-zero exit value 1
  	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
  	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
  	... 145 more

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
58 actionable tasks: 1 executed, 57 up-to-date

**Comment by patrickgold** [comment]
Hi,

you seem to be trying to build FlorisBoard inside Termux on an Android device, which is not officially supported and thus no support can be given, I am sorry. Closing thus.
