### ISSUE TITLE
FlorisBoard stopped working in android 15 private space

### ISSUE THREAD

**Issue by secretmango** [florisboard/florisboard#2693]
### Short description

No idea, just "florisboard stopped working"

Opened the "private space" (grapheneOS android 15) where it is set as default keyboard

### Steps to reproduce

1. Install in private space via obtainium
2. Set it as keyboard
3. Close private space
4. Open private space
5. Repeat x times
6. Wait until you see a unicorn around the corner
7. It crashes

#### Environment information
- FlorisBoard [0.4.3](https://github.com/florisboard/florisboard/releases/v0.4.3) (101)
- Device: Google Pixel 6a (bluejay)
- Android: 15 (cn=VANILLA_ICE_CREAM sdk=35)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-11-17T22:32:33.475201Z
Manufacturer        : Google
Model               : Pixel 6a
Product             : bluejay
Android             : 15 (cn=VANILLA_ICE_CREAM sdk=35) [2024110700]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4,87 GiB (89,01% used, 5,47 GiB max)
Font scale          : 1.0
Locales             : de-DE,en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.4.3 (101)
Build type          : release
Build commit hash   : ff011209252c6b417695aee3872f70ef23af1a07
Java heap memory    : 24,24 MiB (9,47% used, 256,00 MiB max)
Native heap memory  : 9,76 MiB (44,30% used, 22,02 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : false
Glide enabled               : false
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1731882749555.stacktrace</summary>

```
java.lang.ArithmeticException: divide by zero
	at dev.patrickgold.florisboard.lib.compose.FlorisStaggeredVerticalGridKt$FlorisStaggeredVerticalGrid$1$1.measure-3p2s80s(SourceFile:46)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.OffsetKt.measure(SourceFile:2)
	at androidx.compose.foundation.layout.ColumnMeasurePolicy.measure-3p2s80s(SourceFile:46)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.ScrollingLayoutNode.measure-3p2s80s(SourceFile:44)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(SourceFile:115)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(SourceFile:85)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(SourceFile:117)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.OffsetKt.measure(SourceFile:2)
	at androidx.compose.foundation.layout.ColumnMeasurePolicy.measure-3p2s80s(SourceFile:46)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(SourceFile:117)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(SourceFile:85)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.OffsetKt.measure(SourceFile:6)
	at androidx.compose.foundation.layout.RowMeasurePolicy.measure-3p2s80s(SourceFile:46)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(SourceFile:33)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(SourceFile:85)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(SourceFile:115)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.foundation.layout.OffsetKt.measure(SourceFile:2)
	at androidx.compose.foundation.layout.ColumnMeasurePolicy.measure-3p2s80s(SourceFile:46)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:15)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:91)
	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(SourceFile:39)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.navigation.NavDestination$route$3.invoke(SourceFile:364)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:136)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:132)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(SourceFile:17)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(SourceFile:3)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(SourceFile:23)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(SourceFile:66)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:121)
	at android.view.View.measure(View.java:28122)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(Unknown Source:63)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:719)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4823)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3959)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:902)

```
</details>

**Comment by lm41** [comment]
Does it still occur in the latest version? Can you also test on GOS 16?
