### ISSUE TITLE
error

### ISSUE THREAD

**Issue by spngeb** [florisboard/florisboard#2694]
### Short description

Error

### Steps to reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard [0.4.3](https://github.com/florisboard/florisboard/releases/v0.4.3) (101)
- Device: Realme RMX3031 (RMX3031)
- Android: 12 (cn=S sdk=31)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-11-18T06:28:14.350453Z
Manufacturer        : realme
Model               : RMX3031
Product             : RMX3031
Android             : 12 (cn=S sdk=31) [RMX3031_11_C.17]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.27 GiB (58.21% used, 7.33 GiB max)
Font scale          : 0.9
Locales             : en-MM,ml-MM,hi-MM

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.4.3 (101)
Build type          : release
Build commit hash   : null
Java heap memory    : 8.28 MiB (2.16% used, 384.00 MiB max)
Native heap memory  : 12.20 MiB (60.98% used, 20.00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1731911291583.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.left' on a null object reference in method 'android.graphics.Point android.widget.Magnifier.getPosition()'
	at android.widget.Magnifier.getPosition(Magnifier.java:594)
	at android.widget.Editor$HandleView.updateHandlesVisibility(Editor.java:5350)
	at android.widget.Editor$HandleView.updateMagnifier(Editor.java:5413)
	at android.widget.Editor$SelectionHandleView.onTouchEvent(Editor.java:6127)
	at android.view.View.dispatchTouchEvent(View.java:14668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2573)
	at android.view.View.dispatchPointerEvent(View.java:14940)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6932)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6703)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6168)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6230)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6191)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6365)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6199)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6422)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6230)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6191)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6199)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6172)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9301)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9241)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9192)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9455)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```
</details>

**Comment by lm41** [comment]
This is a very weird bug I've never encountered. Can you provide more information on how to reproduce this bug?
