### ISSUE TITLE
"Program stop working" after trying to copy image

### ISSUE THREAD

**Issue by MaSHiNiK** [florisboard/florisboard#2714]
### Short description

The crash sometimes happens when I copy an image after taking a screenshot with screenshot assistant (not sure if it has anything to do with it). The last time this happened, my selection stopped working and all applications crashed after trying to select something (only rebooting the device helped).

### Steps to reproduce

1. Make screenshot through "[Screenshot assistant](https://github.com/beatbrot/ScreenshotAssistant)"
![Screenshot_20241210_133815_de beatbrot screenshotassistant](https://github.com/user-attachments/assets/02852911-4256-44fa-af88-3ef8d68c89ea)
2. Share image to "[Share to Clipboard](https://github.com/tengusw/share_to_clipboard)"
![RImage_Screenshot_20241210_133822_com huawei android internal app](https://github.com/user-attachments/assets/fb6f8882-83df-4ddd-a8ac-901f12f17d0e)
3. See crash (not every time)
![Screenshot-2024-12-10-13-39-16](https://github.com/user-attachments/assets/ca2129db-459b-4fb0-b917-e06f6894462d)

#### Environment information
- FlorisBoard [0.4.3](https://github.com/florisboard/florisboard/releases/v0.4.3) (101)
- Device: HUAWEI FIG-LX1 (FIG-LX1)
- Android: 9 (cn=P sdk=28)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-12-10T11:14:29.125Z
Manufacturer        : HUAWEI
Model               : FIG-LX1
Product             : FIG-LX1
Android             : 9 (cn=P sdk=28) [FIG-LX1 9.1.0.215(C10E8R1P5)]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 1,73 GiB (63,84% used, 2,71 GiB max)
Font scale          : 1.15
Locales             : uk-UA,en-UA

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.4.3 (101)
Build type          : release
Build commit hash   : null
Java heap memory    : 12,59 MiB (3,28% used, 384,00 MiB max)
Native heap memory  : 10,60 MiB (75,71% used, 14,00 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1733499841496.stacktrace</summary>

```
java.lang.SecurityException: UID 10366 does not have permission to content://com.caydey.ffshare.fileprovider/shared_media/02051472-72a1-48ab-b93b-1466a48de375/37eaec4c-55e9-4e1b-9891-2eae8ea1cca3.jpg [user 0]
	at android.os.Parcel.createException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1927)
	at android.os.Parcel.readException(Parcel.java:1877)
	at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:223)
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:149)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardManager.onPrimaryClipChanged(SourceFile:43)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:255)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.checkGrantUriPermissionLocked(ActivityManagerService.java:11019)
	at com.android.server.am.ActivityManagerService.grantUriPermissionLocked(ActivityManagerService.java:11085)
	at com.android.server.am.ActivityManagerService.grantUriPermissionFromOwner(ActivityManagerService.java:11523)
	at com.android.server.clipboard.ClipboardService.grantUriLocked(ClipboardService.java:615)
	at com.android.server.clipboard.ClipboardService.grantItemLocked(ClipboardService.java:630)


```
</details>

<details>
<summary>1733829264152.stacktrace</summary>

```
java.lang.SecurityException: UID 10366 does not have permission to content://com.caydey.ffshare.fileprovider/shared_media/505ac5d6-12e3-4d9b-825b-1c76295dc302/3cb7b6dc-6528-4483-83c6-77591b47f1ba.jpg [user 0]
	at android.os.Parcel.createException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1927)
	at android.os.Parcel.readException(Parcel.java:1877)
	at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:223)
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:149)
	at dev.patrickgold.florisboard.ime.clipboard.ClipboardManager.onPrimaryClipChanged(SourceFile:43)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:255)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.checkGrantUriPermissionLocked(ActivityManagerService.java:11019)
	at com.android.server.am.ActivityManagerService.grantUriPermissionLocked(ActivityManagerService.java:11085)
	at com.android.server.am.ActivityManagerService.grantUriPermissionFromOwner(ActivityManagerService.java:11523)
	at com.android.server.clipboard.ClipboardService.grantUriLocked(ClipboardService.java:615)
	at com.android.server.clipboard.ClipboardService.grantItemLocked(ClipboardService.java:630)


```
</details>

**Comment by lm41** [comment]
Is there a reason why you do not use the 'Share image to clipboard' feature of FlorisBoard directly?

**Comment by MaSHiNiK** [comment]
> Is there a reason why you do not use the 'Share image to clipboard' feature of FlorisBoard directly?

I didn't know this feature existed

**Comment by lm41** [comment]
> > Is there a reason why you do not use the 'Share image to clipboard' feature of FlorisBoard directly?
> 
> I didn't know this feature existed

So is your issue fixed now with this feature?

**Comment by MaSHiNiK** [comment]
> > > Is there a reason why you do not use the 'Share image to clipboard' feature of FlorisBoard directly?
> > 
> > 
> > I didn't know this feature existed
> 
> So is your issue fixed now with this feature?

Everything works fine with it, but there's a possibility that I might accidentally copy an image using the old method or in other applications, which causes the selection menu to break and the applications to crash again. So, I'm not sure if this issue can be considered fully fixed.

Here's a similar [issue](https://github.com/tchapgouv/tchap-android/issues/642)

**Comment by lm41** [comment]
Related https://stackoverflow.com/a/43644521/18227323

**Comment by lm41** [comment]
@MaSHiNiK What do you mean with `the same problem with text selection happened`?

**Comment by lm41** [comment]
I consider the image copy problem fixed. Please open a new issue if the text selection problem is still there.
