### ISSUE TITLE
Can't launch the keyboard

### ISSUE THREAD

**Issue by ganderwa** [florisboard/florisboard#304]
When I try to launch the keyboard it crashes. Gboard works perfectly fine but Florisboard doesn't.
Here is the logs

``
~~~ 1612303355640.stacktrace ~~~

com.squareup.moshi.JsonDataException: java.lang.IllegalArgumentException: No enum constant dev.patrickgold.florisboard.ime.text.key.KeyVariation.EMAİL_ADDRESS at $.arrangement[1][1].variation
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:94)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:43)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:70)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:52)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.mergeLayoutsAsync(LayoutManager.kt:123)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.computeLayoutFor(LayoutManager.kt:310)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$preloadComputedLayout$1.invokeSuspend(LayoutManager.kt:377)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: No enum constant dev.patrickgold.florisboard.ime.text.key.KeyVariation.EMAİL_ADDRESS
	at java.lang.Enum.valueOf(Enum.java:257)
	at dev.patrickgold.florisboard.ime.text.key.KeyVariation.valueOf(Unknown Source:2)
	at dev.patrickgold.florisboard.ime.text.key.KeyVariation$Companion.fromString(KeyVariation.kt:32)
	at dev.patrickgold.florisboard.ime.text.key.KeyVariationAdapter.fromJson(KeyVariation.kt:40)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
	at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:257)
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:90)
	... 22 more

``

**Comment by patrickgold** [comment]
Which version are you on? If you are still on v0.3.5, this is a well known issue for some languages, specifically though Turkish devices. In v0.3.6, this should be fixed.

**Comment by ganderwa** [comment]
> Which version are you on? If you are still on v0.3.5, this is a well known issue for some languages, specifically though Turkish devices. In v0.3.6, this should be fixed.

I am on v0.3.5, and there doesn't seem to be any avaible updates on the FDroid store. And yes I am on a Turkish device. Is there any way to resolve this?

**Comment by patrickgold** [comment]
> I am on v0.3.5, and there doesn't seem to be any avaible updates on the FDroid store. And yes I am on a Turkish device. Is there any way to resolve this?

F-Droid automatically builds and releases FlorisBoard in a periodic interval. When exactly this happens cannot be influenced by me, though I think the update for v0.3.6 should arrive until Friday. There's not really a workaround for this, except setting the device system language to English or any language where the capitalized letters match the English variant (I wouldn't recommend this though).

**Comment by ganderwa** [comment]
> > I am on v0.3.5, and there doesn't seem to be any avaible updates on the FDroid store. And yes I am on a Turkish device. Is there any way to resolve this?
> 
> F-Droid automatically builds and releases FlorisBoard in a periodic interval. When exactly this happens cannot be influenced by me, though I think the update for v0.3.6 should arrive until Friday. There's not really a workaround for this, except setting the device system language to English or any language where the capitalized letters match the English variant (I wouldn't recommend this though).

Thank you for the fast reply. I've downloaded the apk file for v0.3.6 from the Github page and it works great!

**Comment by patrickgold** [comment]
> Thank you for the fast reply. I've downloaded the apk file for v0.3.6 from the Github page and it works great!

Cool thanks for letting me know! Closing this issue as this issue is resolved now.
