### ISSUE TITLE
Crash on setup when no other IME is installed

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#423]
#### Short description
App crashes on setup when no other IME is installed. This can be tested by installing it into [Shelter](https://f-droid.org/en/packages/net.typeblog.shelter/)

#### Steps to reproduce
1. Have no other IME installed
2. Install Shelter
3. Tap on install APK into Shelter
4. Select FlorisBoard APK and install
5. Launch FlorisBoard
6. See error

#### Screen recording

https://user-images.githubusercontent.com/24937357/109780594-72594380-7c07-11eb-8b57-a727a7c544c3.mp4

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: GitHub
- Device: OnePlus 8T
- Android version, ROM: 11, Paranoid Android Ruby Beta 4

I don't have any IMEs other than FlorisBoard installed since I removed Gboard via Magisk Debloater module after installing FlorisBoard (before creating the work profile). I think that's  the problem because installing and enabling any other IME in the work profile and then launching FlorisBoard fixes it.

```
~~~ 1614758721583.stacktrace ~~~

java.lang.NullPointerException: activeImeIds must not be null
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.checkIfImeIsEnabled(FlorisBoard.kt:126)
	at dev.patrickgold.florisboard.setup.EnableImeFragment.onResume(EnableImeFragment.kt:50)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(FragmentStateAdapter.java:726)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer$1.onPageScrollStateChanged(FragmentStateAdapter.java:632)
	at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
	at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
	at androidx.viewpager2.widget.ScrollEventAdapter.dispatchStateChanged(ScrollEventAdapter.java:426)
	at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:214)
	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:807)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by patrickgold** [comment]
Good find! I've never tried out to install FlroisBoard when there were no other IMEs installed and it seems that the returned ID list is null if no other IMEs are enabled, which crashes FlroisBoard. Placing on my todo list.

**Comment by patrickgold** [comment]
Above commit fixes the crash if no other IME is present. Will be included in the next release v0.3.9!

**Comment by IveMalfunctioned** [comment]
what is an IME and how should I install one?

**Comment by tsiflimagas** [comment]
@IveMalfunctioned I don't think an over a year old issue is the best place to ask, especially such a generic question. But since the question has been made, a quick search could have given you some useful [information](https://developer.android.com/guide/topics/text/creating-input-method#:~:text=An%20input%20method%20editor%20(IME,keyboards%20or%20even%20speech%20input.).

**Comment by IveMalfunctioned** [comment]
yes, it's as good as any other thread, because it sends you notifications. I never understood why you people are so picky about stuff like that.
And sorry but that's not a quick search, I did a quick search and found nothing. All I'm trying to do is make voice input work with Floris

**Comment by tsiflimagas** [comment]
> yes, it's as good as any other thread, because it sends you notifications

So, whatever is convenient to you, is proper? I don't think things work like that.

> why you people are so picky about stuff like that

We, people, usually have our reasons to be picky about certain stuff. There's a discussions page which GitHub offers and is enabled in FlorisBoard repo, which is much more suitable. Or you can open a new issue, if you're not familiar with that.

> Anybody who comes across this thread in the future wondering the same thing that's related will have their question answered if solved.

That's my point, this thread was opened for a different purpose. People with the same question as yours, won't come here to get an answer. My sentence was an advice, not a scrutinization ;)
Anyway, to the subject

> All I'm trying to do is make voice input work with Floris

That's different from what you initially asked. In the page I linked, which was the first result when I searched "Android ime", there's a prompt definition of what an ime is. What you want is a voice **I**nput **M**ethod **E**ditor, since currently FlorisBoard doesn't have it's own voice input implementation. The [pull request](https://github.com/florisboard/florisboard/pull/1587) which added this feature has the information and links for voice ime's you'll need (you can also use Google Speech Services). Also a hint: if you install a voice ime and you can't see the microphone icon, make FlorisBoard shorter in settings, because icons can get pushed out of the tool bar, the higher you make the keyboard.

**Comment by IveMalfunctioned** [comment]
Sick. Thanks.
