### ISSUE TITLE
app crashed 

### ISSUE THREAD

**Issue by ash23090** [florisboard/florisboard#439]
~~~ 1614970093999.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 0 free bytes and 0B until OOM, target footprint 201326592, growth limit 201326592
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load(Flictionary.kt:147)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary(DictionaryManager.kt:57)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1$1.invokeSuspend(TextInputManager.kt:313)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Which version of the app do you use and what did you do before this happened?

**Comment by patrickgold** [comment]
> Which version of the app do you use and what did you do before this happened?

Not OP but based on the log it is 100% v0.3.8 and has something to do with the suggestion dictionary load. I am aware of all sorts of issues around internal memory management and most of the time it is the fault of my not-so-efficient internal memory management (although I am constantly improving on that).

**Comment by ash23090** [comment]
the version was 0.38 and as far as I remember I restarted the phone and when I entered some app to type it crashed

**Comment by patrickgold** [comment]
OutOfMemory errors are now handled in #677, please follow that thread for more info.
