### ISSUE TITLE
Got this log notification after restarting device

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#440]
~~~ 1615020692267.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load(Flictionary.kt:140)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary(DictionaryManager.kt:57)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1$1.invokeSuspend(TextInputManager.kt:313)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1615020692261.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.Daemons$FinalizerWatchdogDaemon.finalizerTimedOut(Daemons.java:445)
	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)

**Comment by patrickgold** [comment]
Like I stated in the release notes, the suggestion stuff is highly experimental and OOM errors like this one are likely to occur. The next versions will address these and improve internal memory management.

**Comment by shockergit** [comment]
Ok but app havent crashed yet i just rebooted and this notification just poped up.

**Comment by patrickgold** [comment]
FlorisBoard crashed once while preparing in the background (and you got this notification) but then was able to recover and start correctly in the second attempt.

**Comment by shockergit** [comment]
Oh ok👍
