### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by TheThunderspy** [florisboard/florisboard#449]
Here I leave the log:
~~~ 1615333941974.stacktrace ~~~

java.lang.IllegalArgumentException: 'hint' has a constructor parameter of type T? but a property of type T?.
for dev.patrickgold.florisboard.ime.popup.PopupSet<dev.patrickgold.florisboard.ime.text.key.KeyData> popup
for class dev.patrickgold.florisboard.ime.text.key.FlorisKeyData
for java.util.List<dev.patrickgold.florisboard.ime.text.key.FlorisKeyData>
for java.util.List<java.util.List<dev.patrickgold.florisboard.ime.text.key.FlorisKeyData>> arrangement
for class dev.patrickgold.florisboard.ime.text.layout.LayoutData
	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:349)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:150)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:254)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:254)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:69)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:52)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.mergeLayoutsAsync(LayoutManager.kt:117)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.computeLayoutFor(LayoutManager.kt:310)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$preloadComputedLayout$1.invokeSuspend(LayoutManager.kt:377)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: 'hint' has a constructor parameter of type T? but a property of type T?.
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:235)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	... 27 more

Unfortunatly I don't have the resources to know the "27 more"

**Comment by patrickgold** [comment]
Thanks for your report! Looking at your log I have no clue why this only happens at your device. I will investigate into this.

**Comment by TheThunderspy** [comment]
Sorry if I'm late, this happened after already some time now, and I can't reproduce it.
I just remember that ussually happened when opening the brave browser after a reboot, for a moment I though that it was a visual glitch, but I am not sure, the only thing that now I can say is that my device is kinda broken Bitel B9505 Nougat 7.0 (sdk 24) with SystemUITuner and other stuff that don't matter.
I formated and locked the bootloader, and after to that the issue is not reproducible.
Thank you for your support

**Comment by TheThunderspy** [comment]
Older version of florisboard, I couldn't replicate. Closing.....!
