### ISSUE TITLE
Bug report - keyboard abruply disappeared and received a notification that keyboard has stopped working

### ISSUE THREAD

**Issue by gitanonaddy** [florisboard/florisboard#499]
~~~ 1616729773861.stacktrace ~~~

java.lang.StringIndexOutOfBoundsException: String index out of range: 68
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:952)
	at java.lang.StringBuilder.substring(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.deleteWordsBeforeCursor(EditorInstance.kt:233)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.handleDeleteWord(TextInputManager.kt:468)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:704)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$3.invokeSuspend(InputEventDispatcher.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Glitchy-Tozier** [comment]
App Version? Did you do anything specific?

**Comment by gitanonaddy** [comment]
- Device - S7 edge
- Bug Occurance - everytime the keyboard launches and swipe gesture is used before typing anything. (When the very first action is swipe action after launch)
- Apps - bug occurs on all apps 
- Version - 0.3.9

**Comment by patrickgold** [comment]
This bug is already known (#484) and a potential fix is in master, but not yet released in the beta track. Closing this issue as it is a  duplicate.
