### ISSUE TITLE
"Floris Board has stopped working" banner when i use a "Swipe" gesture on the keyboard, but only if i haven't pressed any buttons on the keyboard before that. 

### ISSUE THREAD

**Issue by Stenledtrap** [florisboard/florisboard#555]
#### Short description
Describe the bug in a short but concise way.
When i press on anything to start typing and try to delete a word with a "Swipe to the left gesture" it does the error message banner, but if i press any key and then "Swipe" again it works.

#### Environment information
- FlorisBoard Version: 
Version 0.3.9
- Install Source: 
F-Droid
- Device: 
Huawei Y6P
- Android version, ROM: 

![Screenshot_20210402_111711.jpg](https://user-images.githubusercontent.com/80212582/113396994-ff57ff80-9361-11eb-8108-9af8840ebb6b.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report! If you click on that notification and vie the crash log, does it look similar to #484?

**Comment by Stenledtrap** [comment]
> Thanks for your bug report! If you click on that notification and vie the crash log, does it look similar to #484?

- It is exactly like this here.

~~~ 1617531588503.stacktrace ~~~

java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.deleteWordsBeforeCursor(EditorInstance.kt:233)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.handleDeleteWord(TextInputManager.kt:468)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:704)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$3.invokeSuspend(InputEventDispatcher.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
~~~ 1617351415224.stacktrace ~~~

java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.deleteWordsBeforeCursor(EditorInstance.kt:233)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.handleDeleteWord(TextInputManager.kt:468)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:704)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$3.invokeSuspend(InputEventDispatcher.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by patrickgold** [comment]
This crash should be prevented in the latest version v0.3.10. Closing this issue though.
