### ISSUE TITLE
Java out of memory crash

### ISSUE THREAD

**Issue by IronVeil** [florisboard/florisboard#569]
#### Short description
The keyboard started slowing down and lagging, and then it crashed with a Java 
OOM error. Log at the bottom

### Steps to reproduce
No clue i was talking to someone on snapchat

#### Environment information
- FlorisBoard Version: v0.3.10-beta04
- Install Source: F-Droid beta
- Device: Samsung S20 FE 5G
- Android version, ROM: 11 OneUI 3.1

~~~ 1617532067794.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 960624 free bytes and 938KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 52166656 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:162)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:253)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:353)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by hbarsaiyan** [comment]
Same for me. After a while keyboard starts to lag very much that i am unable to type. I am using v0.3.10-beta05 on Lenovo Tab4 X304L running Lineage OS 16.

**Comment by patrickgold** [comment]
This crash is known due to the current memory management of suggestions. As a workaround you could disable those suggestions, which should prevent this OOM errors from happening.

**Comment by Glitchy-Tozier** [comment]
It's reproducible using the old method (I had swipe-typing and suggestions enabled, no idea whether this contributed anything):

> Okay, I can replicate it now.
> I just 
> 1. opened some app (Github) 
> 2. clicked on a text-field so that the keyboard was active
> 3. turned the screen back and forth 1-2 minutes.
> 
> It started loading long enough that I could notice the loading-screen, then it ltarted taking its time before even showing the loading-screen. Then the screen-rotations felt like they took longer and longer to start.
> Then FlorisBoard got stuck on the loading-screen for a few seconds, before crashing.
> 
> ((The log in my previous comment is not the log from this last reproduction-crash))

New Log:
~~~ 1618044420216.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1618044418947.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 1063768 free bytes and 1038KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 177209344 bytes)
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by kj7rrv** [comment]
Replicated on my Moto G Power 2020, running Android 10 (unrooted) and FlorisBoard v0.3.10-beta06.~~~ 1618112875392.stacktrace ~~~java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 16 free bytes and 16B until OOM, target footprint 201326592, growth limit 201326592	at dalvik.system.VMStack.getThreadStackTrace(Native Method)	at java.lang.Thread.getStackTrace(Thread.java:1720)	at java.lang.Daemons$Daemon.getStackTrace(Daemons.java:193)	at java.lang.Daemons$FinalizerWatchdogDaemon.finalizerTimedOut(Daemons.java:449)	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)	at java.lang.Daemons$Daemon.run(Daemons.java:137)	at java.lang.Thread.run(Thread.java:919)~~~ 1618113073376.stacktrace ~~~android.view.InflateException: Binary XML file line #56 in dev.patrickgold.florisboard.beta:layout/florisboard: Binary XML file line #20 in dev.patrickgold.florisboard.beta:layout/text_input_layout: Error inflating class <unknown>Caused by: android.view.InflateException: Binary XML file line #20 in dev.patrickgold.florisboard.beta:layout/text_input_layout: Error inflating class <unknown>Caused by: java.lang.reflect.InvocationTargetException	at java.lang.reflect.Constructor.newInstance0(Native Method)	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)	at android.view.LayoutInflater.createView(LayoutInflater.java:854)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onCreateInputView(FlorisBoard.kt:256)	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1507)	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:1935)	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1884)	at android.inputmethodservice.InputMethodService.resetStateForNewConfiguration(InputMethodService.java:1124)	at android.inputmethodservice.InputMethodService.onConfigurationChanged(InputMethodService.java:1105)	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onConfigurationChanged(FlorisBoard.kt:435)	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:5672)	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5872)	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5795)	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)	at android.os.Handler.dispatchMessage(Handler.java:107)	at android.os.Looper.loop(Looper.java:241)	at android.app.ActivityThread.main(ActivityThread.java:7617)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 8 free bytes and 8B until OOM, target footprint 201326592, growth limit 201326592	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:241)	at android.graphics.Paint.<init>(Paint.java:559)	at android.graphics.drawable.ShapeDrawable$ShapeState.<init>(ShapeDrawable.java:556)	at android.graphics.drawable.ShapeDrawable.<init>(ShapeDrawable.java:84)	at android.graphics.drawable.PaintDrawable.<init>(PaintDrawable.java:32)	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:41)	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:77)	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:76)	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:78)	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:104)	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:88)	... 39 moreOn Apr 10, 2021 01:55, Glitchy-Tozier ***@***.***> wrote:
It's reproducible using the old method (I had swipe-typing and suggestions enabled, no idea whether this contributed anything):

Okay, I can replicate it now.
I just
opened some app (Github)clicked on a text-field so that the keyboard was activeturned the screen back and forth 1-2 minutes.
It started loading long enough that I could notice the loading-screen, then it ltarted taking its time before even showing the loading-screen. Then the screen-rotations felt like they took longer and longer to start.
Then FlorisBoard got stuck on the loading-screen for a few seconds, before crashing.
((The log in my previous comment is not the log from this last reproduction-crash))

New Log:

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1618044418947.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 1063768 free bytes and 1038KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 177209344 bytes)
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Glitchy-Tozier** [comment]
This should be high up on the importance-list. It happens multiple times a day and is really annoying.
((LAGGGGGG))

**Comment by Flam3z** [comment]
Same issue happens to me.
Samsung S10, Android 11

**Comment by patrickgold** [comment]
Due to the enormous amount of duplicates OutOfMemory errors are now handled in #677, please follow that thread for more info.
