### ISSUE TITLE
crash upon swiping left to delete last word

### ISSUE THREAD

**Issue by ProodjePindakaas** [florisboard/florisboard#592]
florisboard crashed when swiping left to delete the last word after hiding the keyboard by swiping down and then reopening the keyboard. The crash is reproducable by repeating these steps.

~~~ 1617900331008.stacktrace ~~~

java.lang.StringIndexOutOfBoundsException: String index out of range: 10
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:952)
	at java.lang.StringBuilder.substring(Unknown Source:0)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.deleteWordsBeforeCursor(EditorInstance.kt:233)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.handleDeleteWord(TextInputManager.kt:468)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:704)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$3.invokeSuspend(InputEventDispatcher.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by patrickgold** [comment]
Duplicate #484. Note that the precise word deletion in general is jank af, but v0.3.10 at least prevents crashes like this from occurring.
