### ISSUE TITLE
Florisboard crashing trying to choose a design

### ISSUE THREAD

**Issue by BrudiBanani** [florisboard/florisboard#593]
Hi,
I can reproduce this error anytime with following setup:
Android 11
FlorisBoard 0.3.10
Xiamoi Mi 9 SE
Steps to reproduce:
1.Open Settings 
2. Go to Design
3. either way in light or dark mode click on chosen design.

However i have installed both 0.3.10-beta06 & 0.3.10 and this bug only occurs when 0.3.10 is NOT activated in android keyboard settings.
When keyboard is activated this error does not happen.
This does not happen with 0.3.10-beta06
~~~ 1617951622746.stacktrace ~~~

java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.patrickgold.florisboard/dev.patrickgold.florisboard.settings.ThemeManagerActivity}: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:101)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:95)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:159)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:52)
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.onCreate(FlorisActivity.kt:52)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreate(ThemeManagerActivity.kt:124)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$Companion.getInstance(GlideTypingManager.kt:32)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:88)
	... 38 more

**Comment by BrudiBanani** [comment]
I need to correct myself:
after some activation & deactivation cycles can't reproduce this bug anymore

**Comment by patrickgold** [comment]
Thanks for your bug report! Thanks to the provided log I know the source of the crash and is 100% reproducible both in the stable and beta version. Just to make sure you launch the Settings while the IME service for FlorisBoard is not yet started and voilá - this crash occurs. The reason is that the null safely for retrieving a manager instance is not respected, which results in this crash.

**Comment by X-yl** [comment]
Huh, so the KeyboardView can be initialised before the IME service even starts? TIL. Do you want me to take care of this one? I think a similar issue occurs with the clipboard manager class as well.

**Comment by patrickgold** [comment]
> Huh, so the KeyboardView can be initialised before the IME service even starts? TIL. Do you want me to take care of this one? I think a similar issue occurs with the clipboard manager class as well.

The keyboard view is normally null save so it can be instantiated before the service runs, but I think some `FlorisBoard.default()!!` lines or similar sneaked in causing the crashes when the service is not yet started. If you want you can take care of this bug :)
