### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sammysudo** [florisboard/florisboard#628]
~~~ 1618242533685.stacktrace ~~~

android.os.BadParcelableException: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.Parcel.createException(Parcel.java:2073)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1689)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1189)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:322)
	at android.content.ContentResolver.insert(ContentResolver.java:1831)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:251)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by patrickgold** [comment]
Thanks for your bug report! Could you please provide more info on some steps to reproduce and which version this crash occurred?
