### ISSUE TITLE
Crash While Glide typing

### ISSUE THREAD

**Issue by MathSteve22** [florisboard/florisboard#629]
Phone: Samsung S20 FE
Install: Fdroid, 0.3.10 Beta

Issue: Have had issue with Floris Board crashing (output below). So far it has occurred when glide typing, particularly in messaging apps (for me, signal and qksms) and while phone is vertical. I am able to click on input box to pull back up the keyboard after it crashes. It is not overly consistent (1-2 times per day) so I'm not sure how able to replicate it is.

~~~ 1617737298458.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 1336 byte allocation with 2248552 free bytes and 2195KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 40108032 bytes)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invokeSuspend(EmojiKeyboardView.kt:160)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView.buildLayoutForCategory(EmojiKeyboardView.kt:149)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2.invokeSuspend(EmojiKeyboardView.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618011816827.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2162520 free bytes and 2111KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 49545216 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:115)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:142)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:136)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:109)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords$default(FlorisLanguageModel.kt:93)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:259)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:372)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618011817996.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 11616 byte allocation with 1965480 free bytes and 1919KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 41156608 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:430)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.addEventListener(FlorisBoard.kt:812)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyView.onAttachedToWindow(EmojiKeyView.kt:73)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.widget.ViewAnimator.addView(ViewAnimator.java:193)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2$1.invokeSuspend(EmojiKeyboardView.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1618103751639.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1731992 free bytes and 1691KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 60030976 bytes)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1$1.invoke(GlideTypingManager.kt:81)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1$1.invoke(GlideTypingManager.kt:18)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:422)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618245149953.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2095224 free bytes and 2046KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 202637312 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at android.view.GestureExclusionTracker.updateRectsForView(GestureExclusionTracker.java:43)
	at android.view.ViewRootImpl.updateSystemGestureExclusionRectsForView(ViewRootImpl.java:5252)
	at android.view.View.updateSystemGestureExclusionRects(View.java:12221)
	at android.view.-$$Lambda$WlJa6OPA72p3gYtA3nVKC7Z1tGY.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by patrickgold** [comment]
Thanks for your bug report! Your stacktrace log includes probably all of the crash candidates in terms of memory FlorisBoard currently offers in one go, that's a new one. :)

One specific crash candidate has been fixed in #625, others are already known by the countless memory crash issues. Closing this issue as a duplicate.
