### ISSUE TITLE
Erro relatado

### ISSUE THREAD

**Issue by WalkerPt** [florisboard/florisboard#635]
~~~ 1618221521093.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 405312 free bytes and 395KB until OOM
	at java.util.HashMap.makeTable(HashMap.java:551)
	at java.util.HashMap.doubleCapacity(HashMap.java:570)
	at java.util.HashMap.put(HashMap.java:400)
	at org.json.JSONObject.put(JSONObject.java:264)
	at org.json.JSONTokener.readObject(JSONTokener.java:384)
	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
	at org.json.JSONObject.<init>(JSONObject.java:156)
	at org.json.JSONObject.<init>(JSONObject.java:173)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618221522323.stacktrace ~~~

kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.Default, Continuation at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt)@d6e29b8]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.getPrefs(FlorisActivity.kt:40)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.setThemeRefInPrefs(ThemeManagerActivity.kt:200)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.finish(ThemeManagerActivity.kt:175)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:394)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:193)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more
~~~ 1618221522399.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.getPrefs(FlorisActivity.kt:40)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.setThemeRefInPrefs(ThemeManagerActivity.kt:200)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.finish(ThemeManagerActivity.kt:175)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:394)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618221522451.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.getPrefs(FlorisActivity.kt:40)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.setThemeRefInPrefs(ThemeManagerActivity.kt:200)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.finish(ThemeManagerActivity.kt:175)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:394)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618223279764.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 961312 free bytes and 938KB until OOM; failed due to fragmentation (required continguous free 528384 bytes where largest contiguous free 135168 bytes)
	at java.util.HashMap.makeTable(HashMap.java:551)
	at java.util.HashMap.doubleCapacity(HashMap.java:570)
	at java.util.HashMap.put(HashMap.java:400)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi!  :)

Could cou please share app version and what you did at the time of the crash?

Filling out the bug teplate when posting a crash-log is incredibly helpful to the person fixing the bug.

**Comment by WalkerPt** [comment]
Hi

Version 0.3.10(35).

At the moment I was not doing anything, nor was I close to the tablet.  When I picked up the tablet again, I had an indication that it was closed due to an error.  Had activated, glide typing and show suggestions, (exprimental).  In the meantime, I disabled these functions and have been normal.

Great work.

Telmo.

13/04/2021 12:37:55 Glitchy-Tozier ***@***.***>:

**Comment by patrickgold** [comment]
There's a reason why suggestions are experimental, this being that the memory management isn't the greatest and the memory limit is hit quite frequently, causing the crashes. You did the best you could, temporarily disabling these so you can use FlorisBoard without it crashing. Suggestions will be rewritten from scratch and then hopefully the memory issues also are cleared.

**Comment by Glitchy-Tozier** [comment]
@patrickgold Btw, I'm pretty sure this OOM-Error can be reproduced even without suggestions (just turning the phone back and fourth.)
Maybe that's a different error though.

**Comment by patrickgold** [comment]
Due to the enormous amount of duplicates OutOfMemory errors are now handled in #677, please follow that thread for more info.

@Glitchy-Tozier During my investigation of battery and memory issues today I also found out that there's still too much garbage left when rotating the screen, so I've put it onto the list in #677.

**Comment by Glitchy-Tozier** [comment]
That's just great! Now you're taking away my favorite way, of making the app crash  😔
