### ISSUE TITLE
Error


### ISSUE THREAD

**Issue by Reware53** [florisboard/florisboard#639]
~~~ 1618265926541.stacktrace ~~~

android.view.InflateException: Binary XML file line #56 in dev.patrickgold.florisboard:layout/florisboard: Binary XML file line #20 in dev.patrickgold.florisboard:layout/text_input_layout: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #20 in dev.patrickgold.florisboard:layout/text_input_layout: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onCreateInputView(FlorisBoard.kt:256)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2302)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2878)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2807)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:880)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:241)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1747192 free bytes and 1706KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 38797312 bytes)
	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:244)
	at android.graphics.Paint.<init>(Paint.java:576)
	at android.graphics.drawable.ShapeDrawable$ShapeState.<init>(ShapeDrawable.java:556)
	at android.graphics.drawable.ShapeDrawable.<init>(ShapeDrawable.java:84)
	at android.graphics.drawable.PaintDrawable.<init>(PaintDrawable.java:32)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:84)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:104)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:88)
	... 33 more

**Comment by Glitchy-Tozier** [comment]
Hi!  :)

Could cou please share app version and what you did at the time of the crash?

Filling out the bug teplate when posting a crash-log is incredibly helpful to the person fixing the bug.

**Comment by Reware53** [comment]
> Hi!  :)
> 
> Could cou please share app version and what you did at the time of the crash?
> 
> Filling out the bug teplate when posting a crash-log is incredibly helpful to the person fixing the bug.


**v0.3.10**
I don't remember exactly what I had done I had copied and pasted something that did it

**Comment by patrickgold** [comment]
Thanks for your bug report! OutOfMemory errors are now handled in #677, please follow that thread for more info.
