### ISSUE TITLE
Latest version slow and buggy

### ISSUE THREAD

**Issue by morta5** [florisboard/florisboard#650]
FlorisBoard just closed. Here is the log:

~~~ 1613630382149.stacktrace ~~~

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.containsKey(HashMap.java:595)
	at java.util.HashSet.contains(HashSet.java:203)
	at com.squareup.moshi.internal.Util.resolve(Util.java:185)
	at com.squareup.moshi.internal.Util.resolve(Util.java:176)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:253)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:254)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:254)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:69)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout(LayoutManager.kt:52)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.mergeLayoutsAsync(LayoutManager.kt:117)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.computeLayoutFor(LayoutManager.kt:310)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$preloadComputedLayout$1.invokeSuspend(LayoutManager.kt:377)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618330488153.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available

**Comment by p0wl90** [comment]
I can confirm that 0.3.10 is crazily slow on a Pixel 3a. After opening up, it does not react to input for about 1-5 seconds. Sometimes it processes all of the taps after that duration. But sometimes it does not.

**Comment by patrickgold** [comment]
Thanks for your bug report! I am aware of this issue and memory errors are now managed in #677. Please see that thread for more info.

**Comment by NSTAdventure** [comment]
@patrickgold 

For me this also happened on work profile
