### ISSUE TITLE
Switch windows crash

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#663]
Hey got a crash today. I minimized my browser and the keyboard stayed visible on the screen which meant I couldnt open my launcher. When I used the recent apps menu to switch back, the  keyboard crashed and provided this log.

~~~ 1608360023842.stacktrace ~~~

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8372)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4273)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:940)
	at android.view.View.setFlags(View.java:15732)
	at android.view.View.setVisibility(View.java:11372)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView.setActiveContainer(SmartbarView.kt:103)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarManager.updateActiveContainerVisibility(SmartbarManager.kt:241)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarManager.resetClipboardSuggestion(SmartbarManager.kt:194)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.sendKeyPress(TextInputManager.kt:569)
	at dev.patrickgold.florisboard.ime.text.key.KeyView$onFlorisTouchEvent$2.run(KeyView.kt:235)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
~~~ 1618379022487.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 509432 free bytes and 497KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by patrickgold** [comment]
Thanks for the bug report! I think only the bottom stacktrace is relevant, because the crash in the top stacktrace goes through classes which do not exist anymore in FlorisBoard (`SmartbarManager`). As for the below stacktrace, are you still on v0.3.10 or on v0.3.11-beta01? The beta01 version improves memory management in the glide typing manager, where the OOM error occurred.

**Comment by Kreuger** [comment]
Im still on 0.3.10. Havent been testing the betas recently but I guess I will switch. Does that imply that I was using the glide typing?

**Comment by patrickgold** [comment]
No, only that you've enabled glide typing. Note, that due to the enormous amount of duplicates I am bundling the OutOfMemory errors & discussion in #677, please follow that thread for more info.
