### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#664]
The app hangs sometimes, mostly when switching apps. This is the first time it crashed after hanging. 

~~~ 1618390965356.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 251688 free bytes and 245KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by MisterY** [comment]
This is without the word prediction.

**Comment by Glitchy-Tozier** [comment]
Pretty sure we can close this as a duplicate. It was reported several times already.

(Btw, you can reproduce the bug by rotating the device back and forth a couple of times)

**Comment by MisterY** [comment]
Yes, I think so. Since the app offers to submit it, people are just so kind to go ahead and contribute. ;)

**Comment by MisterY** [comment]
We should really pick one issue and link the duplicates so they can get closed.

**Comment by Glitchy-Tozier** [comment]
Yep :)

I myself am not sure what the main issue for this is, but Patrick knows for sure.
