### ISSUE TITLE
Florisboard was crashed

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [florisboard/florisboard#668]
~~~ 1618413722497.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 173480 byte allocation with 2606232 free bytes and 2545KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 36962304 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.onAttachedToWindow(PopupExtendedView.kt:92)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:80)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8462)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Glitchy-Tozier** [comment]
1. Hübscher Name  ;)
2. Thank you for the report! This Issue was already mentioned several times, so you can probably close this issue as it's a duplicate.

**Comment by mondlicht-und-sterne** [comment]
Zu 1. Danke. Das ist weil ich gern Mond und Sterne schaue.

Dachte nur , lieber ein Fehlerbericht mehr als einer zuwenig.

Also lieber mitteilen, als schweigen.

**Comment by Glitchy-Tozier** [comment]
Perfekt, danke!
Das Optimum ist ein Issue pro Bug, aber natürlich ist es besser zu reporten, wenn mann von keinen anderen Issues weiß.

**Comment by mondlicht-und-sterne** [comment]
ja das habe ich dann hinterher gesehm aber hätte ich es nicht kopiert, hätte ich den bug nicht gehabt.

achso der bug war von der "normalen" florisboard app, nicht von der florisboard beta app.
