### ISSUE TITLE
One more error

### ISSUE THREAD

**Issue by shreyanssshah** [florisboard/florisboard#671]
~~~ 1618423613713.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 6832 byte allocation with 1160568 free bytes and 1133KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 50331648 bytes)
	at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:534)
	at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:506)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.removeEventListener(FlorisBoard.kt:825)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyView.onDetachedFromWindow(EmojiKeyView.kt:77)
	at android.view.View.dispatchDetachedFromWindow(View.java:22071)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:6606)
	at android.view.ViewGroup.removeAllViews(ViewGroup.java:6552)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:564)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:553)
	at android.app.Dialog.setContentView(Dialog.java:869)
	at android.inputmethodservice.InputMethodService.initViews(InputMethodService.java:1739)
	at android.inputmethodservice.InputMethodService.resetStateForNewConfiguration(InputMethodService.java:1841)
	at android.inputmethodservice.InputMethodService.onConfigurationChanged(InputMethodService.java:1825)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onConfigurationChanged(FlorisBoard.kt:435)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:6119)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6408)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6294)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by patrickgold** [comment]
OOM errors are now handled in #677.
