### ISSUE TITLE
Crash when selecting theme if florisboard isn't default keyboard.

### ISSUE THREAD

**Issue by NeutralBit** [florisboard/florisboard#674]
If you select another keyboard as default and then go to Floris > Themes > selected themes. It will crash. 

~~~ 1618445433882.stacktrace ~~~

java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.patrickgold.florisboard/dev.patrickgold.florisboard.settings.ThemeManagerActivity}: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:621)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(Unknown Source:210)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:71)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:6)
	at android.view.LayoutInflater.rInflate(Unknown Source:92)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:107)
	at android.view.LayoutInflater.inflate(Unknown Source:27)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:101)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:95)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:159)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:52)
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.onCreate(FlorisActivity.kt:52)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreate(ThemeManagerActivity.kt:124)
	at android.app.Activity.performCreate(Unknown Source:19)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:376)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$Companion.getInstance(GlideTypingManager.kt:32)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:88)
	... 38 more

**Comment by patrickgold** [comment]
Fixed in #625, available currently in v0.3.11-beta01.
