### ISSUE TITLE
Vibrate error 0/0

### ISSUE THREAD

**Issue by esdreesh** [florisboard/florisboard#678]
~~~ 1618454484668.stacktrace ~~~

java.lang.IllegalArgumentException: duration must be positive (duration=0)
	at android.os.VibrationEffect$OneShot.validate(VibrationEffect.java:470)
	at android.os.VibrationEffect.createOneShot(VibrationEffect.java:178)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.keyPressVibrate(FlorisBoard.kt:665)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.keyPressVibrate$default(FlorisBoard.kt:623)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.onFlorisTouchEvent(KeyView.kt:293)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.sendFlorisTouchEvent(KeyboardView.kt:318)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:254)
	at android.view.View.dispatchTouchEvent(View.java:14376)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:730)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1008)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:169)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:688)
	at android.view.View.dispatchPointerEvent(View.java:14644)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6522)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6309)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5800)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5922)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5979)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5800)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5766)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5774)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5747)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8906)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8767)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8720)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9042)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by patrickgold** [comment]
Fixed by #1142
