### ISSUE TITLE
App crashed in background (TimeoutException)

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#681]
~~~ 1618476913310.stacktrace ~~~

java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

Version: 0.3.11beta01
Github 
Android 11 lineageos 
device poco m2 pro

**Comment by Glitchy-Tozier** [comment]
Hey, that's a new crash log!  :D

**Comment by patrickgold** [comment]
Thanks for your bug report! Seems like something crashed which is not directly managed by FlorisBoard, possibly the Binder for the InputConnection.
