### ISSUE TITLE
FlorisBoard crashes

### ISSUE THREAD

**Issue by realpixelcode** [florisboard/florisboard#683]
```
~~~ 1618477329338.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 45960 free bytes and 44KB until OOM, target footprint 201326592, growth limit 201326592
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677.
Patrick (the creator of Florisboard) knows about the issue and probably already is working on it, so I suggest we close this issue.

**Comment by realpixelcode** [comment]
Whatever you think is right – I just followed the app's instruction 🤷‍♂️

**Comment by patrickgold** [comment]
> Whatever you think is right – I just followed the app's instruction man_shrugging

But not the GitHub bug report instructions...

This issue is already more than known and is summarized in #677, duplicates of the same thing just makes it harder for me and others to try to find what should be worked on currently.
