### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by JimJamShazam** [florisboard/florisboard#694]
I don't see any guidelines for reporting bugs on mobile, but i'm following the prompts within Florisboard so hopefully this is right.

~~~ 1618278069801.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 2080 byte allocation with 369504 free bytes and 360KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 46661632 bytes)
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:108)
	at dev.patrickgold.florisboard.ime.extension.AssetManager.loadAsset-gIAlu-s(AssetManager.kt:152)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.loadTheme-IoAF18A(ThemeManager.kt:257)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.update(ThemeManager.kt:107)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onWindowShown(FlorisBoard.kt:406)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2846)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:880)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:241)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1618535556507.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 4520 byte allocation with 1991792 free bytes and 1945KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 77594624 bytes)
	at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:534)
	at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:506)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.unregisterOnThemeUpdatedListener(ThemeManager.kt:242)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.onDetachedFromWindow(PopupExtendedView.kt:96)
	at android.view.View.dispatchDetachedFromWindow(View.java:22071)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:6606)
	at android.view.ViewGroup.removeAllViews(ViewGroup.java:6552)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:564)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:553)
	at android.app.Dialog.setContentView(Dialog.java:869)
	at android.inputmethodservice.InputMethodService.initViews(InputMethodService.java:1739)
	at android.inputmethodservice.InputMethodService.resetStateForNewConfiguration(InputMethodService.java:1841)
	at android.inputmethodservice.InputMethodService.onConfigurationChanged(InputMethodService.java:1825)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onConfigurationChanged(FlorisBoard.kt:435)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:6119)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6408)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6294)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Glitchy-Tozier** [comment]
1. Thank you for your bug-report!
This issue has been reported a couple of times and is summarized in #677.
Patrick (the creator of Florisboard) knows about the issue and probably already is working on it, so I suggest we close this issue.
2. Could you also not see anthing on github itself? That wuld explain quite a few other bug reports.

(Here's what should've been displayed)
> 

> #### Short description
Describe the bug in a short but concise way.

> #### Steps to reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

> #### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM: 

>

**Comment by JimJamShazam** [comment]
Now that I'm accessing github from desktop, I can see those guidelines. At the time though, Florisboard crashed, and then a dialog came up asking me to copy the error report and then report the issue on github. Clicking on that link brought me to a blank issue submission page with no guidelines or further instructions visible (at least as far as I could tell on mobile). I just pasted the report in not knowing where else to look. I suspect you'll get a number of duplicate errors reported that way as a result.

Great to hear that the issue's being resolved!

**Comment by Glitchy-Tozier** [comment]
> Clicking on that link brought me to a blank issue submission page with no guidelines or further instructions visible

That's really strange. Is that on the Github-app or in a mobile browser?
I actually sespected something like this was happening, but when I tried it out on my phone this was where I landed:
![Screenshot_20210416-150128_GitHub.jpg](https://user-images.githubusercontent.com/59611881/115028057-bc9b3900-9ec4-11eb-9dbf-492da43ab681.jpg)
(The Bug-report-button takes you to a template)

> I suspect you'll get a number of duplicate errors reported that way as a result.

Yeah, it has been kind of bad  xD At least 10-15 duplicates within the last few days.

@patrickgold Any ideas what to do here?

**Comment by JimJamShazam** [comment]
@Glitchy-Tozier In my case it was with a mobile browser, Brave specifically. If I manually go into the Florisboard Github -> Issues -> New, I see the same set of templates as you do, but when the app crashes and gives you a log to report, those menus don't appear. Clicking on the "Report crash on Github" button (or whatever the exact wording was) bypasses all the templates.

**Comment by patrickgold** [comment]
@Glitchy-Tozier It seems that the app handles the templates but the mobile web page seems to kind of do its own thing. What I absolutely don't understand is that it displays an empty issue, if I link to the template chooser page: `https://github.com/florisboard/florisboard/issues/new`. Really strange behavior, but this would indeed explain the countless duplicates etc. As a workaround I could link to the issues rather than the template chooser, which should display the issue list alongside the searchbar.

**Comment by patrickgold** [comment]
Just realized that linking to the issue page is way more intelligent, as you get prompted instantly with the pinned OutOfMemory error issue, then a search bar. Will include this in the crash utility improvements I am currently working on.

**Comment by Glitchy-Tozier** [comment]
Is there some automatic log-posting behavior that might be destroyed by that practice? If no, that sounds like a great idea!

**Comment by patrickgold** [comment]
No, because you copy the stacktrace to the system clipboard, you just have to click 2 more buttons in the web page /or GitHub app). Given that this potentially would prevent the majority of duplicates, I take this 2 buttons more to click immediately over the duplicate mess we currently have.

Btw, thanks you very much for your efforts in first-replying to many unformatted bug reports and in general for your active contributions  in the discussions here on GitHub, this help is very valuable and I really appreciate it!

**Comment by Glitchy-Tozier** [comment]
> Given that this potentially would prevent the majority of duplicates, I take this 2 buttons more to click immediately over the duplicate mess we currently have.

Agreed, this definitely is a big improvement!

> Btw, thanks you very much for your efforts in first-replying to many unformatted bug reports and in general for your active contributions in the discussions here on GitHub, this help is very valuable and I really appreciate it!

1. I have been looking for a prpper open-source keyboard for quite some time and FlorisBoard is just amazing (once we fix those crashes 😏)...
2. I kind of like the atmosphere here and everyones friendliness...

... so I figured it would be a good idea to contribute a little.  :)


(Also, as the keyboard still is in its early stages of development, i can meld it to my own needs by spamming feature requests hehehe)
