### ISSUE TITLE
App force closed

### ISSUE THREAD

**Issue by sn0wD4N** [florisboard/florisboard#697]
~~~ 1618590818231.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 767472 free bytes and 749KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 56623104 bytes)
	at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
	at com.android.internal.util.ArrayUtils.newUnpaddedIntArray(ArrayUtils.java:61)
	at com.android.internal.util.GrowingArrayUtils.append(GrowingArrayUtils.java:65)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:773)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:686)
	at android.widget.TextView.setText(TextView.java:6828)
	at android.widget.TextView.setText(TextView.java:6638)
	at android.widget.TextView.setText(TextView.java:6590)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyView.<init>(EmojiKeyView.kt:68)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invokeSuspend(EmojiKeyboardView.kt:160)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView.buildLayoutForCategory(EmojiKeyboardView.kt:149)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2.invokeSuspend(EmojiKeyboardView.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677.
Patrick (the creator of Florisboard) knows about the issue and probably already is working on it, so I suggest we close this issue.
