### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by keuwey** [florisboard/florisboard#699]
~~~ 1618610515704.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:287)
	at android.content.ContentResolver.insert(ContentResolver.java:1557)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:222)
	at android.content.ClipboardManager$2.handleMessage(ClipboardManager.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:169)
	at android.app.ActivityThread.main(ActivityThread.java:6521)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by patrickgold** [comment]
Thanks for your bug report! Seems to be an issue within the clipboard feature, adding to the todo list!
