### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tudi20** [florisboard/florisboard#719]
```~~~ 1618954637488.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-04-20:819293632
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1684)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:325)
	at android.content.ContentResolver.insert(ContentResolver.java:1844)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:270)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:64)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	... 3 more
```

**Comment by X-yl** [comment]
Could you share the steps to reproduce? What were you doing when this issue occured?

**Comment by Tudi20** [comment]
I was in the multitasking view

**Comment by procheekibreeki** [comment]
I got this same exact error but I don't what I did to get it.

**Comment by anedroid** [comment]
I experience lots of crashes when displaying suggestions is enabled.
