### ISSUE TITLE
florisboard crash..

### ISSUE THREAD

**Issue by Boaz-ka** [florisboard/florisboard#720]
Hi Patrick! 👋

First of all, I want to thank you for your efforts to make florisboard so attractive,
The various options to customize the keyboard, 
caring for privacy...

Since the last update, my favorite app - florisboard seems to behave quite strange,
It's look like that over the time the app is been used - florisboard responding more slowly..

I'll attach the log, so you can have a look - as the "one who knows what is happeming under the hood" 😁

~~~ 1618956239367.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 130152 byte allocation with 2670720 free bytes and 2608KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 42991616 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupView.onAttachedToWindow(PopupView.kt:80)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:79)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)



I hope that will help you to understand..
Again, thank you for your effort (which are not taking for granted..  🙏)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

1. I agree that Florisboard is great!  :)
2. This issue has been reported a couple of times and is summarized in #677. Patrick (and others) are already working on it.

I'm sure he will be happy about your comments, but I'll close this issue to keep the list free of duplicates.  :)
(he sometimes reads closed issues anyways)
