### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#73]
~~~ 1607403228381.stacktrace ~~~

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.updateTheme(FlorisBoard.kt:349)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onWindowShown(FlorisBoard.kt:251)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1891)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:638)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:220)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by patrickgold** [comment]
Could you please provide more context when exactly this crash occurs and possible steps to reproduce? Thank you!

**Comment by patrickgold** [comment]
This crash should be fixed with above commit. Will ship with the next release v0.3.1.
