### ISSUE TITLE
Keyboard hangs occasionally in messaging app

### ISSUE THREAD

**Issue by flarfoo** [florisboard/florisboard#736]
#### Short description
No response (vibrations or text display) while typing in my messages app

#### Steps to reproduce (not entirely sure)
1. Bluetooth connected to wireless earbuds
2. Spotify playing in background
3. Connected to 5G
4. Open default Messages app
5. Click on 'chat message'
6. Start typing?

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Pixel 5
- Android: 11

Crash Report:

~~~ 1619108484219.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 341192 free bytes and 333KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report and welcome on Github!

This was mentioned a couple of times already and is being worked on. The main post for this problem (too much memory usage) is #677.
I'll close this issue to keep the list clean of duplicates. That being said, thank you for your amazingly well filled out bug-report!  :)
