### ISSUE TITLE
Just I visit kaspersky.com

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#740]
It shows a bug when I visit kaspersky.com
Android 11, firefox68,samsung a50

`~~~ 1619180334157.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 120 byte allocation with 1988704 free bytes and 1942KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 37486592 bytes)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:40)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:66)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:65)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:77)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1618158718741.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1000608 free bytes and 977KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 35127296 bytes)
	at dev.patrickgold.florisboard.ime.media.MediaInputManager$onRegisterInputView$1.invokeSuspend(MediaInputManager.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Let's close this to keep the list of issues free of duplicates!
