### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by procheekibreeki** [florisboard/florisboard#742]
Was typing to someone on discord when the keyboard just frozen and then crashed.

~~~ 1619200700801.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 3152 byte allocation with 329472 free bytes and 321KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 70516736 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.toArray(CopyOnWriteArrayList.java:321)
	at java.util.ArrayList.<init>(ArrayList.java:191)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1303)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1284)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:494)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.endInternalBatchEdit(FlorisBoard.kt:459)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:751)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$4.invokeSuspend(InputEventDispatcher.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!
