### ISSUE TITLE
crash detected by device

### ISSUE THREAD

**Issue by kangzhe3067** [florisboard/florisboard#744]
```
~~~ 1619229211976.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1290968 free bytes and 1260KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 81788928 bytes)
	at java.util.HashMap.newNode(HashMap.java:1746)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Other information:
Device: Samsung S21 Ultra (SM-G998B)
OS: Android 11
OneUI: 3.1

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report and for adding environment information!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!
