### ISSUE TITLE
System dead crash

### ISSUE THREAD

**Issue by obeho** [florisboard/florisboard#749]
#### Short description
Describe what you were doing that could've led to the crash.

I was trying to open an app but it wasn't opening, upon repeated clicking a crash report for Florisboard Beta got generated, after which the handset restarted.

Though this might not be some bug in FlorisBoard's code, I hope there is a defined activity for the keyboard in case of system crashes like this. Or is it the same as normal phone reboot?

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

```
~~~ 1619248474626.stacktrace ~~~

java.lang.RuntimeException: android.os.DeadSystemException
	at com.android.internal.inputmethod.InputMethodPrivilegedOperations.reportFullscreenMode(InputMethodPrivilegedOperations.java:177)
	at android.inputmethodservice.InputMethodService.reportFullscreenMode(InputMethodService.java:1329)
	at android.inputmethodservice.InputMethodService.access$100(InputMethodService.java:254)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.bindInput(InputMethodService.java:546)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:184)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: android.os.DeadSystemException
	... 12 more

```

**Comment by patrickgold** [comment]
As per the Android documentation:

> The core Android system has died and is going through a runtime restart. All running apps will be promptly killed.

So most likely something in the system fatally crashed and the Android system then terminates all apps. It is possible for Android apps (including FlorisBoard) to produce this crash, but most likely the app is not the crash source. If possible, could you tell me which Android version + FlorisBoard version you are running and which device you have? There are some known issues for this type of crash for some Android versions, maybe FlorisBoard uses exactly one of these scenarios leading to the crash of the Android core.

Additionally: can you consistently reproduce the bug or was this a one-time experience?

> Or is it the same as normal phone reboot?

Nope, something in the Android core crashed fatally and your phone force rebooted to recover from this.

**Comment by obeho** [comment]
Android 10
v 0.3.11-beta01

> one-time experience
I have been using beta app from Fdroid since glide typing was enabled. This is the first time the app crashed.

> Nope, something in the Android core crashed fatally and your phone force rebooted to recover from this.
Yes, I understand that. I was talking about the app's desinated behaviour when such soft reboot or a normal restart occurs, is it the same in both scenarios?

**Comment by lm41** [comment]
I think we can close this as stale.

**Comment by obeho** [comment]
> I think we can close this as stale.

lol ok. i found a better [keyboard](https://github.com/Helium314/HeliBoard) anyways.

**Comment by lm41** [comment]
@obeho Has it ocurred again?
