### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shreyanssshah** [florisboard/florisboard#755]
~~~ 1618677366837.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 9144 byte allocation with 446192 free bytes and 435KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 36962304 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.onAttachedToWindow(PopupExtendedView.kt:92)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:80)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1618749747871.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 94608 byte allocation with 2179680 free bytes and 2128KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 49283072 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupView.onAttachedToWindow(PopupView.kt:80)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:79)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1618883030048.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1299392 free bytes and 1268KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 34603008 bytes)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$TypeParameter.<init>(ProtoBuf.java:7345)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$TypeParameter.<init>(ProtoBuf.java:7250)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$TypeParameter$1.parsePartialFrom(ProtoBuf.java:7384)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$TypeParameter$1.parsePartialFrom(ProtoBuf.java:7379)
	at kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Function.<init>(ProtoBuf.java:14397)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Function.<init>(ProtoBuf.java:14321)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Function$1.parsePartialFrom(ProtoBuf.java:14516)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Function$1.parsePartialFrom(ProtoBuf.java:14511)
	at kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Package.<init>(ProtoBuf.java:11619)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Package.<init>(ProtoBuf.java:11566)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Package$1.parsePartialFrom(ProtoBuf.java:11697)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$Package$1.parsePartialFrom(ProtoBuf.java:11692)
	at kotlin.reflect.jvm.internal.impl.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.<init>(ProtoBuf.java:22545)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.<init>(ProtoBuf.java:22466)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment$1.parsePartialFrom(ProtoBuf.java:22588)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment$1.parsePartialFrom(ProtoBuf.java:22583)
	at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at kotlin.reflect.jvm.internal.impl.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf$PackageFragment.parseFrom(ProtoBuf.java:22802)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsPackageFragmentImpl$Companion.create(BuiltInsPackageFragmentImpl.kt:49)
	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsPackageFragmentProvider.findPackage(JvmBuiltInsPackageFragmentProvider.kt:61)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider$fragments$1.invoke(AbstractDeserializedPackageFragmentProvider.kt:34)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider$fragments$1.invoke(AbstractDeserializedPackageFragmentProvider.kt:26)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.AbstractDeserializedPackageFragmentProvider.getPackageFragments(AbstractDeserializedPackageFragmentProvider.kt:41)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.CompositePackageFragmentProvider.getPackageFragments(CompositePackageFragmentProvider.kt:31)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.CompositePackageFragmentProvider.getPackageFragments(CompositePackageFragmentProvider.kt:31)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$fragments$2.invoke(LazyPackageViewDescriptorImpl.kt:37)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$fragments$2.invoke(LazyPackageViewDescriptorImpl.kt:30)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:489)
	at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl.getFragments(Unknown Source:7)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$memberScope$1.invoke(LazyPackageViewDescriptorImpl.kt:41)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.LazyPackageViewDescriptorImpl$memberScope$1.invoke(LazyPackageViewDescriptorImpl.kt:30)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter$lazyScope$1.invoke(LazyScopeAdapter.kt:28)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter$lazyScope$1.invoke(LazyScopeAdapter.kt:22)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:489)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.LazyScopeAdapter.getWorkerScope(LazyScopeAdapter.kt:34)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
	at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(findClassInModule.kt:26)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.computeClassifierDescriptor(TypeDeserializer.kt:240)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.access$computeClassifierDescriptor(TypeDeserializer.kt:23)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer$classifierDescriptors$1.invoke(TypeDeserializer.kt:33)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer$classifierDescriptors$1.invoke(TypeDeserializer.kt:23)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.typeConstructor(TypeDeserializer.kt:132)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:76)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.type(TypeDeserializer.kt:64)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.valueParameters(MemberDeserializer.kt:417)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.loadConstructor(MemberDeserializer.kt:342)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.computePrimaryConstructor(DeserializedClassDescriptor.kt:126)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.access$computePrimaryConstructor(DeserializedClassDescriptor.kt:36)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$primaryConstructor$1.invoke(DeserializedClassDescriptor.kt:67)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$primaryConstructor$1.invoke(DeserializedClassDescriptor.kt:36)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.getUnsubstitutedPrimaryConstructor(DeserializedClassDescriptor.kt:130)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.computeConstructors(DeserializedClassDescriptor.kt:133)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.access$computeConstructors(DeserializedClassDescriptor.kt:36)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$constructors$1.invoke(DeserializedClassDescriptor.kt:68)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$constructors$1.invoke(DeserializedClassDescriptor.kt:36)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:489)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.getConstructors(DeserializedClassDescriptor.kt:141)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:202)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:93)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:46)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(Unknown Source:7)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:237)
	at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:221)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonLayoutData$Companion.fromJsonFile(EmoticonLayoutData.kt:40)
	at dev.patrickgold.florisboard.ime.media.emoticon.EmoticonKeyboardView$1.invokeSuspend(EmoticonKeyboardView.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1618969778322.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 1336 byte allocation with 1536616 free bytes and 1500KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 46399488 bytes)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invokeSuspend(EmojiKeyboardView.kt:160)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView.buildLayoutForCategory(EmojiKeyboardView.kt:149)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2.invokeSuspend(EmojiKeyboardView.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1619031799064.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 742264 free bytes and 724KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 25165824 bytes)
	at kotlin.reflect.jvm.internal.KParameterImpl.getType(KParameterImpl.kt:43)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:137)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:111)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:51)
	at dev.patrickgold.florisboard.ime.extension.AssetManager.loadAsset-gIAlu-s(AssetManager.kt:170)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.loadLayout-IoAF18A(LayoutManager.kt:71)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.mergeLayoutsAsync(LayoutManager.kt:122)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager.computeLayoutFor(LayoutManager.kt:337)
	at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$fetchComputedLayoutAsync$computedLayout$1.invokeSuspend(LayoutManager.kt:381)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1619031800548.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 230352 free bytes and 224KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1619096205944.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 1583232 free bytes and 1546KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 86769664 bytes)
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1619292066127.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 373800 free bytes and 365KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 33292288 bytes)
	at org.json.JSONTokener.readLiteral(JSONTokener.java:315)
	at org.json.JSONTokener.nextValue(JSONTokener.java:115)
	at org.json.JSONTokener.readObject(JSONTokener.java:394)
	at org.json.JSONTokener.nextValue(JSONTokener.java:104)
	at org.json.JSONObject.<init>(JSONObject.java:165)
	at org.json.JSONObject.<init>(JSONObject.java:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report and for adding environment information!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!

**Comment by shreyanssshah** [comment]
Yes, so I went through the solution(s), but I really didnt  understand what
I need to do/what settings to change to make the keyboard work without
crashing. Please let me know the changes to be done.

Thanks..

**Comment by Glitchy-Tozier** [comment]
You could try this:

>"When you disable (word-)suggestions and the internal clipboard, all lag seems to be removed."

**Comment by shreyanssshah** [comment]
Yes, i have already disabled  those. And the keyboard still crashed.. maybe
some other suggestion please..

**Comment by Glitchy-Tozier** [comment]
Currently there is no better solution. We're working on fixing it, but that might take 1-2 more weeks.

**Comment by shreyanssshah** [comment]
Yes, no worries. In the meanwhile I will keep using another keyboard. .
