### ISSUE TITLE
Error on Galaxy S9 Java Lang Out of Memory

### ISSUE THREAD

**Issue by Tashima42** [florisboard/florisboard#758]
~~~ 1619358905795.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 76 byte allocation with 1610656 free bytes and 1572KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 176736 bytes)
	at java.lang.Object.internalClone(Native Method)
	at java.lang.Object.clone(Object.java:259)
	at android.graphics.ColorSpace$Named.values(ColorSpace.java:236)
	at android.graphics.ColorSpace.get(ColorSpace.java:1388)
	at android.graphics.Color.colorSpace(Color.java:704)
	at android.graphics.Paint.setAlpha(Paint.java:1140)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:41)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:66)
	at dev.patrickgold.florisboard.ime.popup.PopupView.<init>(PopupView.kt:65)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:77)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by astarq** [comment]
An issue is already open here: https://github.com/florisboard/florisboard/issues/677

Please close this issue inorder to prevent cluttering. Thanks! ✌️🙂

**Comment by Tashima42** [comment]
> An issue is already open here: #677
> 
> Please close this issue inorder to prevent cluttering. Thanks! vslightly_smiling_face

Okay, sorry.
