### ISSUE TITLE
"Florisboard has stopped working..." Error when copying from calculator app

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#761]
I was copying result from calculater app, and florisboard error popped up:

It happens everytime I try to copy from calculator:
![](https://i.imgur.com/izMmtnF.jpg)

As soon as I click on copy, florisboard error notification appears:
![](https://i.imgur.com/fwfYusA.jpg) 

~~~ 1619413304080.stacktrace ~~~

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	... 1 more
Caused by: java.io.FileNotFoundException: No content provider: tag:calculator2.android.com,2021-04-26:33870371
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1673)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
	at android.content.ContentResolver.insert(ContentResolver.java:1828)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:251)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:63)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	... 3 more

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

@X-yl This looks like it may be interesting to you.   :)

**Comment by X-yl** [comment]
Very interesting indeed! Florisboard thinks the calculator is putting an image on the clipboard which gets it very confused. I have to investigate. This is the AOSP calculator right?

**Comment by rancidfrog** [comment]
LimeageOS calculator, so they might have made some changes to AOSP

**Comment by X-yl** [comment]
And here we see the culprit! https://github.com/LineageOS/android_packages_apps_ExactCalculator/blob/c3602a56540caf0e121b632788d6589a530baf84/src/com/android/calculator2/CalculatorResult.java#L1140-L1141

They have included a URI, for their own internal use, however they have not provided a content provider for florisboard to resolve this URI! This is such a hacky abuse of the clipboard system that I'm half tempted to tell you to file a bug for LineageOS. I guess I can stop florisboard from crashing by making sure the mimetypes make sense, but to be honest I really do feel like for once this crash isn't my fault.

**Comment by Glitchy-Tozier** [comment]
Maybe we should do both.

> I guess I can stop florisboard from crashing by making sure the mimetypes make sense

I don't fully understand this but it sounds like a good idea in general

> ...that I'm half tempted to tell you to file a bug for LineageOS.

Maybe we should really do that, if the've commited such a grave faux pas.

**Comment by X-yl** [comment]
> I don't fully understand this but it sounds like a good idea in general.

A mime type is a standardized way to talk about what type of content a file contains. So if a file is plain text, the mimetype is "text/plain". Instead of implicitly assuming a URI means image (as it does in 99% of cases), I will add an explicit check to stop this crash.

> Maybe we should really do that, if the've commited such a grave faux pas.

Upon further investigation, this part of the code is copied directly from the AOSP. As I presume they know a lot more than me, I'm going to have to relent and assume that there's some secret line of the spec which allows this behaviour.

This is what the docs say on first glance though: 
> URI
    A Uri object representing any form of URI. This is primarily for copying complex data from a content provider. To copy data, you put a Uri object into a clip object and put the clip object onto the clipboard. **To paste the data, you get the clip object, get the Uri object, resolve it to a data source such as a content provider, and copy the data from the source into your application's storage.** 

Florisboard does exactly this. It attempts to resolve the URI and copy it to its own storage, which causes a crash because Calculator didn't specify a way for the URI to be resolved.

**Comment by rancidfrog** [comment]
@X-yl 
I tested with hackerskeyboard and lineageOS default keyboard and there was no problem.

![](https://i.imgur.com/89o9yp6.jpg)

Text copied properly without issues. Only florisboard seems to have a problem.

https://github.com/klausw/hackerskeyboard version 1.41.1

**Comment by X-yl** [comment]
I don't think those have clipboard managers, do they? Anyway, although I still believe it's a misuse of the clipboard API, Florisboard definitely shouldn't crash. I'll open a PR with my fix soon.
