### ISSUE TITLE
extreme lag then crash

### ISSUE THREAD

**Issue by Turbotomate** [florisboard/florisboard#765]
Today the keyboard lagged  every time after i opened it (inouts of the first 5 seconds after opening the board got delayed, after that it worked nearly normal) and after ~10 minutes it crashed with the following message:

~~~ 1619458180351.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 53864 byte allocation with 2241360 free bytes and 2188KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 89915392 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupView.onAttachedToWindow(PopupView.kt:80)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:79)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!

**Comment by Turbotomate** [comment]
Duplicate
