### ISSUE TITLE
Florisboard hangs a lot!

### ISSUE THREAD

**Issue by musicsd** [florisboard/florisboard#772]
~~~ 1618577913834.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 32120 free bytes and 31KB until OOM, target footprint 201326592, growth limit 201326592
	at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:86)
	at com.android.internal.util.FastXmlSerializer.<init>(FastXmlSerializer.java:75)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:197)
	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:778)
	at android.app.SharedPreferencesImpl.access$900(SharedPreferencesImpl.java:55)
	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:647)
	at android.app.QueuedWork.processPendingWork(QueuedWork.java:264)
	at android.app.QueuedWork.access$000(QueuedWork.java:50)
	at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:284)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
~~~ 1618577864337.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 16 free bytes and 16B until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
~~~ 1618577861845.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 8 free bytes and 8B until OOM, target footprint 201326592, growth limit 201326592
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:992)
~~~ 1618577845423.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 104 byte allocation with 88 free bytes and 88B until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuilder.toString(StringBuilder.java:413)
	at java.lang.Daemons$FinalizerWatchdogDaemon.finalizerTimedOut(Daemons.java:446)
	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
~~~ 1619638404811.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:65)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView$initGestureClassifier$1.run(KeyboardView.kt:147)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!
