### ISSUE TITLE
Crash when change keyboard app from Gboard to Floris

### ISSUE THREAD

**Issue by kurdikeyboard** [florisboard/florisboard#774]
#### Environment information
- FlorisBoard Version: 0.3.11-debug (36)
- - Device: Realme RMX1931
- Android: 10 (cn=Q sdk=29)
#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1619707284239.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
		at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(Keyboard.kt:159)
			at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onLayoutInternal(TextKeyboardView.kt:680)
				at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.notifyStateChanged(TextKeyboardView.kt:200)
					at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:189)
						at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$2$1$1.invokeSuspend(SmartbarView.kt:114)
							at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
								at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
									at android.os.Handler.handleCallback(Handler.java:883)
										at android.os.Handler.dispatchMessage(Handler.java:100)
											at android.os.Looper.loop(Looper.java:227)
												at android.app.ActivityThread.main(ActivityThread.java:7842)
													at java.lang.reflect.Method.invoke(Native Method)
														at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
															at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```
</details>

**Comment by Glitchy-Tozier** [comment]
@patrickgold Was that displacement-effect in the log intentional?
It kind of hurts my brain.

**Comment by patrickgold** [comment]
@Glitchy-Tozier Nope, definitely not :) Either this was some find of auto-intent error when pasting or something internally goes wrong. (When purposely letting FlorisBoard crash though the stacktrace looks beautiful and not like the one attached above, so not exactly sure here).

**Comment by kurdikeyboard** [comment]
@patrickgold  latest beta version is have many crashes on every single time i got an crash and a black stamp of keyboard is showing on screen even when changes to another keyboard app 


https://user-images.githubusercontent.com/3160786/116788637-67aa1600-aab3-11eb-93c3-ee99fb8183ce.mp4

When Florisboard crash also my device get freeze too 🥶

Version: 3.11.beta2 

Android: 10 Realme UI 1.0

Device: Realme X2 Pro

**Comment by patrickgold** [comment]
Above commit is a potential fix for the NaN crash. If possible could you try out if the [debug APK](https://github.com/florisboard/florisboard/pull/794/checks) if it has been fixed for you? Thanks in advance!
