### ISSUE TITLE
CRASH DURING SPLIT SCREEN MODE

### ISSUE THREAD

**Issue by 42837531** [florisboard/florisboard#775]
~~~ 1619785857383.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1576592 free bytes and 1539KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 2883584 bytes). Number of 256KB sized free regions are: 11
	at dev.patrickgold.florisboard.ime.core.CachedInput.reevaluate(EditorInstance.kt:1098)
	at dev.patrickgold.florisboard.ime.core.CachedInput.reevaluate(EditorInstance.kt:1117)
	at dev.patrickgold.florisboard.ime.core.CachedInput.update(EditorInstance.kt:1067)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.onUpdateSelection(EditorInstance.kt:135)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onUpdateSelection(FlorisBoard.kt:489)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.endInternalBatchEdit(FlorisBoard.kt:459)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:751)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$4.invokeSuspend(InputEventDispatcher.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:988)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Patrick (the creator of Florisboard) is working on it.

Let's close this report to keep the list of issues free of duplicates!

**Comment by beedell-roke** [comment]
@patrickgold, I can't do so myself (because I can't re-open it), but GitHub now supports closing as duplicate.

**Comment by patrickgold** [comment]
I know and do that for new issues, but I don't really bother with old issues.

**Comment by beedell-roke** [comment]
Yeah, sorry. Kinda dumb of me.
