### ISSUE TITLE
Crash report for analysis!

### ISSUE THREAD

**Issue by IdreesM0** [florisboard/florisboard#787]
~~~ 1619934596478.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 184 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at android.os.Message.<init>(Message.java:150)
	at android.os.Message.obtain(Message.java:167)
	at android.os.Message.obtain(Message.java:229)
	at android.os.Handler.obtainMessage(Handler.java:368)
	at com.android.internal.os.HandlerCaller.obtainMessage(HandlerCaller.java:119)
	at android.inputmethodservice.IInputMethodSessionWrapper.removeImeSurface(IInputMethodSessionWrapper.java:193)
	at com.android.internal.view.IInputMethodSession$Stub.onTransact(IInputMethodSession.java:265)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)
~~~ 1619934596216.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
~~~ 1619934549936.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 120 byte allocation with 72 free bytes and 72B until OOM, target footprint 268435456, growth limit 268435456
	at android.util.MergedConfiguration.<init>(MergedConfiguration.java:36)
	at android.util.MergedConfiguration.<init>(MergedConfiguration.java:33)
	at android.util.MergedConfiguration$1.createFromParcel(MergedConfiguration.java:80)
	at android.util.MergedConfiguration$1.createFromParcel(MergedConfiguration.java:77)
	at android.view.IWindow$Stub.onTransact(IWindow.java:358)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)
~~~ 1619934599633.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 72 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at android.os.Message.obtain(Message.java:167)
	at android.os.Message.obtain(Message.java:229)
	at android.os.Handler.obtainMessage(Handler.java:368)
	at com.android.internal.os.HandlerCaller.obtainMessage(HandlerCaller.java:119)
	at android.inputmethodservice.IInputMethodSessionWrapper.finishSession(IInputMethodSessionWrapper.java:222)
	at com.android.internal.view.IInputMethodSession$Stub.onTransact(IInputMethodSession.java:240)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)
~~~ 1619934599967.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at android.os.Parcel.obtain(Parcel.java:3504)
	at android.os.Binder.execTransactInternal(Binder.java:1138)
	at android.os.Binder.execTransact(Binder.java:1126)
~~~ 1619934596225.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 184 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at android.os.Message.<init>(Message.java:150)
	at android.os.Message.obtain(Message.java:167)
	at android.os.Message.obtain(Message.java:229)
	at android.os.Handler.obtainMessage(Handler.java:368)
	at com.android.internal.os.HandlerCaller.obtainMessage(HandlerCaller.java:119)
	at android.inputmethodservice.IInputMethodSessionWrapper.finishSession(IInputMethodSessionWrapper.java:222)
	at com.android.internal.view.IInputMethodSession$Stub.onTransact(IInputMethodSession.java:240)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)
~~~ 1619934600838.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 48 free bytes and 48B until OOM, target footprint 268435456, growth limit 268435456
	at android.app.servertransaction.LaunchActivityItem$1.createFromParcel(LaunchActivityItem.java:169)
	at android.app.servertransaction.LaunchActivityItem$1.createFromParcel(LaunchActivityItem.java:167)
	at android.os.Parcel.readParcelable(Parcel.java:3284)
	at android.os.Parcel.readParcelableList(Parcel.java:3055)
	at android.app.servertransaction.ClientTransaction.<init>(ClientTransaction.java:204)
	at android.app.servertransaction.ClientTransaction.<init>(ClientTransaction.java:44)
	at android.app.servertransaction.ClientTransaction$1.createFromParcel(ClientTransaction.java:211)
	at android.app.servertransaction.ClientTransaction$1.createFromParcel(ClientTransaction.java:209)
	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1257)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)

Xiaomi mi 11 lite
Miui 12.0.8 on android 11

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Fixes are on their way.

Let's close this report to keep the list of issues free of duplicates!
