### ISSUE TITLE
works slow or instable

### ISSUE THREAD

**Issue by dorsdn** [florisboard/florisboard#788]
~~~ 1619936817629.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201425456, growth limit 201326592
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:992)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. Fixes are on their way.

Let's close this report to keep the list of issues free of duplicates!
