### ISSUE TITLE
Crashed and shown this message

### ISSUE THREAD

**Issue by shameempk** [florisboard/florisboard#797]
```
~~~ 1609661748380.stacktrace ~~~

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1577)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1424)
	at dev.patrickgold.florisboard.ime.popup.KeyPopupManager.extend(KeyPopupManager.kt:389)
	at dev.patrickgold.florisboard.ime.text.key.KeyView$onFlorisTouchEvent$3.run(KeyView.kt:258)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
~~~ 1620055886812.stacktrace ~~~

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1071)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1576)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1423)
	at dev.patrickgold.florisboard.ime.popup.KeyPopupManager.extend(KeyPopupManager.kt:389)
	at dev.patrickgold.florisboard.ime.text.key.KeyView$onFlorisTouchEvent$3.run(KeyView.kt:258)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by shameempk** [comment]
Version: 0.3.2.
I am not sure about what I was doing.

**Comment by Glitchy-Tozier** [comment]
In that case I suggest updating. 0.3.2 was released many monthas ago, so that issue may already have been fixed.

(just know that 0.3.10 crashes from time to time. 0.3.11 will fix that issue)

**Comment by shameempk** [comment]
I'll try that. FYI this version was the latest available in f-droid. I'll update it with release apk's.

**Comment by shameempk** [comment]
Closing as per [this comment](https://github.com/florisboard/florisboard/issues/797#issuecomment-831690060).
Will reopen if encounter with new versions.

**Comment by Glitchy-Tozier** [comment]
> FYI this version was the latest available in f-droid.

That would be very weird. Sure it was 0.3.2.?

Maybe it was an F-Droid-bug?

**Comment by shameempk** [comment]
I installed beta from f-droid now. And I checked again and it is showing 0.3.10 now. Must be some error from f-droid side as I had refreshed all repos before it showed 0.3.2.
