### ISSUE TITLE
Error while rotating screen in termux

### ISSUE THREAD

**Issue by kj7rrv** [florisboard/florisboard#800]
#### Short description
I was using Vim in Termux.

#### Steps to reproduce
1. Open Termux
2. Run Vim
3. Edit a file
4. Rotate screen (a few times?)

#### Environment information
- FlorisBoard Version: 0.3.11-beta02 (37)
- Device: Motorola moto g power
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = false
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1618535982303.stacktrace</summary>

```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)

```
</details>

<details>
<summary>1618602286010.stacktrace</summary>

```
android.view.InflateException: Binary XML file line #56 in dev.patrickgold.florisboard.beta:layout/florisboard: Binary XML file line #20 in dev.patrickgold.florisboard.beta:layout/text_input_layout: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #20 in dev.patrickgold.florisboard.beta:layout/text_input_layout: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onCreateInputView(FlorisBoard.kt:256)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1507)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:1935)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1884)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:638)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:220)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 3808 byte allocation with 2624 free bytes and 2624B until OOM, target footprint 201326592, growth limit 201326592
	at android.view.ViewGroup.addInArray(ViewGroup.java:5218)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5131)
	at android.view.ViewGroup.addView(ViewGroup.java:4938)
	at android.view.ViewGroup.addView(ViewGroup.java:4878)
	at android.view.ViewGroup.addView(ViewGroup.java:4851)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:79)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:115)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:65)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:98)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:82)
	... 32 more

```
</details>

<details>
<summary>1620065358977.stacktrace</summary>

```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

It seems like you have the almost-FlorisBoard-traditional rotate OOM crash - when the device is rotated, the UI is rebuild and some parts of the UI are just not optimized for it, especially Emojis (will be fixed in v0.3.11-beta04!!) and suggestions (the big fish which will definitely contribute to eat up your RAM). As a temporary fix you can disable suggestions and see how it goes. As this crash is OOM related, I will close it and use #677 further on.
