### ISSUE TITLE
ArrayIndexOutOfBoundsException when switching between tasks

### ISSUE THREAD

**Issue by felixwiemuth** [florisboard/florisboard#801]
#### Short description
Happened while switching between recent tasks (using the swipe gesture at the bottom of the screen). Some tasks would open the keyboard because they have an active input field. After some number of switching forth and back (rather quickly) I suddenly got the keyboard crash info.

Interesting that the exception seems to have to do with the gliding functionality. Maybe I accidentally triggered a glide action on the keyboard while wanting to swipe to recent tasks? (Gliding is enabled.)

I could not reproduce this so far.

OS is Android 11 / GrapheneOS.

~~~ 1620050496382.stacktrace ~~~

java.lang.ArrayIndexOutOfBoundsException: length=300; index=-1
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Gesture.getLastX(StatisticalGlideTypingClassifier.kt:541)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.pruneByExtremities(StatisticalGlideTypingClassifier.kt:277)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.unCachedGetSuggestions(StatisticalGlideTypingClassifier.kt:166)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.getSuggestions(StatisticalGlideTypingClassifier.kt:150)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$updateSuggestionsAsync$1.invokeSuspend(GlideTypingManager.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi, what version of the app are you using?

**Comment by felixwiemuth** [comment]
v0.3.10. I hoped that the version would be in that stack trace header. I suggest that the issue template for crash reports is updated to ask for the relevant data.

**Comment by Glitchy-Tozier** [comment]
> v0.3.10.

Interesting, let's see what Patrick finds when he checks out the bug.

> I suggest that the issue template for crash reports is updated to ask for the relevant data.

That's a great suggestion and already was implemented.  ;)
In v.0.3.11 (which should get released in 1-2 weeks) the crash-log has been improved and you won't be taken to the wrong/empty template abymore.

**Comment by felixwiemuth** [comment]
> That's a great suggestion and already was implemented. ;)

I meant [here](https://github.com/florisboard/florisboard/blob/master/.github/ISSUE_TEMPLATE/crash_report.md) in the template itself, is the "Environment" section added?

> In v.0.3.11 (which should get released in 1-2 weeks) the crash-log has been improved and you won't be taken to the wrong/empty template abymore.

That sounds good, I had planned to suggest that too ;).

**Comment by Glitchy-Tozier** [comment]
> I meant here in the template itself, is the "Environment" section added?

It was removed, actually, because in 0.3.11 the enviroment-information will automatically be added to the crash-log.

> That sounds good, I had planned to suggest that too ;).

Well, I was faster.  :P

**Comment by joe733** [comment]
#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Itel L5503
- Android: 9 (cn=P sdk=28)

#### Features enabled

```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```


#### Attached stacktrace files
<details>
<summary>1628596403426.stacktrace</summary>

```java
java.lang.StringIndexOutOfBoundsException: String index out of range: 12
 at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:952)
 at java.lang.StringBuilder.substring(StringBuilder.java:77)
 at dev.patrickgold.florisboard.ime.core.Region.getText(EditorInstance.kt:914)
 at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$2$1.invokeSuspend(TextInputManager.kt:459)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

</details>

Is this related or should I open a new issue?
