### ISSUE TITLE
Changing the theme from dark mode or light mode will crash florisboard

### ISSUE THREAD

**Issue by main-character** [florisboard/florisboard#803]
#### Short descriptions
Switching from dark to light more or vice versa crashes florisboard 

#### Steps to reproduce
1. Change theme of your phone to dark mode or light mode
2. Try to open the keyboard 
3. See crash

Im using the latest Florisboard v 0.3.11-beta02

#### Environment information
- FlorisBoard Version: 0.3.11-beta02 (37)
- Device: Realme RMX2001
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1620122351721.stacktrace</summary>

```
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:602)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboard.layout(TextKeyboard.kt:159)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onLayoutInternal(TextKeyboardView.kt:637)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.notifyStateChanged(TextKeyboardView.kt:179)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.setComputedKeyboard(TextKeyboardView.kt:168)
	at dev.patrickgold.florisboard.ime.text.smartbar.SmartbarView$onAttachedToWindow$3$1$1.invokeSuspend(SmartbarView.kt:129)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>

**Comment by Glitchy-Tozier** [comment]
Does this still happen in 0.3.11-beta03 ?

**Comment by main-character** [comment]
is it released? let me try sir

**Comment by Glitchy-Tozier** [comment]
Pretty sure it has been released; I've already seen bug reports for it.

**Comment by main-character** [comment]
guess ill have to close the issue. Thanks for replying sir.

**Comment by Glitchy-Tozier** [comment]
Great, thank you for testing it out sir!
