### ISSUE TITLE
NPE: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()'

### ISSUE THREAD

**Issue by matttbe** [florisboard/florisboard#81]
Hello,

When trying the app for the first time, I got this crash:

```
~~~ 1607930111812.stacktrace ~~~

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.onFinishInputView(FlorisBoard.kt:237)
	at android.inputmethodservice.InputMethodService.finishViews(InputMethodService.java:2218)
	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2236)
	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2229)
	at android.inputmethodservice.InputMethodService.access$700(InputMethodService.java:261)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:693)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInputWithToken(InputMethodService.java:663)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:233)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7657)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I am on Android 11 without Google Apps. Version 0.3.0 of the app.
Before this crash, I had the wizard screen and then I changed some settings, e.g. dark mode with dark nav bar, glyde, etc. Then I switched to another app to try the new keyboard. I had the smileys view and I was unable to switch to the keyboard view. After the crash, I got the keyboard but maybe without the modified settings.

I hope this will help!

**Comment by patrickgold** [comment]
Thanks for the bug report, this definitely helps! This issue is definitely connected with #73 (although not the same) and it seems to crash somewhere in the internal event handler chain. I'll look into fixing it!

**Comment by patrickgold** [comment]
This crash should be fixed with above commit. Will ship with the next release v0.3.1.
