### ISSUE TITLE
Random lagging and crashing of Floris board

### ISSUE THREAD

**Issue by mayur392** [florisboard/florisboard#813]
~~~ 1620212620953.stacktrace ~~~

java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~ 1619777880487.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager.setLayout(GlideTypingManager.kt:65)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView$initGestureClassifier$1.run(KeyboardView.kt:147)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, the update may take 1-2 more weeks though.

Let's close this report to keep the list of issues free of duplicates!
