### ISSUE TITLE
App slowdown/error

### ISSUE THREAD

**Issue by davewwjd** [florisboard/florisboard#821]
I had the following error for the first time while typing: 

~~~ 1620311347868.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 1616240 byte allocation with 790824 free bytes and 772KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOfRange(Arrays.java:3589)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:108)
	at dev.patrickgold.florisboard.ime.extension.AssetManager.loadAssetRaw-IoAF18A(AssetManager.kt:202)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:78)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

It has been slowing down lately when i type but this the first error. Thanks!

**Comment by davewwjd** [comment]
Hello,

0.3.10 in the about section

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Glitchy-Tozier** [comment]
I see, thank you for the quick reply!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, releasing the update may take 1 more week though.

Let's close this report to keep the list of issues free of duplicates!
