### ISSUE TITLE
OOM crash

### ISSUE THREAD

**Issue by rakoo** [florisboard/florisboard#832]
I opened Signal from a notification and the keyboard froze, I didn't do anything extravagant so I don't really have a scenario...

```
~~~ 1620474393941.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 96704 free bytes and 90KB until OOM
	at java.util.HashMap.makeTable(HashMap.java:551)
	at java.util.HashMap.doubleCapacity(HashMap.java:570)
	at java.util.HashMap.put(HashMap.java:400)
	at org.json.JSONObject.put(JSONObject.java:264)
	at org.json.JSONTokener.readObject(JSONTokener.java:384)
	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
	at org.json.JSONObject.<init>(JSONObject.java:156)
	at org.json.JSONObject.<init>(JSONObject.java:173)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by kj7rrv** [comment]
Duplicate of #677?

**Comment by rakoo** [comment]
Definitely, I didn't see it when I opened my issue (not a big fan of browsing github on the phone), I'll close this one
