### ISSUE TITLE
Bug/crash report: Failed 32 byte allocation

### ISSUE THREAD

**Issue by tdbe** [florisboard/florisboard#836]
I'm not sure of this is the right way to submit bugs but FlorisBoard started griding to a halt and crashed while I was writing a note. Says it's out of memory which is very strange given the phone wasn't..

```
~~~ 1619912144907.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1678608 free bytes and 1639KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 48234496 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:115)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:136)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:142)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:130)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:109)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords$default(FlorisLanguageModel.kt:93)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:259)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:372)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1619912145809.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1534240 free bytes and 1498KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 28049408 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:115)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:142)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:136)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords(FlorisLanguageModel.kt:109)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listSimilarWords$default(FlorisLanguageModel.kt:93)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:259)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:372)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1620250823500.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 75336 byte allocation with 1231984 free bytes and 1203KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 14417920 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:607)
	at java.util.concurrent.CopyOnWriteArrayList.addIfAbsent(CopyOnWriteArrayList.java:586)
	at dev.patrickgold.florisboard.ime.theme.ThemeManager.registerOnThemeUpdatedListener(ThemeManager.kt:235)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.onAttachedToWindow(PopupExtendedView.kt:92)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:80)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1620436845324.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2382528 free bytes and 2326KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 86507520 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:162)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:253)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:372)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1620507890561.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 753576 free bytes and 735KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 100925440 bytes)
	at java.util.HashMap.newNode(HashMap.java:1746)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at dev.patrickgold.florisboard.ime.core.PrefHelper$Keyboard.getSoundEnabled(PrefHelper.kt:1662)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.keyPressSound(FlorisBoard.kt:653)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.onFlorisTouchEvent(KeyView.kt:294)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.sendFlorisTouchEvent(KeyboardView.kt:321)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:257)
	at android.view.View.dispatchTouchEvent(View.java:15199)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1162)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:188)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should come out during the next week.

Let's close this report to keep the list of issues free of duplicates!
