### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Thewisem** [florisboard/florisboard#867]
#### Short description
Describe what you were doing that could've led to the crash.
No clue

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

~~~ 1620990749907.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 6777968 free bytes and 6MB until OOM; failed due to fragmentation (required continguous free 528384 bytes where largest contiguous free 20480 bytes)
	at java.util.HashMap.resize(HashMap.java:511)
	at java.util.HashMap.addEntry(HashMap.java:808)
	at java.util.HashMap.put(HashMap.java:436)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to fill out this bug-report!

Could you please share which version of the app you are using?

**Comment by Thewisem** [comment]
Version 0.3.10

**Comment by Thewisem** [comment]
Found out why though

**Comment by Thewisem** [comment]
Try playing around with typing settings.

**Comment by Thewisem** [comment]
And choose the keyboard and keep previewing it. And you will get this error

**Comment by Glitchy-Tozier** [comment]
Ah, I see!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the Play-Store and should soon arrive on f-droid.

If you don't mind, I'll close this report to keep the list of issues free of duplicates!
Should this happen again with 0.3.11/0.3.12, make sure to comment in #677! People would be interested to hear!
