### ISSUE TITLE
Crashed when customizing layout of keyboard

### ISSUE THREAD

**Issue by Thewisem** [florisboard/florisboard#868]
#### Short description
Describe what you were doing that could've led to the crash.
I was changing the layout of the keyboard to my liking at the typing section. I also previewed the changes as well.

#### Steps to reproduce
1. Go to FlorisBoard
2. Click on Typing
3. Play around with it for some time
4. See crash

~~~ 1620991248241.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 7017560 free bytes and 6MB until OOM; failed due to fragmentation (required continguous free 528384 bytes where largest contiguous free 57344 bytes)
	at java.util.HashMap.resize(HashMap.java:511)
	at java.util.HashMap.addEntry(HashMap.java:808)
	at java.util.LinkedHashMap.addEntry(LinkedHashMap.java:464)
	at java.util.HashMap.put(HashMap.java:436)
	at org.json.JSONObject.put(JSONObject.java:264)
	at org.json.JSONTokener.readObject(JSONTokener.java:384)
	at org.json.JSONTokener.nextValue(JSONTokener.java:100)
	at org.json.JSONObject.<init>(JSONObject.java:156)
	at org.json.JSONObject.<init>(JSONObject.java:173)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to fill out this bug-report!

Could you please share which version of the app you are using?

**Comment by Thewisem** [comment]
0.3.12

**Comment by Thewisem** [comment]
Sorry for late response. This came in spam folder

**Comment by patrickgold** [comment]
This is a general OOM issue and is/will be addressed in the following stable releases including 0.4.0. Closing to keep the list of issues cleaner.
