### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jweidmaier** [florisboard/florisboard#913]
~~~ 1621389385345.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 666456 free bytes and 650KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 71303168 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:162)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.NgramNode.listAllSameOrderWords(FlorisLanguageModel.kt:163)
	at dev.patrickgold.florisboard.ime.nlp.FlorisLanguageModel.matchAllNgrams(FlorisLanguageModel.kt:253)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary.getTokenPredictions(Flictionary.kt:308)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$$inlined$let$lambda$1.invokeSuspend(TextInputManager.kt:372)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to fill out this bug-report!

Could you please share which version of the app you are using?

**Comment by jweidmaier** [comment]
I'm on version 0.3.10. I'm using a Samsung Galaxy S21 5G on Android 11.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Glitchy-Tozier** [comment]
Ah, I see!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the Play-Store and should soon arrive on f-droid.

If you don't mind, I'll close this report to keep the list of issues free of duplicates!
Should this happen again with 0.3.11/0.3.12, make sure to comment in #677! People would be interested to hear!
