### ISSUE TITLE
Copying an image crashes clipboard

### ISSUE THREAD

**Issue by rayavarapuvikram1** [florisboard/florisboard#923]
Android Version: 7
Phone: Redmi Note 4
Release : 0.3.12
Whenever I am copying an image and opening the clipboard app multiplies a lot of times in the clipboard and crashes.

**Comment by Glitchy-Tozier** [comment]
Thabk you for your bug report!
Could you share the crash log with us?

**Comment by rayavarapuvikram1** [comment]
> Thank you for your bug report!
> Could you share the crash log with us?
#### Environment information
- FlorisBoard Version: 0.3.12-debug (43)
- Device: Xiaomi Redmi Note 4
- Android: 7.0 (cn=N sdk=24)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1621774764909.stacktrace</summary>

```
java.lang.IllegalArgumentException: Don't have this item!
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.getType(FlorisContentProvider.kt:81)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1569)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1633)
	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:424)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1160)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
	at android.content.ClipData$Item.coerceToText(ClipData.java:332)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:124)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:221)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:235)
	at android.content.ClipboardManager$2.handleMessage(ClipboardManager.java:74)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

```
</details>

**Comment by Glitchy-Tozier** [comment]
Thank you, let's see what Patrick can do with this!
Where do you copy an image from to reproduce this bug?

**Comment by rayavarapuvikram1** [comment]
Copied from google.

**Comment by Glitchy-Tozier** [comment]
In the google-app?

**Comment by rayavarapuvikram1** [comment]
Chrome

**Comment by rayavarapuvikram1** [comment]
> In the google-app?

chrome

**Comment by Luensche** [comment]
Do you mean with 'clipboard app' the clipboard history?

**Comment by patrickgold** [comment]
This issue is not reproducible anymore in the latest debug builds, instead of crashing `getType` returns null. Closing thus.
