### ISSUE TITLE
"Crashed due to unexpected error"

### ISSUE THREAD

**Issue by NatSantiago** [florisboard/florisboard#930]
Hi, This morning Florisboard was a bit laggy, and crashed unexpectedly after a few minutes (version 0.3.10, Android 11 MIUI 12)

~~~ 1621780652151.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 465576 free bytes and 454KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:423)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the app-stores. (v0.3.12)  :)

Let's close this report to keep the list of issues free of duplicates!
