### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by religioner** [florisboard/florisboard#937]
~~~ 1621892067169.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:265)
	at android.content.ContentResolver.insert(ContentResolver.java:1290)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:235)
	at android.content.ClipboardManager$2.handleMessage(ClipboardManager.java:74)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6358)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)

**Comment by religioner** [comment]
Медленно запускается. Иногда вылетает. С оригиналом такого не было.

**Comment by Glitchy-Tozier** [comment]
> Медленно запускается. Иногда вылетает. С оригиналом такого не было.

Google Translate: 
>Launches slowly. Sometimes crashes. This was not the case with the original.

**Comment by Glitchy-Tozier** [comment]
Closing this because of two reasons:
1. This is v.0.3.10
2. This probably was fixed in #844
3. (If it still happens in newer versions, it'll get re-reported anyways, with the new reports containing more environment info.)
