### ISSUE TITLE
Stops suddenly while using: no longer possible to use glide typing ever since

### ISSUE THREAD

**Issue by maitra** [florisboard/florisboard#954]
#### Short description

Was typing within WhatsApp.

#### Steps to reproduce

I was using WhatsApp. Suddenly got the notice the Florisboard has closed. I can no longer do any swipe typing. Rebooting the phone does not help.

#### Environment information
- FlorisBoard Version: 0.3.12 (43)
- Device: Samsung SM-G930F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1622215289316.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:150)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getFlorisboard(TextInputManager.kt:63)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.getActiveEditorInstance(TextInputManager.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.access$getActiveEditorInstance(TextInputManager.kt:59)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onUpdateSelection$2$1.invokeSuspend(TextInputManager.kt:459)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! Based on the provided stack trace this behavior makes absolutely no sense at all. FlorisBoard seems to have crashed due to a null reference but normally a phone reboot resets all apps properly. Could you try to clear the cache of FlorisBoard and then force stop and restart it? If the problem still persists then I am baffled, if it has gone away the cache was corrupted somehow.

**Comment by patrickgold** [comment]
@maitra Could you try the latest beta to see if this issue still persists? Thank you!

**Comment by patrickgold** [comment]
Closing due to insufficient info and the glide feature having changed so much since 2021, that this issue does not apply anymore.
