### ISSUE TITLE
Crashed in Fennec (FlorisBoard was not open)

### ISSUE THREAD

**Issue by kj7rrv** [florisboard/florisboard#964]
#### Short description
I rebooted my phone, started using Fennec F-Droid (with tabs that were already open), and got this.

#### Environment information
- FlorisBoard Version: 0.3.11-beta06 (41)
- Device: Motorola moto g power
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = false
suggestions_next_word = true
glide = true
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1620944386076.stacktrace</summary>

```
android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@9397393 -- the specified display can not be found
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1149)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:441)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.app.Dialog.show(Dialog.java:340)
	at android.inputmethodservice.SoftInputWindow.show(SoftInputWindow.java:270)
	at android.inputmethodservice.SoftInputWindow.setToken(SoftInputWindow.java:104)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.attachToken(InputMethodService.java:763)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.initializeInternal(InputMethodService.java:734)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:173)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7803)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>

<details>
<summary>1622397019640.stacktrace</summary>

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier$Pruner.<init>(StatisticalGlideTypingClassifier.kt:370)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.initializePruner(StatisticalGlideTypingClassifier.kt:134)
	at dev.patrickgold.florisboard.ime.text.gestures.StatisticalGlideTypingClassifier.setWordData(StatisticalGlideTypingClassifier.kt:117)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:77)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by kj7rrv** [comment]
I had not used FlorisBoard yet when this happened.

**Comment by patrickgold** [comment]
Thanks for your crash report! The main problem is that the stack trace does not contain a call for a function which I wrote (only Android framework or base classes), so I am unsure if I can do anything against this (binding the dialog window with the service class is normally handled by the base InputMethodService implementation).

**Comment by kj7rrv** [comment]
Oh, okay. Like I said, I just got the notification out of the blue after turning my phone on. IDK whether or not Fennec had anything to do with it.
Should I close the issue?

**Comment by patrickgold** [comment]
> IDK whether or not Fennec had anything to do with it.

Highly unlikely.

>  Should I close the issue?

I think yes. Should this exact issue occur multiple times in the future then feel free to reopen it, as FlorisBoard may be the cause actually, if it was a one-time issue then maybe some token for the window got lost in the Android framework due to a very special constellation of states I probably cannot control.

**Comment by kj7rrv** [comment]
Okay, thank you. I'll reopen if it happens again.
