### ISSUE TITLE
Florisboard crashes when touched with 4 fingers

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#994]
#### Steps to reproduce
Just touch it with 4 fingers at the same time  :)

#### Environment information
- FlorisBoard Version: 0.3.13-beta03 (46)
- Device: Samsung SM-G960F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1622868952824.stacktrace</summary>

```
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2762)
	at dev.patrickgold.florisboard.ime.text.gestures.SwipeGesture$Detector.onTouchUp(SwipeGesture.kt:155)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:354)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:79)
	at android.view.View.dispatchTouchEvent(View.java:14368)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1156)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:177)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
	at android.view.View.dispatchPointerEvent(View.java:14636)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6579)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6357)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5968)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6025)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9029)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8886)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8839)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9166)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report! This crash was fixed with #992 when I played around with the touch logic for detecting rendering issues (kind of accidentally discovered the 4-finger issue) and will be parts of the beta04 release!
