### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by itsmebonny** [florisboard/florisboard#999]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

~~~ 1622926354003.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 40904 free bytes and 39KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.ComparableTimSort.ensureCapacity(ComparableTimSort.java:900)
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:653)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1302)
	at java.util.Arrays.sort(Arrays.java:1485)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at java.util.Collections.sort(Collections.java:159)
	at android.view.ViewGroup$ChildListForAccessibility.sort(ViewGroup.java:8801)
	at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:8784)
	at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:8753)
	at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:3509)
	at android.view.View.dispatchPopulateAccessibilityEvent(View.java:8099)
	at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:3515)
	at android.view.View.dispatchPopulateAccessibilityEvent(View.java:8099)
	at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:3515)
	at android.view.View.dispatchPopulateAccessibilityEvent(View.java:8099)
	at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:3515)
	at com.android.internal.policy.DecorView.dispatchPopulateAccessibilityEventInternal(DecorView.java:646)
	at android.view.View.dispatchPopulateAccessibilityEvent(View.java:8099)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:8061)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:8038)
	at android.view.View.sendAccessibilityEventInternal(View.java:8015)
	at android.view.View.sendAccessibilityEvent(View.java:7979)
	at com.android.internal.policy.DecorView.sendAccessibilityEvent(DecorView.java:634)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2803)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1797)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7759)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Glitchy-Tozier** [comment]
Could you please specify what FlorisBoard version and Android device/version you are on? Thanks in advance!

**Comment by Glitchy-Tozier** [comment]
This issue has been fixed in the newest releases. I'll close this report to clean up the list of issues.
